### ISSUE TITLE
Internal Server Error when inspecting iPhone 5S simulator with 1.2.29 version

### ISSUE THREAD

**Issue by gaboF** [macacajs/app-inspector#101]
When I want to inspect one item in the app, the inspector stopped to work with message Internal Server Error. Terminal shows error: **Error: socket hang up**
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:  1.2.29 

- os version / 系统:10.12.4

- device  information / 设备版本: iPhone 5S simulator

app-inspector -u B6A0C12B-BF57-4190-B859-BC127855A794
>> xctestwd start with port: 8001
>> XCTestWD version: 1.0.15
>> iOS device started: B6A0C12B-BF57-4190-B859-BC127855A794
>> inspector start at: http://192.168.0.101:5678
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /

  **Error: socket hang up
      at createHangUpError (_http_client.js:203:15)
      at Socket.socketOnEnd (_http_client.js:288:23)
      at emitNone (events.js:72:20)
      at Socket.emit (events.js:166:7)
      at endReadableNT (_stream_readable.js:903:12)
      at doNTCallback2 (node.js:439:9)
      at process._tickCallback (node.js:353:17)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404**

**Comment by DanielPradoPino** [comment]
Are you trying to inspect any part of your app using any secured layer as registration, login, etc?
I found yesterday that xcuitestwd is not able to retrieve source tree in this scenario and I needed to switch back to use WebDriverAgent, it is slower but secure.

**Comment by gaboF** [comment]
@DanielPradoPino yes, I'm trying to get locator for password input element. How can I switch back to use WebDriverAgent ?

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor

**Comment by gaboF** [comment]
what does this command npm i macaca-cli -g && macaca doctor should do ?

**Comment by xudafeng** [comment]
paste your environment output to me
