### ISSUE TITLE
after running app-inspector 1.2.29 , I have problem with : please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj

### ISSUE THREAD

**Issue by msmirzazadeh** [macacajs/app-inspector#105]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:
1.2.29

- os version / 系统:
OSX 10.12.2

- device  information / 设备版本:

- terminal log / 终端输出信息:

$ app-inspector -u A93167CF-1590-4011-B8A3-ECE401E8A1E2 --verbose  ‹ruby-2.2.2›
>> request.js:24:12 [master] pid:3185 get remote update info failed.
>> server.js:16:12 [master] pid:3185 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'A93167CF-1590-4011-B8A3-ECE401E8A1E2',
  ip: '192.168.100.216',
  host: 'MSM.local',
  loaded_time: '2017-05-23 15:21:36' }
>> app-inspector.js:43:12 [master] pid:3185 server start at: http://192.168.100.216:5678
>> xctest-client.js:53:14 [master] pid:3185 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:226:14 [master] pid:3185 xcode version: 8.3.2
>> XCTestWD version: 1.0.21
>> xctest-client.js:174:14 [master] pid:3185 2017-05-23 15:21:37.963 xcodebuild[3188:862546]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/E7D26E6C-84DF-445A-84F1-269B928C6529/Session-XCTestWDUITests-2017-05-23_152137-PHOIhZ.log

>> xctest-client.js:175:14 [master] pid:3185 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:3185 2017-05-23 15:21:37.964 xcodebuild[3188:862533] [MT] IDETestOperationsObserverDebug: (627F6FEB-249E-4D8A-8297-B5766BEF326F) Beginning test session XCTestWDUITests-627F6FEB-249E-4D8A-8297-B5766BEF326F at 2017-05-23 15:21:37.964 with Xcode 8E2002 on target <DVTiPhoneSimulator: 0x7fb22fb8a760> {
		SimDevice: SimDevice : iPhone 7 (A93167CF-1590-4011-B8A3-ECE401E8A1E2) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7 } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:175:14 [master] pid:3185 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:3185 2017-05-23 15:21:39.865 xcodebuild[3188:862533] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/E7D26E6C-84DF-445A-84F1-269B928C6529/Session-XCTestWDUITests-2017-05-23_152137-PHOIhZ.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/E7D26E6C-84DF-445A-84F1-269B928C6529/Session-XCTestWDUITests-2017-05-23_152137-PHOIhZ.log}

>> xctest-client.js:175:14 [master] pid:3185 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:3185 2017-05-23 15:21:39.866 xcodebuild[3188:862543] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fb22cc53aa0>

>> xctest-client.js:175:14 [master] pid:3185 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:3185
Testing failed:
	Command /bin/sh failed with exit code 1
** TEST FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Intermediates/XCTestWD.build/Debug-iphonesimulator/XCTestWD.build/Script-63D408691EAB64FC00198736.sh

>> xctest-client.js:175:14 [master] pid:3185 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:3185 (1 failure)

>> xctest-client.js:175:14 [master] pid:3185 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:257:14 [master] pid:3185 killing deviceLogProc pid: 3189
>> xctest-client.js:262:14 [master] pid:3185 killing runnerProc pid: 3188
>> xctest-client.js:185:14 [master] pid:3185 xctest client exit with code: 65, signal: null
>> xctest-client.js:109:18 [master] pid:3185 simulator log process exit with code: null, signal: SIGKILL

this is Script-63D408691EAB64FC00198736.sh content:
#!/bin/sh
/usr/local/bin/carthage copy-frameworks

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor
