### ISSUE TITLE
can't run app-inspector on real Android device

### ISSUE THREAD

**Issue by gaboF** [macacajs/app-inspector#107]
**真机问题先参考 https://testerhome.com/topics/5953**

Hi, I can't run app-inspector - When I run it, it throws error (see below). I can confirm it worked fine a several version ago.

- app inspector version / 版本号: 2.0.1 

- os version / 系统: Mac OS 10.12.4

- device  information / 设备版本: Galaxy S5 / 6.0.1 Android

- terminal log / 终端输出信息:

gabo:~ gabo$ app-inspector -u 9e6396b4 --verbose
>> port: 5678 was occupied, changed port: 5680
>> server.js:16:12 [master] pid:1546 server start with config:
 { port: 5680,
  verbose: true,
  udid: '9e6396b4',
  ip: '10.16.32.115',
  host: 'gabo',
  loaded_time: '2017-05-25 13:40:41' }
>> app-inspector.js:43:12 [master] pid:1546 server start at: http://10.16.32.115:5680
{ [Error: Command failed: /bin/sh -c /Users/gabo/Development/android-sdk-macosx/platform-tools/adb -s 9e6396b4 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing
cannot stat '/usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk': No such file or directory
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /Users/gabo/Development/android-sdk-macosx/platform-tools/adb -s 9e6396b4 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by xudafeng** [comment]
check your Android SDK environment

**Comment by gaboF** [comment]
I update android SDK but now I got the following error:
gabo:tools gabo$ app-inspector -u 9e6396b4
path.js:424
    var path = (i >= 0) ? arguments[i] : process.cwd();
                                                 ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.posix.resolve (path.js:424:50)
    at Function.Module._resolveLookupPaths (module.js:249:17)
    at Function.Module._resolveFilename (module.js:327:31)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/bin/app-inspector:10:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by gaboF** [comment]
I check SDK and everything looks alright.I also tried appium doctor for
Android and it looks correct:

gabo:~ gabo$ appium-doctor --android

info AppiumDoctor Appium Doctor v.1.2.5

info AppiumDoctor ### Diagnostic starting ###

info AppiumDoctor  ✔ ANDROID_HOME is set to:
/Users/gabo/Development/android-sdk-macosx

info AppiumDoctor  ✔ JAVA_HOME is set to:
/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home

info AppiumDoctor  ✔ adb exists at:
/Users/gabo/Development/android-sdk-macosx/platform-tools/adb

info AppiumDoctor  ✔ android exists at:
/Users/gabo/Development/android-sdk-macosx/tools/android

info AppiumDoctor  ✔ emulator exists at:
/Users/gabo/Development/android-sdk-macosx/tools/emulator

info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set

info AppiumDoctor ### Diagnostic completed, no fix needed. ###

info AppiumDoctor

info AppiumDoctor Everything looks good, bye!

info AppiumDoctor


Whad do you suggest ?

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor

**Comment by gaboF** [comment]
this is output after running that command. issue still persists.

npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please
install the latest version of pug instead of jade

npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue

npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will
fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon
as possible. Use 'npm ls graceful-fs' to find it in the tree.

/usr/local/bin/macaca ->
/usr/local/lib/node_modules/macaca-cli/bin/macaca-cli


> macaca-cli@2.0.1 postinstall /usr/local/lib/node_modules/macaca-cli

> node ./scripts/print.js



@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@888
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0Lt111111tL0
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0GCLCG8@01ii1fLCGGGGCC8
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80GLfCfL0
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80GCLLfttttt1i1tfffLCG08
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8GLti;;;;;;;;;;;;;;;;;;;;;;;;itfC0@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@8Cti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i1LG8
@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@0L1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;1L0
@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@8L1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;if
0@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@880088@@@@0t;;;;;;;;;;;itLCG0000GCLt1;;;;itfCGG000GCLf1;
;;;;;;;;;;;1C8@@@80008@@@@@@@@@@@

@@@@@@8Cti;;;;;;itLt;;;;;;;;;;tC8@@@@@@@@@@@@@@8GC0@@@@@@@@@@@@@@8Gfi
;;;;;;;;;;;t1i;;;;;i1fG8@@@@@@

@@@@0t;;;;;;;;;;;;;;;;;;;;;;L8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C1
;;;;;;;;;;;;;;;;;;;;;if8@@@@

@@@L;;;;;;;;;;;;;;;;;;;;;;t8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C;
;;;;;;;;;;;;;;;;;;;;;iG@@@

@@L;;;;;;;;;;;;;;;;;;;;;;L@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0;
;;;;;;;;;;;;;;;;;;;;;;0@@

@8;;;;;;;;;;;;;;;;;;;;;;f@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@G;
;;;;;;;;;;;;;;;;;;;;;1@@

@G;;;;;;;;;;;;;;;;;;;;;;8@@@@@@@@@8CfLG@@@@@@@@@@@@@@@@@8CfLC@@@@@@@@@@@@@t
;;;;;;;;;;;;;;;;;;;;;i@@

@8;;;;;;;;;;;;;;;;;;;;;t@@@@@@@@@G;;;;;t@@@@@@@@@@@@@@@8i;;;;i8@@@@@@@@@@@G
;;;;;;;;;;;;;;;;;;;;;1@@

@@L;;;;;;;;;;;;;;;;;;;;t@@@@@@@@@G;;;;;1@@@@@@@@@@@@@@@8;;;;;i8@@@@@@@@@@@G
;;;;;;;;;;;;;;;;;;;;;0@@

@@@L;;;;;;;;;;;;;;;;;;;i@@@@@@@@@@0LtfC@@@@@@@@@@@@@@@@@8LffC8@@@@@@@@@@@@L;
;;;;;;;;;;;;;;;;;;iG@@@

@@@@0t;;;;;;;;;;;;;;;;;;C@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8;;
;;;;;;;;;;;;;;;;;f8@@@@

@@@@@@0Lti;;;;;;;;;;;;;;i8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Ci
;;;;;;;;;;;;;;1fC8@@@@@@

@@@@@@@@@@1;;;;;;;;;;;fG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@G
t;;;;;;;;;;;i@@@@@@@@@@

@@@@@@@@@@t;;;;;;;;;f8
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@01;;;;;;;;;i
@@@@@@@@@@

@@@@@@@@@@L;;;;;;;;G
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@f;;;;;;;;t
@@@@@@@@@@

@@@@@@@@@@0;;;;;;;0
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@1;;;;;;;C
@@@@@@@@@@

@@@@@@@@@@@1;;;;;t
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@G;;;;;;i8
@@@@@@@@@@

@@@@@@@@@@@0;;;;;L
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;;;;;;C
@@@@@@@@@@@

@@@@@@@@@@@@f;;;;f
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@i;;;;t
@@@@@@@@@@@@

@@@@@@@@@@@@@t;;;i@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8;;;;i8
@@@@@@@@@@@@

@@@@@@@@@@@@@@t;;;t
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@t;;;i8
@@@@@@@@@@@@@

@@@@@@@@@@@@@@@f;;;t8
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8t;;;t8
@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@Gi;;iG
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Gi;;;L
@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@8f;;;tG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8C
1;;;t0@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@0t;;;ifG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0Cti
;;;tG@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@0fi;;;;tLG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80Cti;;;;;
f0@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@8Gt;;;;;;itfLC008@@@@@@@@@@@@@@@@@@880GCLt1;;;;;;;tC8
@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@8Gf1;;;;;;;;;;ii11ttfffLffftt11ii;;;;;;;;;;itC8
@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8Gfti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i1fC0
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8GCLt11i;;;;;;;;;;;;;ii1tfCG0@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8880000000888
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@



Macaca was successfully installed! Please visit: https://macacajs.github.io


/usr/local/lib

└─┬ macaca-cli@2.0.1

  └─┬ detect-port@1.1.3

    └── address@1.0.2



  macaca-doctor version: 2.0.0



  Node.js checklist:


  node env: /usr/local/bin/node

  node version: v4.2.1 lower than v6.9.2


  iOS checklist:


  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`

  Xcode Command Line Tools is ready, version: 2347.

  Xcode is uninstalled

  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`

  ios_webkit_debug_proxy is installed at:
`/usr/local/bin/ios_webkit_debug_proxy`

  carthage require version 0.22.0 and above


  Android checklist:


  JAVA version is `1.8.0_111`

  JAVA_HOME is set to
`/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`

  ANDROID_HOME is set to `/Users/gabo/Development/android-sdk-macosx`

  Platforms is set to
`/Users/gabo/Development/android-sdk-macosx/platforms/android-22`

  ADB tool is set to
`/Users/gabo/Development/android-sdk-macosx/platform-tools/adb`

  Command Line Tools: gradle is uninstalled


  Installed driver list:

**Comment by gaboF** [comment]
I also installed Gradle as macaca doctor recommends but I got same error.

**Comment by xudafeng** [comment]
apk file build failed, pls check the file

/usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk

**Comment by gaboF** [comment]
There is no /build folder in this path /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/
Is there any way how can I recreate it ?
![ce](https://cloud.githubusercontent.com/assets/3266275/26482790/9f13e314-41e9-11e7-8f18-5662e1eaeba3.png)

**Comment by xudafeng** [comment]
0. cd /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/
0. node ./script/install.js

**Comment by xudafeng** [comment]
``` bash
$ cd /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/
$ node ./script/build.js

```

**Comment by gaboF** [comment]
Unfortunately, now it failed with similar error as before:
gabo:uiautomatorwd gabo$ node ./script/build.js
module.js:339
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/script/build.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by xudafeng** [comment]
my god ,
```
$ node ./scripts/build.js

```

**Comment by gaboF** [comment]
Guy @xudafeng , you deserve a big KUDOS ! Thank you very much. All my problem are now solved. I can use app-inspector again ! Perfect!

**Comment by youngchow** [comment]
@gaboF , i got the same error, like follows:
{ Error: Command failed: /Users/roczhang/android-sdks/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing
cannot stat '/usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk': No such file or directory

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/roczhang/android-sdks/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by Metatron7** [comment]
I had the sample error，but i use this method to resolve my problem

$ cd /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/
$ node ./scripts/build.js

**Comment by Jagapd** [comment]
I get the issue when I run the node./script/build.js
I have installed gradle and set path. Gradle -version gives correct result

(node:10116) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): please install gradle
(node:10116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TAVkiev** [comment]
try run in cmd (install it if you not: https://www.npmjs.com/package/macaca-doctor)
"macaca doctor"
in my case everything were good except  GRADLE_HOME was not set as variable (only in path)
then try again, after few minutes it will generate app-debug.apk
