### ISSUE TITLE
app-inspector升级到2.0.1怎么根据xpath定位

### ISSUE THREAD

**Issue by AppleZou** [macacajs/app-inspector#108]
iOS真机上怎么都找不到那个元素
1.Xpath里面为什么会有name，我定位的元素里面没有name
2.使用Xpath定位的话就直接拷贝使用就行了吗
![image](https://cloud.githubusercontent.com/assets/25732354/26483241/a3b8cbac-421e-11e7-82bf-1b31d6e5522f.png)

**Comment by xudafeng** [comment]
right
