### ISSUE TITLE
return full xpath into inspector screen

### ISSUE THREAD

**Issue by gaboF** [macacajs/app-inspector#109]
There is no full xpath in Inspector page since 2.0 version of app-inspector. I kindly ask you to revert to return it. Shortened xpath can remain but full xpath is essential and should be available too.

Please re-add it there.
Thanks.

- app inspector version / 版本号: 2.0.1

**Comment by xudafeng** [comment]
@gaboF

aha? send me pull request？

**Comment by gaboF** [comment]
@xudafeng Sorry, I don't know how to send you pull request. I hope the Full xpath come back.

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/2e7ab7865e28e7ef7e96af14dc560d53ea86243c
