### ISSUE TITLE
	Test target XCTestWDUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted) ** TEST FAILED **

### ISSUE THREAD

**Issue by msmirzazadeh** [macacajs/app-inspector#110]
Test target XCTestWDUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

- app inspector version / 版本号:
2.0.1

- os version / 系统:
OSX 10.12.2

- device  information / 设备版本:

- terminal log / 终端输出信息:

server.js:16:12 [master] pid:4634 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'A908E923-3BBB-4D4A-808A-4CC69ED2C33E',
  ip: '192.168.100.216',
  host: 'MSM.local',
  loaded_time: '2017-05-27 10:37:44' }
>> app-inspector.js:43:12 [master] pid:4634 server start at: http://192.168.100.216:5678
>> xctest-client.js:53:14 [master] pid:4634 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:226:14 [master] pid:4634 xcode version: 8.3.2
>> XCTestWD version: 1.0.26
>> xctest-client.js:174:14 [master] pid:4634 2017-05-27 10:37:44.743 xcodebuild[4639:527131]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/111DC53A-3DAB-432C-AC12-6FFB4AD1584A/Session-XCTestWDUITests-2017-05-27_103744-dG5LNP.log

>> xctest-client.js:175:14 [master] pid:4634 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:4634 2017-05-27 10:37:44.743 xcodebuild[4639:527120] [MT] IDETestOperationsObserverDebug: (50CF565E-9115-4655-B999-F3D2476F239C) Beginning test session XCTestWDUITests-50CF565E-9115-4655-B999-F3D2476F239C at 2017-05-27 10:37:44.743 with Xcode 8E2002 on target <DVTiPhoneSimulator: 0x7f90b847a710> {
		SimDevice: SimDevice : iPhone 6 (A908E923-3BBB-4D4A-808A-4CC69ED2C33E) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:175:14 [master] pid:4634 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:4634 2017-05-27 10:37:49.881 xcodebuild[4639:527120] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

>> xctest-client.js:175:14 [master] pid:4634 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:4634
Testing failed:
	Test target XCTestWDUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

>> xctest-client.js:175:14 [master] pid:4634 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:257:14 [master] pid:4634 killing deviceLogProc pid: 4640
>> xctest-client.js:262:14 [master] pid:4634 killing runnerProc pid: 4639
>> xctest-client.js:185:14 [master] pid:4634 xctest client exit with code: 65, signal: null
>> xctest-client.js:109:18 [master] pid:4634 simulator log process exit with code: null, signal: SIGKILL

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor

**Comment by HeartIsBeat** [comment]
![image](https://user-images.githubusercontent.com/20472976/28303713-0b825a24-6bc7-11e7-8074-6aa57c35fb85.png)
@xudafeng 我也出现这个问题，怎么解决呢？
