### ISSUE TITLE
输入框xpath不可用

### ISSUE THREAD

**Issue by grubby2013** [macacajs/app-inspector#111]
- app inspector version / 版本号:

2.0.1
- os version / 系统:
xcode 8.3.2

- device  information / 设备版本:
iPhone6s plus（iOS 10.3.1）

- terminal log / 终端输出信息:

无法通过XPath找到输入框

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/2e7ab7865e28e7ef7e96af14dc560d53ea86243c

**Comment by grubby2013** [comment]
依然不能用
