### ISSUE TITLE
Socket Hangup Error when refreshing the browser

### ISSUE THREAD

**Issue by kahyalar** [macacajs/app-inspector#113]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:
It cames empty when I write app-inspector -v

- os version / 系统:

- device  information / 设备版本:
                deviceSerialNumber:         Serial Number
		identifier:                 UDID
		deviceClass:                iPhone
		deviceName:                 A Phone
		deviceIdentifier:           UDID
		productVersion:             9.3.4
		buildVersion:               13G35
		deviceSoftwareVersion:      9.3.4 (13G35)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12805275648
		deviceAvailableCapacity:    10458669056
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f8665d91a60 Xcode.DeviceType.iPhone>

- terminal log / 终端输出信息:

```
>> iOS device started: 8cf88820750279d6cd49b48d5a079a9315598778
>> inspector start at: http://192.168.10.138:5678
  <-- GET /
>> ios.js:67:10 [master] pid:8410 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
>> ios.js:67:10 [master] pid:8410 Dump iOS XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/ios.json
  --> GET / 200
  <-- GET /
>> helper.js:94:16 [master] pid:8410 xctest client proxy error with: Error: socket hang up

  Error: socket hang up
      at createHangUpError (_http_client.js:302:15)
      at Socket.socketOnEnd (_http_client.js:394:23)
      at emitNone (events.js:91:20)
      at Socket.emit (events.js:188:7)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

I want to open an application then use inspector. When I ran that command app-inspector -u udid, it gets only main screen page. When I open an app, then refresh the browser, I saw socket hang up error. When browser's screen became Internal server error message only.

Any help, thanks !

**Comment by kahyalar** [comment]
Okay, it's returned normal. Just an internet issue with my ISP. Can be closed, thank you.

**Comment by KaranKKK** [comment]
Last login: Tue Jul  4 17:51:55 on ttys001
macmini-divya:~ ca_automation$ ./node_modules/.bin/app-inspector -u 2a0d1e5f1a6e30135bca4ef16fdbd8f275300eaf -p 8001
>> xctestwd start with port: 8002
>> XCTestWD version: 1.0.42
undefined
>> iOS device started: 2a0d1e5f1a6e30135bca4ef16fdbd8f275300eaf
>> inspector start at: http://192.168.1.88:8001
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8002
      at Object.exports._errnoException (util.js:1016:11)
      at exports._exceptionWithHostPort (util.js:1039:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404


I am getting this error when i am using that command 

and in the browser it is showing Internal Server Error....



can any one help me please

**Comment by kahyalar** [comment]
Correct me, if I'm wrong but i think your installation is not properly done. Because, favicon is macacajs's file and if you get 404 on it; my opinion is run macaca doctor and fix any problem if exist. Than try again, if you get still errors, i think re-install can be best option.

Good luck

**Comment by KaranKKK** [comment]
Thanks for the reply.........
yes by installing macaca doctor ...i fix the issue and its worked....

**Comment by kahyalar** [comment]
I'm happy to hear that, so keep on testing! :)

**Comment by KaranKKK** [comment]
ya ..by ur help the process again come in platform.... @kahyalar
