### ISSUE TITLE
有的时候可以，有的时候就不行，需要重启设备才可以

### ISSUE THREAD

**Issue by RmondJone** [macacajs/app-inspector#115]
OSX系统：10.12，Xcode:8.3.2 ,真机：10.2 5C
Last login: Tue Jun 13 17:43:13 on ttys000
localhost:~ ghl$ app-inspector -u 327148b379e10cad789f12bd457b76018fd0eeca --verbose
>> request.js:24:12 [master] pid:13279 get remote update info failed.
>> server.js:16:12 [master] pid:13279 server start with config:
 { port: 5678,
  verbose: true,
  udid: '327148b379e10cad789f12bd457b76018fd0eeca',
  ip: '172.32.145.105',
  host: 'localhost',
  loaded_time: '2017-06-13 17:55:28' }
>> app-inspector.js:43:12 [master] pid:13279 server start at: http://172.32.145.105:5678
>> xctest-client.js:52:14 [master] pid:13279 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:13279 xcode version: 8.3.2
>> XCTestWD version: 1.0.31
>> xctest-client.js:172:14 [master] pid:13279 2017-06-13 17:55:30.436 xcodebuild[13286:657335]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ghl/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/1F0E4E84-297C-4560-AB00-7B2AA66CE86B/Session-XCTestWDUITests-2017-06-13_175530-er64nG.log

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13279 2017-06-13 17:55:30.437 xcodebuild[13286:657333] [MT] IDETestOperationsObserverDebug: (0E9E154E-5CFE-4E7C-A9D9-EC6B9DE60047) Beginning test session XCTestWDUITests-0E9E154E-5CFE-4E7C-A9D9-EC6B9DE60047 at 2017-06-13 17:55:30.437 with Xcode 8E2002 on target <DVTiOSDevice: 0x7fd41cd44a10> {
		deviceSerialNumber:         F73LC1H2FNLT
		identifier:                 327148b379e10cad789f12bd457b76018fd0eeca
		deviceClass:                iPhone
		deviceName:                 郭翰林
		deviceIdentifier:           327148b379e10cad789f12bd457b76018fd0eeca
		productVersion:             10.2
		buildVersion:               14C92
		deviceSoftwareVersion:      10.2 (14C92)
		deviceArchitecture:         armv7s
		deviceTotalCapacity:        13087416320
		deviceAvailableCapacity:    1756647424
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fd4193d4030 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.2 (14C92))

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13279 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/17/_rgt2qfx51lgfksdh8_qp9rw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/6c373746a3d6fe6af5c886dc6a4eeccd/327148b379e10cad789f12bd457b76018fd0eeca/XCTestWDUITests-Runner.app
state->new_bundle: /Users/ghl/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphoneos/XCTestWDUITests-Runner.app
state->dst_bundle: /var/folders/17/_rgt2qfx51lgfksdh8_qp9rw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.mcqpVo/XCTestWDUITests-Runner.app_sparse.ipa/Payload//XCTestWDUITests-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/17/_rgt2qfx51lgfksdh8_qp9rw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.mcqpVo/XCTestWDUITests-Runner.app_sparse.ipa

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13279 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/17/_rgt2qfx51lgfksdh8_qp9rw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.mcqpVo/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13279 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/17/_rgt2qfx51lgfksdh8_qp9rw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.mcqpVo/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13279 2017-06-13 17:55:52.452 xcodebuild[13286:657333] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13279 
Testing failed:

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:13279 	Test target XCTestWDUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

>> xctest-client.js:173:14 [master] pid:13279 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:13279 killing deviceLogProc pid: 13283
>> xctest-client.js:260:14 [master] pid:13279 killing runnerProc pid: 13286
>> xctest-client.js:266:14 [master] pid:13279 killing iproxyProc pid: 13285
>> xctest-client.js:183:14 [master] pid:13279 xctest client exit with code: 65, signal: null
>> xctest-client.js:211:14 [master] pid:13279 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:145:16 [master] pid:13279 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:247:14 [master] pid:13279 Fail to start xctest: undefined
undefined
>> iOS device started: 327148b379e10cad789f12bd457b76018fd0eeca
>> inspector start at: http://172.32.145.105:5678
  <-- GET /
>> helper.js:94:16 [master] pid:13279 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

**Comment by chenqb** [comment]
需要插拔usb线，不过不是根本办法

**Comment by xudafeng** [comment]
@chenqb 需要插拔 usb 说明 iproxy 的 usb 连接出问题了，可以提供更多信息吗？
