### ISSUE TITLE
socket hangup error

### ISSUE THREAD

**Issue by kahyalar** [macacajs/app-inspector#118]
I get an error when trying to inspect real ios device. Inspector starts correctly but when i refresh the page, socket hang up error shows up. Any advice, thanks.

Environment check:
``` 
  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/kahyalar/Library/Android/sdk`
  Platforms is set to `/Users/kahyalar/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/kahyalar/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.23
  ios: 2.0.18
```
- terminal log / 终端输出信息:

```
>> port: 5678 was occupied, changed port: 5679
>> xctestwd start with port: 8001
>> XCTestWD version: 1.0.31
>> iOS device started: 8cf88820750279d6cd49b48d5a079a9315598778
>> inspector start at: http://192.168.10.23:5679
  <-- GET /
  --> GET / 200
  <-- GET /
  <-- GET /

  Error: socket hang up
      at createHangUpError (_http_client.js:343:15)
      at Socket.socketOnEnd (_http_client.js:435:23)
      at emitNone (events.js:110:20)
      at Socket.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)


  Error: socket hang up
      at createHangUpError (_http_client.js:343:15)
      at Socket.socketOnEnd (_http_client.js:435:23)
      at emitNone (events.js:110:20)
      at Socket.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)

  <-- GET /

  Error: socket hang up
      at createHangUpError (_http_client.js:343:15)
      at Socket.socketOnEnd (_http_client.js:435:23)
      at emitNone (events.js:110:20)
      at Socket.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector#ios-real-device

**Comment by kahyalar** [comment]
I install it like that. Also it's worked, while ago. I just updated and this is the result. 

Error log with verbose:

>> server.js:16:12 [master] pid:4021 server start with config:
 { port: 5678,
  verbose: true,
  udid: '8cf88820750279d6cd49b48d5a079a9315598778',
  ip: '192.168.10.23',
  host: 'Furkan-MacBook-Pro.local',
  loaded_time: '2017-06-19 10:43:03' }
>> app-inspector.js:43:12 [master] pid:4021 server start at: http://192.168.10.23:5678
>> xctest-client.js:52:14 [master] pid:4021 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:4021 xcode version: 8.3.2
>> XCTestWD version: 1.0.37
>> xctest-client.js:172:14 [master] pid:4021 2017-06-19 10:43:06.393 xcodebuild[4027:152475]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/F42FE0A4-70BA-461E-8E41-B87CA408784C/Session-XCTestWDUITests-2017-06-19_104306-hewRGH.log

>> xctest-client.js:173:14 [master] pid:4021 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:4021 2017-06-19 10:43:06.395 xcodebuild[4027:152467] [MT] IDETestOperationsObserverDebug: (5DAAE3CD-138D-465C-8F9F-3CE9D53556DB) Beginning test session XCTestWDUITests-5DAAE3CD-138D-465C-8F9F-3CE9D53556DB at 2017-06-19 10:43:06.394 with Xcode 8E2002 on target <DVTiOSDevice: 0x7fca2e749890> {
		deviceSerialNumber:        Serial Number
		identifier:                 UDID
		deviceClass:                iPhone
		deviceName:                 testinium’s iPhone
		deviceIdentifier:           UDID
		productVersion:             9.3.4
		buildVersion:               13G35
		deviceSoftwareVersion:      9.3.4 (13G35)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12805275648
		deviceAvailableCapacity:    10476920832
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fca2e50a520 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (9.3.4 (13G35))

>> xctest-client.js:173:14 [master] pid:4021 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:4021 2017-06-19 10:43:15.038 xcodebuild[4027:152467] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/F42FE0A4-70BA-461E-8E41-B87CA408784C/Session-XCTestWDUITests-2017-06-19_104306-hewRGH.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/F42FE0A4-70BA-461E-8E41-B87CA408784C/Session-XCTestWDUITests-2017-06-19_104306-hewRGH.log}

>> xctest-client.js:173:14 [master] pid:4021 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:4021
Testing failed:

>> xctest-client.js:173:14 [master] pid:4021 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:4021 	Command /bin/sh failed with exit code 162
** TEST FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Intermediates/XCTestWD.build/Debug-iphoneos/XCTestWDUITests.build/Script-7F90C8321EF231B2003F2DA0.sh
(1 failure)

>> xctest-client.js:173:14 [master] pid:4021 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:4021 killing deviceLogProc pid: 4024
>> xctest-client.js:260:14 [master] pid:4021 killing runnerProc pid: 4027
>> xctest-client.js:266:14 [master] pid:4021 killing iproxyProc pid: 4026
>> xctest-client.js:183:14 [master] pid:4021 xctest client exit with code: 65, signal: null
>> xctest-client.js:145:16 [master] pid:4021 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:247:14 [master] pid:4021 Fail to start xctest: undefined
undefined
>> iOS device started: 8cf88820750279d6cd49b48d5a079a9315598778
>> inspector start at: http://192.168.10.23:5678
>> xctest-client.js:211:14 [master] pid:4021 iproxy exit with code: null, signal: SIGKILL
  <-- GET /
>> helper.js:94:16 [master] pid:4021 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1014:11)
      at exports._exceptionWithHostPort (util.js:1037:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)

**Comment by kahyalar** [comment]
Update:

I re-install all elements according to installation guide. It opens but when i refresh the page on browser, i get socket hang up error. 

Error log:
  Error: socket hang up
      at createHangUpError (_http_client.js:343:15)
      at Socket.socketOnEnd (_http_client.js:435:23)
      at emitNone (events.js:110:20)
      at Socket.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by kahyalar** [comment]
I briefly search about this. And this error is beacuse of the application. Macaca Inspector is a flawless again! Can be closed. Thanks

**Comment by govinda-tiket** [comment]
Hey @kahyalar , 
What do you mean by "Macaca Inspector is a flawless again! Can be closed"? is it solved or yet to be solved?

**Comment by kahyalar** [comment]
Hi @govinda-tiket , sorry for creating confusion. I edit my comment. It's solved then I closed.
