### ISSUE TITLE
执行app-inspector -u android模拟器,报错Internal Server Error

### ISSUE THREAD

**Issue by mijiawei** [macacajs/app-inspector#120]
Environment check:

``` 
macaca-doctor version: 2.0.1


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.4

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/micky/Library/Android/sdk`
  Platforms is set to `/Users/micky/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/micky/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.30
  chrome: 1.0.6
  electron: 1.1.6 [out-of-date]
  ios: 2.0.22

```

---

- app inspector version / 版本号:2.0.6

- terminal log / 终端输出信息:

```
>> UIAutomatorWD http server ready
>> Android device started: 192.168.56.101:5555
>> inspector start at: http://192.168.1.8:5678
  <-- GET /
>> proxy.js:55:14 [master] pid:42884 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9007/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:83:20 [master] pid:42884 Got response with status 200: {"status":0,"value":"","sessionId":null}
>> Dump Android XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/android.json

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/android.js:28:13)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/android.js:65:14)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:109:7)


```

**Comment by kahyalar** [comment]
Can you run it with --verbose parameter for better log output ?

**Comment by mijiawei** [comment]
'''
>> server.js:16:12 [master] pid:95379 server start with config:
 { port: 5678,
  verbose: true,
  udid: '192.168.56.101:5555',
  ip: '172.17.7.206',
  host: 'mijiaweideMacBook-Air.local',
  loaded_time: '2017-07-27 14:26:33' }
>> app-inspector.js:43:12 [master] pid:95379 server start at: http://172.17.7.206:5678
>> uiautomator-client.js:56:14 [master] pid:95379 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:56:14 [master] pid:95379 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9002<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: 192.168.56.101:5555
>> inspector start at: http://172.17.7.206:5678
  <-- GET /
>> proxy.js:55:14 [master] pid:95379 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9002/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:83:20 [master] pid:95379 Got response with status 200: {"status":0,"value":"","sessionId":null}
>> Dump Android XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/android.json

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/android.js:28:13)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/android.js:65:14)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
'''

**Comment by meowtec** [comment]
Now if the DOM data was parsed error, app-inspector will print the raw data. 
Please upgrade app-inspector.
