### ISSUE TITLE
app-inspector上的xpath获取页面元素，unable to find an element

### ISSUE THREAD

**Issue by AppleZou** [macacajs/app-inspector#122]
使用xpath="
//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]"定位那个Name的输入框定位不到,一用xpath定位 就会socket hang up
![image](https://user-images.githubusercontent.com/25732354/27369461-97bacd70-568a-11e7-99f0-3798f5eb894f.png)
还有就是xpath_lite跟xpath有什么区别呀

**Comment by xudafeng** [comment]
升级新版app-inspector
