### ISSUE TITLE
App Inspector can not find Info.plist in XCTestWD.app

### ISSUE THREAD

**Issue by fisharu** [macacajs/app-inspector#124]
- app inspector version / 版本号: 2.0.6
-updated macaca cli to newest, updated carthage to newest, macaca-doctor states there are no issues with iOS-related environment checks

- os version / 系统: macOS 10.12.5

- device  information / 设备版本: Iphone 7 Simulator iOS 10.3

- terminal log / 终端输出信息:

app-inspector -u B52B0889-7CCB-486F-B2C4-CB70169B7498 --verbose
>> server.js:16:12 [master] pid:53361 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'B52B0889-7CCB-486F-B2C4-CB70169B7498',
  ip: '10.50.66.115',
  host: 'LocalMachineName.local',
  loaded_time: '2017-06-26 18:33:38' }
>> app-inspector.js:43:12 [master] pid:53361 server start at: http://10.50.66.115:5678
>> xctest-client.js:52:14 [master] pid:53361 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:53361 xcode version: 8.3.3
>> XCTestWD version: 1.0.40
>> xctest-client.js:172:14 [master] pid:53361 2017-06-26 18:33:41.645 xcodebuild[53364:6212935]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/9C34A986-4333-43BE-8765-E74AB31A523F/Session-XCTestWDUITests-2017-06-26_183341-2sj6BM.log

>> xctest-client.js:173:14 [master] pid:53361 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:53361 2017-06-26 18:33:41.645 xcodebuild[53364:6212861] [MT] IDETestOperationsObserverDebug: (CEFC044F-C5FD-49F7-907A-2FCA6B83A25B) Beginning test session XCTestWDUITests-CEFC044F-C5FD-49F7-907A-2FCA6B83A25B at 2017-06-26 18:33:41.645 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7fd5b5047be0> {
		SimDevice: SimDevice : iPhone 7 (B52B0889-7CCB-486F-B2C4-CB70169B7498) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7 } runtime={ SimRuntime : 10.3.1 (14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3.1 (14E8301))

>> xctest-client.js:173:14 [master] pid:53361 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:53361 2017-06-26 18:33:50.139 xcodebuild[53364:6212861] Error Domain=IDEFoundationErrorDomain Code=1 "No Info.plist found for application at path /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist" UserInfo={NSLocalizedDescription=No Info.plist found for application at path /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist}
2017-06-26 18:33:50.139 xcodebuild[53364:6212861] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "No Info.plist found for application at path /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist If you believe this error represents a bug, please attach the log file at /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/9C34A986-4333-43BE-8765-E74AB31A523F/Session-XCTestWDUITests-2017-06-26_183341-2sj6BM.log" UserInfo={NSLocalizedDescription=No Info.plist found for application at path /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist If you believe this error represents a bug, please attach the log file at /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/9C34A986-4333-43BE-8765-E74AB31A523F/Session-XCTestWDUITests-2017-06-26_183341-2sj6BM.log}

>> xctest-client.js:173:14 [master] pid:53361 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:53361 2017-06-26 18:33:50.142 xcodebuild[53364:6212945] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fd5b51af100>

>> xctest-client.js:173:14 [master] pid:53361 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:53361 
Testing failed:
	Test target XCTestWDUITests encountered an error (No Info.plist found for application at path /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist If you believe this error represents a bug, please attach the log file at /Users/username/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/9C34A986-4333-43BE-8765-E74AB31A523F/Session-XCTestWDUITests-2017-06-26_183341-2sj6BM.log)

>> xctest-client.js:173:14 [master] pid:53361 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:53361 ** TEST FAILED **

>> xctest-client.js:173:14 [master] pid:53361 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:53361 killing deviceLogProc pid: 53365
>> xctest-client.js:260:14 [master] pid:53361 killing runnerProc pid: 53364
>> xctest-client.js:183:14 [master] pid:53361 xctest client exit with code: 65, signal: null
>> xctest-client.js:108:18 [master] pid:53361 simulator log process exit with code: null, signal: SIGKILL

Thank you for any help you can give me with this situation.

**Comment by kahyalar** [comment]
Hello. 
Did you change your username or is it really /Users/username/... ?

I'm not sure about it but, maybe you can use authorize-ios(or with sudo) for authorizing your iOS simulator.

**Comment by xudafeng** [comment]
update inspector to the latest one
