### ISSUE TITLE
app-inspector升级后必须卸载掉真机原来的XCTestWDUITests

### ISSUE THREAD

**Issue by magaofei** [macacajs/app-inspector#126]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:
2.0.6

- os version / 系统:
10.3.2

- device  information / 设备版本:
iPad Pro 9.7

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by HeartIsBeat** [comment]
@magaofei 怎么卸载呢？卸载后怎么重装呢？

**Comment by magaofei** [comment]
@HeartIsBeat 在测试设备上删除App , 再次运行就直接安装了

**Comment by HeartIsBeat** [comment]
@magaofei 
哦哦，你说的是这个意思啊。
但是卸了，重新跑app-inspecotor -u deviceid  还是不行。
自从app-inspector第一次成功取到元素后，后面都不行了。

**Comment by magaofei** [comment]
@HeartIsBeat 后边加上 `--verbose` 发一下详细日志

**Comment by HeartIsBeat** [comment]
@magaofei 日志像这个了 #110

**Comment by magaofei** [comment]
@HeartIsBeat 应该是签名问题, 你重新签名

**Comment by magaofei** [comment]
@HeartIsBeat 对, 点一下上面的Product -> Test 试试能不能自己启动, 个人帐号的话需要在真机上信任一下, 还有不能超过两台设备

**Comment by HeartIsBeat** [comment]
全卸了，得重新信任一下，因此都是跑两次
还是不行的哦，问题一样， 不过有两个告警
![image](https://user-images.githubusercontent.com/20472976/28304387-ee721b2e-6bc9-11e7-8561-764c3fff785c.png)
![image](https://user-images.githubusercontent.com/20472976/28304400-010aae0e-6bca-11e7-8f7c-e9826c925285.png)

**Comment by magaofei** [comment]
@HeartIsBeat  代码警告没事, `macaca doctor` 看一下? 或者设备都重启一下?

**Comment by HeartIsBeat** [comment]
重启了设备/mac还是不行哟
![image](https://user-images.githubusercontent.com/20472976/28305010-aa503e82-6bcc-11e7-9ee8-126b9ff9d349.png)

**Comment by HeartIsBeat** [comment]
@magaofei 错了，重启了mac和设备可以了。。我再多跑几次，多谢啊！
