### ISSUE TITLE
android 手机小米5splus 无法使用

### ISSUE THREAD

**Issue by melissalu** [macacajs/app-inspector#127]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:
2.0.1 

- os version / 系统:

mac 10.12.4 (16E195)
- device  information / 设备版本:
6.0.1

- terminal log / 终端输出信息:

```>> Android device started: 3641c1ab
>> inspector start at: http://10.9.240.36:5678
  <-- GET /
  <-- GET /
  <-- GET /
  <-- GET /

```

> try `app-inspector -u xxxx --verbose` for more log detail.

>> request.js:24:12 [master] pid:33175 get remote update info failed.
>> server.js:16:12 [master] pid:33175 server start with config:
 { port: 5678,
  verbose: true,
  udid: '3641c1ab',
  ip: '10.9.240.36',
  host: 'MELISSALU-MC4',
  loaded_time: '2017-07-12 10:59:10' }
>> app-inspector.js:43:12 [master] pid:33175 server start at: http://10.9.240.36:5678
>> UIAutomatorWD http server ready
>> Android device started: 3641c1ab
>> inspector start at: http://10.9.240.36:5678
  <-- GET /
>> proxy.js:55:14 [master] pid:33175 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9001/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:61:22 [master] pid:33175 UIAutomatorWD client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:33175 UIAutomatorWD client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:33175 UIAutomatorWD client proxy error with: Error: socket hang up

**Comment by kahyalar** [comment]
Actually, inspecting Android is really easy. So, i think maybe you should run macaca doctor. Then, we can discuss about the output of it.

**Comment by qichuan** [comment]
@melissalu I have published a fix recently for the socket issue, please update the module by `npm i macaca-android -g` and try again.
