### ISSUE TITLE
app-inspector -u deviceid --verbose Fail for device ios version is not match XCTestWD's

### ISSUE THREAD

**Issue by HeartIsBeat** [macacajs/app-inspector#128]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:
2.0.6

- os version / 系统:
10.12.4

- device  information / 设备版本:
iphone touch  ios8.1

- terminal log / 终端输出信息:
![image](https://user-images.githubusercontent.com/20472976/28254820-06fb28c6-6ae3-11e7-9262-74d4d06c95b9.png)

```
Web is Internal Server Error
Using ios simulation iphone 6 10.3 is also failed.
How to let XCTestWD to suit for all ios version？ 
```

> try `app-inspector -u xxxx --verbose` for more log detail.
![image](https://user-images.githubusercontent.com/20472976/28254797-d890e7fa-6ae2-11e7-9155-2f114b6d7c31.png)
I hava changed all XCTestWD and XCTestWDUITests's ios Development target to 8.1，the problem is also.
![image](https://user-images.githubusercontent.com/20472976/28254873-873dd2f4-6ae3-11e7-80d2-b141aa5a2621.png)
![image](https://user-images.githubusercontent.com/20472976/28254858-62db25f6-6ae3-11e7-9f06-2482aa7b6fa3.png)
![image](https://user-images.githubusercontent.com/20472976/28254868-7f4ca62e-6ae3-11e7-8941-77bd5edde72f.png)

**Comment by HeartIsBeat** [comment]
@xudafeng I used ipod touch 9.3.5 .The problem is changed, like #110

**Comment by kahyalar** [comment]
Hi there, did u authorize your simulators. It might be that. Can you download authorize-ios, then just run it. Please let me know :)

**Comment by HeartIsBeat** [comment]
@kahyalar 
Authorize your simulators?  NO.
I have solved the problem by using ipod touch 9.3.5 and  restart mac and device. like #126 
When I use app-inspector -u simulator(ios10.3), it's OK.
Using simulator(ios8.1), it is not OK.

**Comment by SamuelZhaoY** [comment]
XCode 8.3.2+ by default should only support OS version from 9.0 and above. Hence it will not be recommended to use 8.X  iOS simulators

**Comment by HeartIsBeat** [comment]
@SamuelZhaoY  Thankyou for your answer!

**Comment by SamuelZhaoY** [comment]
np ：）
