### ISSUE TITLE
Internal Server Error when macaca inspector used with Real device, works fine in simulators

### ISSUE THREAD

**Issue by HP1508** [macacajs/app-inspector#130]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:
2.0.4

- os version / 系统:
MAC 10.12.3

- device  information / 设备版本:
iPhone 6s - Real device

- terminal log / 终端输出信息:

```
<-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

> try `app-inspector -u xxxx --verbose` for more log detail.
>> xctest-client.js:173:14 [master] pid:5044 please check project: /Users/<<xxx>>/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:5044 killing deviceLogProc pid: 5047
>> xctest-client.js:260:14 [master] pid:5044 killing runnerProc pid: 5050
>> xctest-client.js:266:14 [master] pid:5044 killing iproxyProc pid: 5049
>> xctest-client.js:183:14 [master] pid:5044 xctest client exit with code: 65, signal: null
>> xctest-client.js:145:16 [master] pid:5044 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:247:14 [master] pid:5044 Fail to start xctest: undefined
undefined

**Comment by irensoltan** [comment]
Facing the same issue. Did you find a solution?

**Comment by fengguochao** [comment]
https://macacajs.github.io/environment-setup

hello, pls refer to this doc. 
have you change the DEVELOPMENT_TEAM_ID ?

**Comment by ankitguptatest** [comment]
Issue is still present, ISE is getting on url
