### ISSUE TITLE
2.0.7 ECONNREFUSED Error

### ISSUE THREAD

**Issue by kahyalar** [macacajs/app-inspector#135]
I was using 2.0.5 then i decide to upgrade to 2.0.7

After update, i can't run inspector.

I did whole signing related things but result is still same.

app-inspector -u d61a6c03d188d445c12b3da07797f708fd7385da --verbose
>> server.js:16:12 [master] pid:2082 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'd61a6c03d188d445c12b3da07797f708fd7385da',
  ip: '192.168.60.175',
  host: 'Furkan-MacBook-Pro.local',
  loaded_time: '2017-08-29 13:31:40' }
>> app-inspector.js:43:12 [master] pid:2082 server start at: http://192.168.60.175:5678
>> xctest-client.js:55:14 [master] pid:2082 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:228:14 [master] pid:2082 xcode version: 8.3.3
>> XCTestWD version: 1.1.8
>> xctest-client.js:178:14 [master] pid:2082 2017-08-29 13:31:41.925 xcodebuild[2086:31862]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/C04CEA6E-DAEA-45B0-83F0-EBB73041DD9F/Session-XCTestWDUITests-2017-08-29_133141-0ycb7x.log

>> xctest-client.js:179:14 [master] pid:2082 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2082 2017-08-29 13:31:41.925 xcodebuild[2086:31810] [MT] IDETestOperationsObserverDebug: (8E1E492E-82C3-4F24-943F-B8A90D36E5EE) Beginning test session XCTestWDUITests-8E1E492E-82C3-4F24-943F-B8A90D36E5EE at 2017-08-29 13:31:41.925 with Xcode 8E3004b on target <DVTiOSDevice: 0x7fdf8a7f5a50> {
		deviceSerialNumber:         DX4SPW67FFG8
		identifier:                 d61a6c03d188d445c12b3da07797f708fd7385da
		deviceClass:                iPhone
		deviceName:                 Emre iPhone'u
		deviceIdentifier:           d61a6c03d188d445c12b3da07797f708fd7385da
		productVersion:             10.1.1
		buildVersion:               14B100
		deviceSoftwareVersion:      10.1.1 (14B100)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12249968640
		deviceAvailableCapacity:    8602718208
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fdf8a73a9e0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.1.1 (14B100))

>> xctest-client.js:179:14 [master] pid:2082 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2082 2017-08-29 13:31:42.110 xcodebuild[2086:31810] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/C04CEA6E-DAEA-45B0-83F0-EBB73041DD9F/Session-XCTestWDUITests-2017-08-29_133141-0ycb7x.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/C04CEA6E-DAEA-45B0-83F0-EBB73041DD9F/Session-XCTestWDUITests-2017-08-29_133141-0ycb7x.log}

>> xctest-client.js:179:14 [master] pid:2082 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2082
Testing failed:

>> xctest-client.js:179:14 [master] pid:2082 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2082 	XCTestWDUITests requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/kahyalar/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/C04CEA6E-DAEA-45B0-83F0-EBB73041DD9F/Session-XCTestWDUITests-2017-08-29_133141-0ycb7x.log
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:179:14 [master] pid:2082 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:263:14 [master] pid:2082 killing deviceLogProc pid: 2085
>> xctest-client.js:268:14 [master] pid:2082 killing runnerProc pid: 2086
>> xctest-client.js:189:14 [master] pid:2082 xctest client exit with code: 65, signal: null
>> xctest-client.js:150:16 [master] pid:2082 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:255:14 [master] pid:2082 Fail to start xctest: undefined
undefined
>> iOS device started: d61a6c03d188d445c12b3da07797f708fd7385da
>> inspector start at: http://192.168.60.175:5678
  <-- GET /
>> helper.js:94:16 [master] pid:2082 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1024:11)
      at exports._exceptionWithHostPort (util.js:1047:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)

**Comment by govinda-tiket** [comment]
I am getting the same issue, Have anyone solve this issue? Please update the solution.

**Comment by kahyalar** [comment]
In this error, I re-install application and each step follow the [guide](https://macacajs.github.io/app-inspector/) there is section for iOS Real Device at bottom of page. You have to check both general settings and build settings in .xcodeproj for signing. Also both targets. If you sign them all, it worked in my case. 👍
