### ISSUE TITLE
运行app-inspector -u xxx 后打开浏览器，但直接显示Internal Server Error

### ISSUE THREAD

**Issue by ancining** [macacajs/app-inspector#137]
- app inspector version / 版本号:
2.0.7

- os version / 系统:
10.12.6
Xcode-version:8.3.2

- device  information / 设备版本:

10.3.3
- terminal log / 终端输出信息:
![image](https://user-images.githubusercontent.com/26423615/30578938-ed6b173e-9d48-11e7-9dcc-604f19ad1dfd.png)

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.
>> port: 5678 was occupied, changed port: 5679
>> server.js:16:12 [master] pid:2106 server start with config:
 { port: 5679,
  verbose: true,
  udid: 'cd96a57c1c80c1d10460f0b22412adccdccdb01d',
  ip: '192.168.4.109 

',
  host: 'gyn.local',
  loaded_time: '2017-09-19 14:44:11' }
>> app-inspector.js:43:12 [master] pid:2106 server start at: http://192.168.4.109:5679 

>> xctest-client.js:55:14 [master] pid:2106 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:228:14 [master] pid:2106 xcode version: 8.3.2
>> XCTestWD version: 1.1.8
>> xctest-client.js:178:14 [master] pid:2106 2017-09-19 14:44:12.573 xcodebuild[2110:121532]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/gyn/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/8B52A0A7-5E47-4B3E-B2AC-0C8E6560D372/Session-XCTestWDUITests-2017-09-19_144412-1Z9Gfx.log

>> xctest-client.js:179:14 [master] pid:2106 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2106 2017-09-19 14:44:12.573 xcodebuild[2110:121517] [MT] IDETestOperationsObserverDebug: (CB6B98B5-A649-49F4-96F3-21192A27B276) Beginning test session XCTestWDUITests-CB6B98B5-A649-49F4-96F3-21192A27B276 at 2017-09-19 14:44:12.573 with Xcode 8E2002 on target <DVTiOSDevice: 0x7f8b0fc92cd0> {
		deviceSerialNumber:         DNRLG6QAFP6H
		identifier:                 cd96a57c1c80c1d10460f0b22412adccdccdb01d
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           cd96a57c1c80c1d10460f0b22412adccdccdb01d
		productVersion:             10.3.3
		buildVersion:               14G60
		deviceSoftwareVersion:      10.3.3 (14G60)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12418412544
		deviceAvailableCapacity:    7976783872
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f8b124dd6c0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.3 (14G60))

>> xctest-client.js:179:14 [master] pid:2106 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2106 2017-09-19 14:44:12.811 xcodebuild[2110:121517] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/gyn/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/8B52A0A7-5E47-4B3E-B2AC-0C8E6560D372/Session-XCTestWDUITests-2017-09-19_144412-1Z9Gfx.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/gyn/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/8B52A0A7-5E47-4B3E-B2AC-0C8E6560D372/Session-XCTestWDUITests-2017-09-19_144412-1Z9Gfx.log}

>> xctest-client.js:179:14 [master] pid:2106 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2106 
Testing failed:

>> xctest-client.js:179:14 [master] pid:2106 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2106 	XCTestWDUITests requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/gyn/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/8B52A0A7-5E47-4B3E-B2AC-0C8E6560D372/Session-XCTestWDUITests-2017-09-19_144412-1Z9Gfx.log
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:179:14 [master] pid:2106 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:263:14 [master] pid:2106 killing deviceLogProc pid: 2109
>> xctest-client.js:268:14 [master] pid:2106 killing runnerProc pid: 2110
>> xctest-client.js:189:14 [master] pid:2106 xctest client exit with code: 65, signal: null
>> xctest-client.js:150:16 [master] pid:2106 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:255:14 [master] pid:2106 Fail to start xctest: undefined
undefined
>> iOS device started: cd96a57c1c80c1d10460f0b22412adccdccdb01d
>> inspector start at: http://192.168.4.109:5679 

  <— GET /
>> helper.js:94:16 [master] pid:2106 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

  <— GET /favicon.ico
  —> GET /favicon.ico 404
有人可以从我提供的信息解答我的问题吗？感谢！

**Comment by timsheng** [comment]
@ancining  hi, 解决没？我也有一样的问题

**Comment by redpeer** [comment]
xiaomi5抱类似的错误，有的app可以，有些就行，>> port: 5678 was occupied, changed port: 5680
>> server.js:16:12 [master] pid:12396 server start with config:
 { port: 5680,
  verbose: true,
  udid: '64d34e83',
  ip: '192.168.31.179',
  host: 'air.local',
  loaded_time: '2018-01-20 17:20:43' }
>> app-inspector.js:43:12 [master] pid:12396 server start at: http://192.168.31.179:5680
>> uiautomator-client.js:61:14 [master] pid:12396 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:12396 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9001<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: 64d34e83
>> inspector start at: http://192.168.31.179:5680
  <-- GET /
>> proxy.js:55:14 [master] pid:12396 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9001/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:85:20 [master] pid:12396 Got response with status 200: {"status":0,"value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy rotation=\"0\" />","sessionId":null}
>> Dump Android XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/android.json

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/android.js:28:14)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/android.js:49:14)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by SamuelZhaoY** [comment]
please check project compilation for XCTestWD, refer issue here: https://github.com/macacajs/XCTestWD/issues/122 ,  for understanding how to build xctestwd please refer to https://github.com/macacajs/XCTestWD
