### ISSUE TITLE
app-inspector is not working in IOS 11

### ISSUE THREAD

**Issue by rdhandapani88** [macacajs/app-inspector#138]
Hi, Recently i have upgraded my iphone os version to IOS 11 and upgraded Xcode to 9. After that app-inspector stoped working, as XCTestWD is not installing in to the device. Tried downloading XCTestWD framework and install it thru XCODE, it says module swifter not found. Please help.

**Comment by pesedr** [comment]
I have this same issue. Is there any solution for this yet?

**Comment by deyvisonbm** [comment]
I too, i`m waiting for solution of this issue :/

**Comment by rdhandapani88** [comment]
Team,
I think Dev's are fixing this, so time being we can continue with Xcode 8.3.3, App inspector version 2.0.6, Carthage - V0.23.0, XCTestWD, V1.1.0. It works perfect in 10.3.3, so we can continue development in 10.3.3 and same can run agains 11.0

**Comment by xudafeng** [comment]
@rdhandapani88 please reinstall app-inspector

https://github.com/alibaba/macaca/issues/705

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/139

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/136
