### ISSUE TITLE
最新inspector2.0.8查看iOS系统计算器页面元素显示error

### ISSUE THREAD

**Issue by AlanFightting** [macacajs/app-inspector#144]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:2.0.8

- os version / 系统:10.12.6

- device  information / 设备版本:iOS10

始终获取不到页面元素属性

<img width="489" alt="wx20171009-144340 2x" src="https://user-images.githubusercontent.com/18625759/31327264-c2700e32-ad00-11e7-9f47-035c78278362.png">

**Comment by xudafeng** [comment]
更新即可
