### ISSUE TITLE
能否添加查看UI元素大小的功能？

### ISSUE THREAD

**Issue by wenmin92** [macacajs/app-inspector#146]
现在有个bounds属性，但是并不直观，也不明白bounds属性4个值的含义。

**Comment by fengguochao** [comment]
hello, bounds4个值的意义（left, top, width, height）
left是离屏幕左边的距离，top是离屏幕上边的距离
如果需要获取UI元素大小，请使用bounds的后面2个

**Comment by wenmin92** [comment]
@fengguochao 虽然有些迟, 但是很感谢你的解答. 谢谢.
