### ISSUE TITLE
With reference to issue #138.. App-inspector is installed successfully but device screen is not displayed in the browser

### ISSUE THREAD

**Issue by rdhandapani88** [macacajs/app-inspector#147]
With reference to the issue  #138, i can install XCTestWD in the iOS 11 device, with Xcode 9, but i could not see the device screen shot to identify the object in the browser. It keeps on telling waiting device start.... and it the terminal i am getting 200 response. Please check this, is there any cartage version we need to change ?

IOS version 11
MAC os - Seirra
XCODE - 9
Macaca version - 2.0.10
app-inspector version - 2.0.8
carthage - 0.26.0

**Comment by krupar92** [comment]
I also have same issue. What is the solution to this?

**Comment by krupar92** [comment]
@rdhandapani88: Can you please help me in letting me know the steps to resolve this issue.Thanks

**Comment by rdhandapani88** [comment]
@krupar92 : Still the issue is not resolved. I am facing the same issue.
