### ISSUE TITLE
iOS 10系统获取到的source节点tree有误，非当前应用节点tree

### ISSUE THREAD

**Issue by leemony** [macacajs/app-inspector#152]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

{  "sessionId" : "",  "status" : 0,  "value" : {    "label" : " ",    "name" : " ",    "value" : "",    "isEnabled" : true,    "isVisible" : true,    "rect" : {      "height" : 667,      "x" : 0,      "y" : 0,      "width" : 375    },    "type" : "Application",    "frame" : "{{0, 0}, {375, 667}}",    "rawIndentifier" : "",    "children" : [      {        "label" : "",        "name" : "",        "value" : "",        "children" : [          {            "label" : "",            "name" : "",            "value" : "",            "children" : [              {                "label" : "",                "name" : "",                "value" : "",                "children" : [                  {                    "label" : "",                    "name" : "",                    "value" : "",                    "children" : [                      {                        "label" : "",                        "name" : "",                        "value" : "",                        "children" : [                          {                            "label" : "",                            "name" : "",                            "value" : "",                            "children" : [                              {                                "label" : "",                                "name" : "",                                "value" : "",                                "children" : [                                  {                                    "label" : "",                                    "name" : "",                                    "value" : "",                                    "children" : [                                      {                                        "label" : "",                                        "name" : "",                                        "value" : "",                                        "children" : [                                          {                                            "label" : "",                                            "name" : "",                                            "value" : "",                                            "isVisible" : true,                                            "rect" : {                                              "height" : 667,                                              "x" : 0,                                              "y" : 0,                                              "width" : 375                                            },                                            "type" : "Other",                                            "frame" : "{{0, 0}, {375, 667}}",                                            "rawIndentifier" : "",                                            "isEnabled" : true                                          },                                          {                                            "label" : "",                                            "name" : "",                                            "value" : "",                                            "isVisible" : true,                                            "rect" : {                                              "height" : 667,                                              "x" : 0,                                              "y" : 0,                                              "width" : 375                                            },                                            "type" : "Other",                                            "frame" : "{{0, 0}, {375, 667}}",                                            "rawIndentifier" : "",                                            "isEnabled" : true                                          }                                        ],                                        "isVisible" : true,                                        "rect" : {                                          "height" : 667,                                          "x" : 0,                                          "y" : 0,                                          "width" : 375                                        },                                        "type" : "Other",                                        "frame" : "{{0, 0}, {375, 667}}",                                        "rawIndentifier" : "",                                        "isEnabled" : true                                      }                                    ],                                    "isVisible" : true,                                    "rect" : {                                      "height" : 667,                                      "x" : 0,                                      "y" : 0,                                      "width" : 375                                    },                                    "type" : "Other",                                    "frame" : "{{0, 0}, {375, 667}}",                                    "rawIndentifier" : "",                                    "isEnabled" : true                                  }                                ],                                "isVisible" : true,                                "rect" : {                                  "height" : 667,                                  "x" : 0,                                  "y" : 0,                                  "width" : 375                                },                                "type" : "Other",                                "frame" : "{{0, 0}, {375, 667}}",                                "rawIndentifier" : "",                                "isEnabled" : true                              },                              {                                "label" : "",                                "name" : "",                                "value" : "",                                "isVisible" : true,                                "rect" : {                                  "height" : 667,                                  "x" : 0,                                  "y" : 0,                                  "width" : 375                                },                                "type" : "Other",                                "frame" : "{{0, 0}, {375, 667}}",                                "rawIndentifier" : "",                                "isEnabled" : true                              }                            ],                            "isVisible" : true,                            "rect" : {                              "height" : 667,                              "x" : 0,                              "y" : 0,                              "width" : 375                            },                            "type" : "Other",                            "frame" : "{{0, 0}, {375, 667}}",                            "rawIndentifier" : "",                            "isEnabled" : true                          }                        ],                        "isVisible" : true,                        "rect" : {                          "height" : 667,                          "x" : 0,                          "y" : 0,                          "width" : 375                        },                        "type" : "Other",                        "frame" : "{{0, 0}, {375, 667}}",                        "rawIndentifier" : "",                        "isEnabled" : true                      }                    ],                    "isVisible" : true,                    "rect" : {                      "height" : 667,                      "x" : 0,                      "y" : 0,                      "width" : 375                    },                    "type" : "Other",                    "frame" : "{{0, 0}, {375, 667}}",                    "rawIndentifier" : "",                    "isEnabled" : true                  }                ],                "isVisible" : true,                "rect" : {                  "height" : 667,                  "x" : 0,                  "y" : 0,                  "width" : 375                },                "type" : "Other",                "frame" : "{{0, 0}, {375, 667}}",                "rawIndentifier" : "",                "isEnabled" : true              },              {                "label" : "",                "name" : "",                "value" : "",                "isVisible" : true,                "rect" : {                  "height" : 667,                  "x" : 0,                  "y" : 0,                  "width" : 375                },                "type" : "Other",                "frame" : "{{0, 0}, {375, 667}}",                "rawIndentifier" : "",                "isEnabled" : true              }            ],            "isVisible" : true,            "rect" : {              "height" : 667,              "x" : 0,              "y" : 0,              "width" : 375            },            "type" : "Other",            "frame" : "{{0, 0}, {375, 667}}",            "rawIndentifier" : "",            "isEnabled" : true          }        ],        "isVisible" : true,        "rect" : {          "height" : 667,          "x" : 0,          "y" : 0,          "width" : 375        },        "type" : "Window",        "frame" : "{{0, 0}, {375, 667}}",        "rawIndentifier" : "",        "isEnabled" : true      }    ]  }}

**Comment by xudafeng** [comment]
@fengguochao 排查下解析问题
