### ISSUE TITLE
Error occours while i execute "npm i app-inspector -g" on windows(GRADLE_HOME is setted).

### ISSUE THREAD

**Issue by smallsharp** [macacajs/app-inspector#155]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

C:\Users\cm>npm i app-inspector -g
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn
-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead

> devicelog@1.0.5 preinstall D:\nodejs\node_modules\app-inspector\node_modules\devicelog
> xcodebuild

'xcodebuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
D:\nodejs\app-inspector -> D:\nodejs\node_modules\app-inspector\bin\app-inspector
D:\nodejs\inspector -> D:\nodejs\node_modules\app-inspector\bin\app-inspector

> uiautomatorwd@1.0.45 install D:\nodejs\node_modules\app-inspector\node_modules\uiautomatorwd
> node ./scripts/build.js

please set GRADLE_HOME
TypeError: Cannot read property 'cwd' of undefined
    at Promise (D:\nodejs\node_modules\app-inspector\node_modules\gradle\lib\gradle.js:32:35)
    at gradleBuild (D:\nodejs\node_modules\app-inspector\node_modules\gradle\lib\gradle.js:31:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\app-inspector\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: devicelog@1.0.5 (node_modules\app-inspector\node_modules\devicelog):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: devicelog@1.0.5 preinstall: `xcodebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ app-inspector@2.0.10
added 392 packages in 44.074s

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by smallsharp** [comment]
windows7 系统

**Comment by smallsharp** [comment]
执行命令时报错了：
![image](https://user-images.githubusercontent.com/17560276/33161758-98d6c1b4-d060-11e7-914a-c0992718e02c.png)

**Comment by smallsharp** [comment]
本地路径下没有找到后面的文件夹：
![image](https://user-images.githubusercontent.com/17560276/33161764-a44ad620-d060-11e7-8ce9-e3dc4c76c972.png)

**Comment by xudafeng** [comment]
@smallsharp sdk没装好，apk文件没build成功
