### ISSUE TITLE
weex的页面元素的id无法获取到

### ISSUE THREAD

**Issue by vivian2011** [macacajs/app-inspector#156]
现在只能通过文本和xpath来定位，这两个内容经常变化，这样编写脚本效率极低根本不适合做自动化，有办法能解决吗？

**Comment by xudafeng** [comment]
@misakuo

**Comment by misakuo** [comment]
weex添加了test-id属性在前端来替代id属性做元素标识，同时在native端维护了一份test-id到view-id的映射表，如此便可以将前端的id和真实的元素关联起来

**Comment by yuliu312832473** [comment]
这么麻烦啊 ，你们飞猪app是怎么测的
