### ISSUE TITLE
app-inspector can not working on real iphone6s(os11.2)

### ISSUE THREAD

**Issue by LYJHON** [macacajs/app-inspector#162]
Environment check:

 macaca-doctor version: 2.0.4

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v9.3.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0

  Android checklist:

  JAVA version is `1.8.0_45`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/xxx/Desktop/javaTest/adt/sdk`
  Platforms is set to `/Users/xxx/Desktop/javaTest/adt/sdk/platforms/android-27`
  ADB tool is set to `/Users/xxx/Desktop/javaTest/adt/sdk/platform-tools/adb`
  gradle is installed, version: 4.4

  Installed driver list:

  ios: 2.0.30

- app inspector version / 版本号:

2.0.10
- os version / 系统:

10.13.1
- device  information / 设备版本:

iphone6s 
os:11.2
- terminal log / 终端输出信息:

server.js:16:12 [master] pid:3245 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'e8e1fd382334901052991fc08020acb341XXXXXX',
  ip: '192.168.0.103',
  host: 'liuyongdeMacBook-Pro-2.local',
  loaded_time: '2017-12-31 18:25:06' }
>> app-inspector.js:43:12 [master] pid:3245 server start at: http://192.168.0.103:5678
>> xctest-client.js:56:14 [master] pid:3245 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:242:14 [master] pid:3245 xcode version: 9.2
>> XCTestWD version: 1.3.12
>> xctest-client.js:190:18 [master] pid:3245 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:3245 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:3245 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:3245 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:3245 killing deviceLogProc pid: 3255
>> xctest-client.js:281:14 [master] pid:3245 killing runnerProc pid: 3248
>> xctest-client.js:201:16 [master] pid:3245 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:3245 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:3245 Fail to start xctest: undefined
undefined
>> iOS device started: e8e1fd382334901052991fc08020acb3417e8e31
>> inspector start at: http://192.168.0.103:5678
  <-- GET /
>> helper.js:94:16 [master] pid:3245 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:999:13)
      at _exceptionWithHostPort (util.js:1020:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by rdhandapani88** [comment]
I too facing the same problem. App inspector is not working fine in the latest version of Xcode 9.2 and IOS version. Any solution for this ?

**Comment by krupar92** [comment]
Any fix found?

**Comment by narendra-chandratre** [comment]
Yes, I am also observing same issue :( 

**Environment :** 
1. Xcode version : 9.2 [Latest]
2. iOS real device : iPhone 6 Plus
3. iPhone Version : 10.3.3[14G60]
4. Macbook iOS Version : 10.12.6

**Below error observed :**
>> XCTestWD version: 1.3.25
undefined
>> iOS device started: <device-id-of-your-device>
>> inspector start at: http://10.236.11.5:5678
  <-- GET /

  **Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:1003:13)
      at _exceptionWithHostPort (util.js:1024:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)**

**Comment by narendra-chandratre** [comment]
Finally, It started working for me! 

1. Clean & Build your 3 projects [Your actual targeted automation project + WebDriverAgent + XCTest]
2. Verify Team ID is correct and Profiles are valid
3. Crosscheck your Macaca installation on your machine

**Comment by SamuelZhaoY** [comment]
@narendra-chandratre  thanks for the answer,  @rdhandapani88 @krupar92 can also check this issue:  https://github.com/macacajs/app-inspector/issues/184.  it is caused by the testing target's compilation issue
