### ISSUE TITLE
Error: Command failed

### ISSUE THREAD

**Issue by gaye746560359** [macacajs/app-inspector#166]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:2.0.10

- os version / 系统:win10 x64

- device  information / 设备版本:android 7.1

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

![image](https://user-images.githubusercontent.com/3060035/35089506-19b77138-fc72-11e7-82c4-d08915f41c89.png)

**Comment by zeeshanu** [comment]
Just do the following and you will be up and running

```bash
which app-inspector     # /Users/zeeshan/.nvm/versions/node/v9.3.0/bin/app-inspector
cd /Users/zeeshan/.nvm/versions/node/v9.3.0/bin/app-inspector
npm remove uiautomatorwd
npm install uiautomatorwd@1.0.45 
```

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/179
upgrade your app-inspector
