### ISSUE TITLE
Webview content is not shown (iOS 11.2 , Xcode 9.2 )

### ISSUE THREAD

**Issue by DanielPradoPino** [macacajs/app-inspector#169]
- app inspector version / 版本号: 20.0.10
- os version / 系统: 11.2
- device  information / 设备版本: iOS Simulator iPhone 7 iOS 11.2

Inspector is showing Webview element but with barely no information inside.

`<XCUIElementTypeOther>
    <XCUIElementTypeWebView>
        <XCUIElementTypeOther></XCUIElementTypeOther>
    </XCUIElementTypeWebView>
</XCUIElementTypeOther>`

If use the same version, same app in Xcode 8.3 everything is showing correctly.

Thanks in advance.

**Comment by xudafeng** [comment]
@DanielPradoPino

try to upgrade `ios_webkit_debug_proxy` to the latest
