### ISSUE TITLE
can't run app-inspector on Galaxy S5 real device

### ISSUE THREAD

**Issue by gaboF** [macacajs/app-inspector#173]
Could you please help me with running the app inspector ? After upgrade to 2.0.10 it stopped to work correctly.
When I run app-inspector -u command it fails with error (see below)

Environment check:

- app inspector version / 版本号:  2.0.10 

- os version / 系统: macOS 10.12.6

- device  information / 设备版本: Galaxy S5 / Android 6.0.1 / Real device

- doctor log:
gabo:~ gabo$ appium-doctor --android
info AppiumDoctor Appium Doctor v.1.2.5
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/gabo/Development/android-sdk-macosx
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/gabo/Development/android-sdk-macosx/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/gabo/Development/android-sdk-macosx/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/gabo/Development/android-sdk-macosx/tools/emulator
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!

when I try try `app-inspector -u xxxx --verbose` for more log detail I got:

gabo:~ gabo$ app-inspector -u 9e6396b4 --verbose
>> port: 5678 was occupied, changed port: 5680
>> server.js:16:12 [master] pid:17778 server start with config:
 { port: 5680,
  verbose: true,
  udid: '9e6396b4',
  ip: '10.16.32.33',
  host: 'gabo',
  loaded_time: '2018-02-12 15:15:21' }
>> app-inspector.js:43:12 [master] pid:17778 server start at: http://10.16.32.33:5680
{ [Error: Command failed: /bin/sh -c /Users/gabo/Development/android-sdk-macosx/platform-tools/adb -s 9e6396b4 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /Users/gabo/Development/android-sdk-macosx/platform-tools/adb -s 9e6396b4 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/179
upgrade your app-inspector
