### ISSUE TITLE
Not able to inspect element in macaca inspector

### ISSUE THREAD

**Issue by krupar92** [macacajs/app-inspector#174]
Hi All,

I am trying to run an app file on macaca browser for inspecting mobile element. I am getting following error. The bowser starts up saying waiting for device.Can you please help.

I am using iphone 6 simulator , not a real device.

xctest-client.js:201:16 [master] pid:82949 xctest client exit with code: 65, signal: null
xctest-client.js:115:18 [master] pid:82949 simulator log process exit with code: null, signal: SIGKILL . 

These are versions of software installed in my MAC
macaca-doctor version: 2.0.5

Node.js checklist:

node env: /usr/local/bin/node
node version: v8.9.2

iOS checklist:

Xcode Command Line Tools is ready, version: 2349.
xcodebuild version: 9.2
iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
carthage is installed, version: 0.27.0

**Comment by krupar92** [comment]
Can anyone please help in this?

**Comment by wispy316** [comment]
Installed driver list:
  ios: 2.0.30

is macaca-ios driver installed?  parse your full macaca doctor log.

**Comment by krupar92** [comment]
yes it is installed.Please check

  macaca-doctor version: 2.0.5


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.9.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/krupa/Android`
  Platforms is set to `/Users/krupa/Android/platforms/android-20`
  ADB tool is set to `/Users/krupa/Android/platform-tools/adb`
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.30

**Comment by krupar92** [comment]
@wispy316 :Still same issue persists.Please help

**Comment by rdhandapani88** [comment]
@krupar92  Macaca App ispector is working fine in Real devices. I tried with real devices. Please make sure that you have installed the latest version of app-inspector , and even i tried with latest ios version 11.2.6. it is working fine. It is not working only for IPAD's.

**Comment by xudafeng** [comment]
@krupar92

please check your host environment.

```
$ npx macaca-cli doctor
```

**Comment by krupar92** [comment]
Still not working for simulator.

**Comment by lgzwo** [comment]
同样遇到这个问题，macaca测试运行正常，app-inspector无法启动，用的模拟器。

**Comment by SamuelZhaoY** [comment]
https://github.com/macacajs/app-inspector/issues/184 please check about xcode compilation issue

**Comment by codingfishman** [comment]
@SamuelZhaoY 
  I have the same issue, and I compiled the "XCTestWDUITests" in Xcode successfully, no errors.
  The `macaca docotor` reports the env is fine, the `app-insepector` start without errors either, but the page keeps 'waiting device start...', and no simulator is launched, I have no clues now...


```
 Node.js checklist:

  node env: /Users/wangweijie/.nvm/versions/node/v9.8.0/bin/node
  node version: v9.8.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.29.0


Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is not set
  ANDROID_HOME is set to `/usr/local/share/android-sdk`
  Android SDK Platforms directory is not exist, please install the whole thing
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.30
```
