### ISSUE TITLE
Not able to inspect element

### ISSUE THREAD

**Issue by saglave** [macacajs/app-inspector#176]
Environment check:

``` bash
npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/179

upgrade your app-inspector
