### ISSUE TITLE
app-inspector can't use in HUAWEI 5X

### ISSUE THREAD

**Issue by zhangpeng23796** [macacajs/app-inspector#182]
macaca-doctor version: 2.0.9

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v9.3.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhj/android-sdk-macosx`
  Platforms is set to `/Users/zhj/android-sdk-macosx/platforms/android-27`
  ADB tool is set to `/Users/zhj/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 4.4

  Installed driver list:

  android: 2.0.46
  chrome: 1.0.7

app-inspector -u T3Q4C15A31016180 —verbose
app-inspector can't use in HUAWEI 5X, the error is:
>> request.js:11:12 [master] pid:17002 get remote update info failed.
>> server.js:16:12 [master] pid:17002 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'T3Q4C15A31016180',
  ip: '10.167.44.18',
  host: 'bogon',
  loaded_time: '2018-03-15 15:11:08' }
>> app-inspector.js:45:12 [master] pid:17002 server start at: http://10.167.44.18:5678
>> uiautomator-client.js:61:14 [master] pid:17002 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:17002 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9002<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: T3Q4C15A31016180
>> inspector start at: http://10.167.44.18:5678
  <-- GET /
>> proxy.js:55:14 [master] pid:17002 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9002/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:63:22 [master] pid:17002 UIAutomatorWD client proxy error with: Error: socket hang up
>> proxy.js:63:22 [master] pid:17002 UIAutomatorWD client proxy error with: Error: socket hang up

![image](https://user-images.githubusercontent.com/26616673/37448379-15b5530a-2861-11e8-852f-d21c1c64c108.png)

**Comment by fengguochao** [comment]
hi, zhangpeng,

can you help paste this file /usr/local/lib/node_modules/app-inspector/.temp/android.json ?
