### ISSUE TITLE
app-inspector -u 设备号 ，报安卓异常

### ISSUE THREAD

**Issue by liyinchigithub** [macacajs/app-inspector#183]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```
  macaca-doctor version: 2.0.10

  Node.js checklist:

  node env: C:\lyc\nodejs\node.exe
  node version: v8.9.3

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\lyc\Java`
  ANDROID_HOME is set to `C:\lyc\android-sdk-windows_SDK24API21`
  Platforms is set to `C:\lyc\android-sdk-windows_SDK24API21\platforms\android-27`
  ADB tool is set to `C:\lyc\android-sdk-windows_SDK24API21\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\lyc\gradle-4.1-bin\gradle-4.1`

  Installed driver list:

  android: 2.0.47

---

- app inspector version / 版本号:
app-inspector@2.0.15

- os version / 系统:
window 10 64位

- device  information / 设备版本:
Android 7.0

- terminal log / 终端输出信息:
>> android.util.AndroidException: INSTRUMENTATION_FAILED: com.macaca.android.testing.test/android.support.test.runner.AndroidJUnitRunner
        at com.android.commands.am.Am.runInstrument(Am.java:890)
        at com.android.commands.am.Am.onRun(Am.java:400)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:121)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)

  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
android 驱动安装失败，重装 android sdk
