### ISSUE TITLE
Error while running XCTestWD - Use of undeclared type 'XCTestWDServer' , because of that app-inspector is not working

### ISSUE THREAD

**Issue by rdhandapani88** [macacajs/app-inspector#184]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```
Done
---

- app inspector version / 版本号:
2.0.15 

- os version / 系统:
Mac os sierra 10.12.6

- device  information / 设备版本:
IPad Mini 11.2.6

- terminal log / 终端输出信息:

it-reference-dependencies-path /Users/rajendh/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Intermediates.noindex/XCTestWD.build/Debug-iphoneos/XCTestWDUITests.build/Objects-normal/arm64/XCTestWDRunner.swiftdeps -o /Users/rajendh/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Intermediates.noindex/XCTestWD.build/Debug-iphoneos/XCTestWDUITests.build/Objects-normal/arm64/XCTestWDRunner.o -index-store-path /Users/rajendh/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Index/DataStore -index-system-modules
/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/XCTestWDRunner.swift:14:17: error: use of undeclared type 'XCTestWDServer'
    var server: XCTestWDServer?
                ^~~~~~~~~~~~~~
/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/XCTestWDRunner.swift:30:23: error: use of unresolved identifier 'XCTestWDServer'
        self.server = XCTestWDServer()
                      ^~~~~~~~~~~~~~
XCTest.XCTestObserver:5:12: note: did you mean 'XCTestObserver'?
open class XCTestObserver : NSObject {
           ^

2018-04-05 13:25:55.474 xcodebuild[68086:2955279] Error Domain=IDETestOperationsObserverErrorDomain Code=14 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/nj/kvb21x_x44d31tlfsghypv44p6bdc8/T/com.apple.dt.XCTest/IDETestRunSession-CCB2A5B7-D7FE-460E-99C6-22D982B472B7/XCTestWDUITests-E31330C0-E6CA-49F0-8675-5CAF25F920DA/Session-XCTestWDUITests-2018-04-05_132540-t1JVDg.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/nj/kvb21x_x44d31tlfsghypv44p6bdc8/T/com.apple.dt.XCTest/IDETestRunSession-CCB2A5B7-D7FE-460E-99C6-22D982B472B7/XCTestWDUITests-E31330C0-E6CA-49F0-8675-5CAF25F920DA/Session-XCTestWDUITests-2018-04-05_132540-t1JVDg.log}

Testing failed:
	Use of undeclared type 'XCTestWDServer'
	Use of unresolved identifier 'XCTestWDServer'
** TEST FAILED **

The following build commands failed:
	CompileSwift normal arm64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/XCTestWDRunner.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

> try `app-inspector -u xxxx --verbose` for more log detail.

I have installed the latest version of App-inspector and installed all prerequisites, but while running the xctestwdTest , the project displays the above error in Xcode, also in terminal. Kindly help to resolve this. I have installed the cartage dependencies also using "carthage bootstrap --platform ios" in the xctestwd folder. Only this is Blocking kindly help.
![screen shot 2018-04-05 at 1 26 21 pm](https://user-images.githubusercontent.com/32144304/38381708-a18ed0b6-38d5-11e8-86a8-5eb6c4d5bfab.png)

**Comment by SamuelZhaoY** [comment]
please update to xctestwd to 1.3.27,  there is a known compilation issue occurring for xcode 9.3 at early versions. if your problem still exists, please enter the directory where xctestwd module is installed and check the compilation error for target 'XCTestWDUITests'
```
cd $(npm root -g)//app-inspector/node_modules/xctestwd
```
