### ISSUE TITLE
一直报 xctest client exit with code: 65, signal: null  求解决 (签名已改）

### ISSUE THREAD

**Issue by muxiaFrank** [macacajs/app-inspector#187]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号: 2.0.15

- XCTestWD version / 版本号: 1.3.27

- os version / 系统:10.12.6 

- device  information / 设备版本: 模拟器

- terminal log / 终端输出信息:
>> xctest-client.js:195:18 [master] pid:53046 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> Read simulator log at: /var/folders/_z/s56lk0nn2n17f30hfbmmk5100000gn/T/com.apple.dt.XCTest/IDETestRunSession-2D563DAD-6120-42A0-90EC-B0CEECD6971B/XCTestWDUITests-4BC27D34-A649-4808-96DD-AD7A77C98A07/StandardOutputAndStandardError.txt
>> xctest-client.js:195:18 [master] pid:53046 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> Read simulator log at: /var/folders/_z/s56lk0nn2n17f30hfbmmk5100000gn/T/com.apple.dt.XCTest/IDETestRunSession-2D563DAD-6120-42A0-90EC-B0CEECD6971B/XCTestWDUITests-4BC27D34-A649-4808-96DD-AD7A77C98A07/StandardOutputAndStandardError.txt
>> xctest-client.js:195:18 [master] pid:53046 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:53046 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:53046 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:281:14 [master] pid:53046 killing deviceLogProc pid: 53067
>> xctest-client.js:286:14 [master] pid:53046 killing runnerProc pid: 53049
>> xctest-client.js:206:16 [master] pid:53046 xctest client exit with code: 65, signal: null
>> xctest-client.js:119:18 [master] pid:53046 simulator log process exit with code: null, signal: SIGKILL
>> Read simulator log at: /var/folders/_z/s56lk0nn2n17f30hfbmmk5100000gn/T/com.apple.dt.XCTest/IDETestRunSession-2D563DAD-6120-42A0-90EC-B0CEECD6971B/XCTestWDUITests-4BC27D34-A649-4808-96DD-AD7A77C98A07/StandardOutputAndStandardError.txt

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by SamuelZhaoY** [comment]
please use verbose mode to provide detailed information, you can also refer to this issue on how to debug on iOS driver's compilation issue https://github.com/macacajs/app-inspector/issues/184
