### ISSUE TITLE
xcode 9.3  Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by linyan0321** [macacajs/app-inspector#189]
- app inspector version / 版本号:
 2.0.15

- os version / 系统:
10.13.4 (17E199)

- device  information / 设备版本:
iphone真机

- terminal log / 终端输出信息:
XCTestWDUITests 在xcode9.3   iOS系统是10.13.4  编译失败

![image](https://user-images.githubusercontent.com/28682425/39663385-2e03c97a-50a5-11e8-8f79-b3aaa0da0b05.png)

**Comment by SamuelZhaoY** [comment]
refer to this issue, https://github.com/macacajs/app-inspector/issues/184 , seems you have just updated xcode 9.2 to 9.3, if in this case, reinstall app-inspector

**Comment by linyan0321** [comment]
@SamuelZhaoY  reinstall app-inspector  the same error

help me

**Comment by SamuelZhaoY** [comment]
recompile xctestwd, the xctestwd binary in your cache is build with swift 4.0.3

**Comment by linyan0321** [comment]
@SamuelZhaoY thank you very much
1、uninstall app-inspector
2、clear xcode all cache
3、restart ios sys and install app-inspector
4、compile 

OK OK OK

**Comment by YGQ8988** [comment]
thinks , reinstall app-inspector, then build succeeded,
