### ISSUE TITLE
app-inspector  Android虚拟机界面无法加载

### ISSUE THREAD

**Issue by fangqie** [macacajs/app-inspector#190]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:2.0.15

- os version / 系统:win10

- device  information / 设备版本:GalaxyNexus_android7  api24

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.
>> server.js:16:12 [master] pid:13976 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'emulator-5554',
  ip: '10.0.100.144',
  host: 'SZXHQDEVLTP001',
  loaded_time: '2018-05-07 12:00:54' }
>> app-inspector.js:45:12 [master] pid:13976 server start at: http://10.0.100.144:5678
>> uiautomator-client.js:32:14 [master] pid:13976 Package com.macaca.android.testing already exists. No need reinstall.
>> uiautomator-client.js:51:14 [master] pid:13976 Package com.macaca.android.testing.test already exists. No need reinstall.
>> uiautomator-client.js:92:14 [master] pid:13976 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
>> uiautomator-client.js:92:14 [master] pid:13976
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:92:14 [master] pid:13976 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9006<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: emulator-5554
>> inspector start at: http://10.0.100.144:5678
  <-- GET /
>> proxy.js:55:14 [master] pid:13976 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9006/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:85:20 [master] pid:13976 Got response with status 200: {"status":0,"value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy rotation=\"0\">\r\n  <node index=\"0\" text=\"\" resource-id=\"\" class=\"android.widget.LinearLayout\" p...
>> Dump Android XML success, save to C:\Users\yanfang.chen\AppData\Roaming\npm\node_modules\app-inspector\.temp\android.json
  --> GET / 200

**Comment by LLLucian** [comment]
同样虚拟机界面加载不了，解决了吗？

**Comment by xudafeng** [comment]
请安装最新版
