### ISSUE TITLE
app-debug.apk not found, please resolve and reinstall android driver

### ISSUE THREAD

**Issue by Mr-G-1992** [macacajs/app-inspector#193]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

```

  macaca-doctor version: 2.0.14


  Node.js checklist:

  node env: D:\Program Files\nodejs\node.exe
  node version: v8.11.1

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_111`
  ANDROID_HOME is set to `E:\sdk`
  Platforms is set to `E:\sdk\platforms\android-26`
  ADB tool is set to `E:\sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\Program Files\gradle-4.6`

  Installed driver list:

  android: 2.0.47
```
---

- app inspector version / 版本号: 2.0.15

- os version / 系统: win7

- device  information / 设备版本:  SM-G9209

- terminal log / 终端输出信息: 
 uiautomator-client.js:42:14 [master] pid:12516 D:\ProgramFiles\nodejs\node_global\node_modules\app-inspector\node_modules\_uiautomatorwd@1.0.53@uiautomatorwd\app\build\outputs\apk\app-debug.apk not found, please resolve and reinstall android driver

> try `app-inspector -u xxxx --verbose` for more log detail.

```
>> uiautomator-client.js:42:14 [master] pid:15124 D:\Program Files\nodejs\node_g
lobal\node_modules\app-inspector\node_modules\_uiautomatorwd@1.0.53@uiautomatorw
d\app\build\outputs\apk\app-debug.apk not found, please resolve and reinstall an
droid driver
Error: >> uiautomator-client.js:42:14 [master] pid:15124 D:\Program Files\nodejs
\node_global\node_modules\app-inspector\node_modules\_uiautomatorwd@1.0.53@uiaut
omatorwd\app\build\outputs\apk\app-debug.apk not found, please resolve and reins
tall android driver
    at Logger.error (D:\Program Files\nodejs\node_global\node_modules\app-inspec
tor\node_modules\_xlogger@1.0.6@xlogger\lib\xlogger.js:169:9)
    at UIAutomator.init (D:\Program Files\nodejs\node_global\node_modules\app-in
spector\node_modules\_uiautomatorwd@1.0.53@uiautomatorwd\lib\uiautomator-client.
js:42:14)
    at UIAutomator.init.throw (<anonymous>)
    at onRejected (D:\Program Files\nodejs\node_global\node_modules\app-inspecto
r\node_modules\_co@4.6.0@co\index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

> try `cnpm install app-inspector -g` for more log detail.
```
Downloading app-inspector to D:\Program Files\nodejs\node_global\node_modules\ap
p-inspector_tmp
Copying D:\Program Files\nodejs\node_global\node_modules\app-inspector_tmp\_app-
inspector@2.0.15@app-inspector to D:\Program Files\nodejs\node_global\node_modul
es\app-inspector
Installing app-inspector's dependencies to D:\Program Files\nodejs\node_global\n
ode_modules\app-inspector/node_modules
[1/19] co@^4.6.0 installed at node_modules\_co@4.6.0@co
[2/19] commander@^2.9.0 installed at node_modules\_commander@2.15.1@commander
[3/19] request@^2.74.0 existed at node_modules\_request@2.87.0@request
[4/19] co-request@^1.0.0 installed at node_modules\_co-request@1.0.0@co-request
[5/19] xlogger@^1.0.4 existed at node_modules\_xlogger@1.0.6@xlogger
[6/19] xutil@^1.0.2 existed at node_modules\_xutil@1.0.11@xutil
[7/19] detect-port@^1.0.0 installed at node_modules\_detect-port@1.2.3@detect-po
rt
[8/19] koa-router@^5.4.0 installed at node_modules\_koa-router@5.4.2@koa-router
[9/19] xml2map@^1.0.2 installed at node_modules\_xml2map@1.0.2@xml2map
[10/19] koa@^1.2.1 installed at node_modules\_koa@1.6.0@koa
fsevents@1.2.4 download from binary mirror: {"module_name":"fse","module_path":"
./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{
version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}
.tar.gz","host":"https://cdn.npm.taobao.org/dist/fsevents"}
platform unsupported nunjucks@2.5.2 › chokidar@1.7.0 › fsevents@^1.0.0 Package r
equire os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compati
ble with your platform(win32)
[11/19] macaca-adb@* installed at node_modules\_macaca-adb@1.0.34@macaca-adb
[12/19] koa-static@^2.0.0 installed at node_modules\_koa-static@2.1.0@koa-static

[13/19] koa-bodyparser@^2.2.0 installed at node_modules\_koa-bodyparser@2.5.0@ko
a-bodyparser
[14/19] ios-simulator@* installed at node_modules\_ios-simulator@1.0.15@ios-simu
lator
[15/19] react-syntax-highlighter@^7.0.2 installed at node_modules\_react-syntax-
highlighter@7.0.4@react-syntax-highlighter
[16/19] nunjucks@^2.4.2 installed at node_modules\_nunjucks@2.5.2@nunjucks
[17/19] npm-update@^1.0.2 installed at node_modules\_npm-update@1.0.7@npm-update

[18/19] uiautomatorwd@* installed at node_modules\_uiautomatorwd@1.0.53@uiautoma
torwd
[19/19] xctestwd@* installed at node_modules\_xctestwd@1.3.30@xctestwd
execute post install 3 scripts...
[1/3] scripts.install xctestwd@1.3.30 › ios-utils@1.0.5 › devicelog@^1.0.2 run "
node ./scripts/build.js"
[1/3] scripts.install xctestwd@1.3.30 › ios-utils@1.0.5 › devicelog@^1.0.2 finis
hed in 810ms
[2/3] scripts.install uiautomatorwd@* run "node ./scripts/build.js"
(node:8892) UnhandledPromiseRejectionWarning: ,NDK is missing a "platforms" dire
ctory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is
 currently set to E:\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.
properties to remove this warning.


A larger heap for the Gradle daemon is recommended for running jack.

It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at le
ast 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environ
ment.html


A larger heap for the Gradle daemon is recommended for running jack.

It currently has 1024 MB.
For faster builds, increase the maximum heap size for the Gradle daemon to at le
ast 1536 MB.
To do this set org.gradle.jvmargs=-Xmx1536M in the project gradle.properties.
For more information see https://docs.gradle.org/current/userguide/build_environ
ment.html

Checking the license for package Android Support Repository in E:\sdk\licenses
Warning: License for package Android Support Repository not accepted.

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:comman
d_line_warnings
,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android Support Repository].
  Before building your project, you need to accept the license agreements and co
mplete the installation of the missing components using the Android Studio SDK M
anager.
  Alternatively, to learn how to transfer the license agreements from one workst
ation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

(node:8892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 2)
(node:8892) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
[2/3] scripts.install uiautomatorwd@* finished in 8s
[3/3] scripts.install xctestwd@* run "node ./scripts/install.js"
[3/3] scripts.install xctestwd@* finished in 1s
peerDependencies WARNING react-syntax-highlighter@^7.0.2 requires a peer of reac
t@>= 0.14.0 but none was installed
deprecate xctestwd@1.3.30 › request@2.69.0 › tough-cookie@~2.2.0 ReDoS vulnerabi
lity parsing Set-Cookie https://nodesecurity.io/advisories/130
deprecate xctestwd@1.3.30 › request@2.69.0 › node-uuid@~1.4.7 Use uuid module in
stead
deprecate xctestwd@1.3.30 › xcode@0.8.9 › node-uuid@1.4.7 Use uuid module instea
d
Recently updated (since 2018-05-16): 7 packages (detail see file D:\Program File
s\nodejs\node_global\node_modules\app-inspector\node_modules\.recently_updates.t
xt)
  2018-05-21
    → npm-update@1.0.7 › co-request@0.2.1 › request@*(2.87.0) (15:35:02)
    → xctestwd@1.3.30 › request@2.69.0 › form-data@1.0.1 › async@^2.0.1(2.6.1)
(12:34:29)
  2018-05-18
    → macaca-adb@*(1.0.34) (14:29:33)
    → xctestwd@1.3.30 › macaca-doctor@2.0.14 › java-util@0.1.1 › java-home@~1.0
.1(1.0.7) (08:49:47)
  2018-05-17
    → xctestwd@1.3.30 › request@2.69.0 › stringstream@~0.0.4(0.0.6) (18:22:37)
  2018-05-16
    → detect-port@^1.0.0(1.2.3) (21:23:33)
    → xctestwd@*(1.3.30) (17:58:12)
All packages installed (315 packages installed from npm registry, used 28s, spee
d 1.66MB/s, json 289(1.8MB), tarball 45.31MB)
[app-inspector@2.0.15] link D:\Program Files\nodejs\node_global\inspector@ -> D:
\Program Files\nodejs\node_global\node_modules\app-inspector\bin\app-inspector
[app-inspector@2.0.15] link D:\Program Files\nodejs\node_global\app-inspector@ -
> D:\Program Files\nodejs\node_global\node_modules\app-inspector\bin\app-inspect
or
```

**Comment by aisir** [comment]
>> uiautomator-client.js:42:14 [master] pid:10891 /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk not found, please resolve and reinstall android driver
Error: >> uiautomator-client.js:42:14 [master] pid:10891 /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk not found, please resolve and reinstall android driver
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169:9)
    at UIAutomator.init (/usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/lib/uiautomator-client.js:42:14)
    at UIAutomator.init.throw (<anonymous>)
    at onRejected (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)

executed app-inspector -u 0815f83d8da72404 in ubuntu shell,received same error ,yesterday

**Comment by schwarcu** [comment]
I have the same issue. Impossible to use inspector.

**Comment by prasanna532** [comment]
uiautomator-client.js:42:14 [master] pid:4320 C:\Users\XXX\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk not found, please resolve and reinstall android driver
Error: >> uiautomator-client.js:42:14 [master] pid:4320 C:\Users\XXX\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk not found, please resolve and reinstall android driver
    at Logger.error (C:\Users\XXX\AppData\Roaming\npm\node_modules\app-inspector\node_modules\xlogger\lib\xlogger.js:169:9)
    at UIAutomator.init (C:\Users\XXX\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\lib\uiautomator-client.js:42:14)
    at UIAutomator.init.throw (<anonymous>)
    at onRejected (C:\Users\XXX\AppData\Roaming\npm\node_modules\app-inspector\node_modules\co\index.js:81:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by bitlin** [comment]
我的可以解决：
1. > cd <Your directory>/node_modules/app-inspector/node_modules/uiautomatorwd
2. > ./gradlew assembleDebug assembleDebugAndroidTest

如果执行以上命令过程中遇到Android SDK未同意协议的问题，
执行 $ANDROID_HOME/tools/bin/sdkmanager --licenses  
其中$ANDROID_HOME提前已设置环境变量

**Comment by clark-ewerton** [comment]
Just adding a quick comment here...

This error: **AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\debug\app-debug.apk not found** 

means that is coming from that module "uiautomatorwd".

And that module only runs in JDK 8 nowadays because is deprecated. So if you wanna run macaca inspector these days, please make sure to switch java version to JDK 8 only to run the inspector ok?

I'm using Windows, so I created a .bat file with the following content to sort the issue out:

`@echo off
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_202
set PATH=%JAVA_HOME%\bin;%PATH%
cd C:\Users\clark\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd
gradlew.bat assembleDebug `

If, by any chance, happens to throw this error:

> Task :app:packageDebug FAILED

**FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key AndroidDebugKey from store "C:\Users\clark\.android\debug.keystore": Invalid keystore format**

You can run the following command to tackle it:

` del C:\Users\clark\.android\debug.keystore
keytool -genkeypair -alias androiddebugkey -keypass android -keystore C:\Users\clark\.android\debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 10000 -keyalg RSA -keysize 2048 -storetype JKS
keytool -list -v -keystore C:\Users\clark\.android\debug.keystore -storepass android `

And lastly it's gonna throw this error probably right away:

**>> uiautomator-client.js:61:14 [master] pid:7712 C:\Users\clark\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\
androidTest\debug\app-debug-androidTest.apk not found, please resolve and reinstall android driver**

Resolve it by running the script:
`
@echo off
set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_202
set PATH=%JAVA_HOME%\bin;%PATH%
cd C:\Users\clark\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd
gradlew.bat assembleAndroidTest`
