### ISSUE TITLE
Command failed：push app-debug.apk to android temp file

### ISSUE THREAD

**Issue by chenjiacun35** [macacajs/app-inspector#194]
Environment check:

```bash
```
Node.js checklist:

node env: D:\Program Files\nodejs8.9\node.exe
node version: v8.9.3

Android checklist:

JAVA version is `1.8.0_152`
JAVA_HOME is set to `D:\Program Files\Java\jdk1.8.0_52`
ANDROID_HOME is set to `D:\Android\sdk`
Platforms is set to `D:\Android\sdk\platforms\android-26`
ADB tool is set to `D:\Android\sdk\platform-tools\adb.exe`
GRADLE_HOME is set to `D:\Android\Android Studio171.44\gradle\gradle-4.1`

Installed driver list:

android: 2.0.47
electron: 1.1.19

---

- app inspector version / 版本号:
2.0.17

- os version / 系统:
Win7 64位

- device  information / 设备版本:
三星s6/android 6.0.1

- terminal log / 终端输出信息:
{ Error: Command failed: D:\Android\sdk\platform-tools\adb.exe -s 85b6395a323756
5a push D:\Program Files\nodejs8.9\node-global\node_modules\app-inspector\node_m
odules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.mac
aca.android.testing

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'D:\\Android\\sdk\\platform-tools\\adb.exe -s 85b6395a3237565a push D:\\P
rogram Files\\nodejs8.9\\node-global\\node_modules\\app-inspector\\node_modules\
\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.maca
ca.android.testing' }
> try `app-inspector -u xxxx --verbose` for more log detail.

- bug可能的原因: 
node安装在D:\\Program Files，push命令中路径没有加双引号导致push错误

**Comment by meowtec** [comment]
@xudafeng 看看 macaca-adb 的问题，是不是要换成 execFile，支持通过数组传参。

**Comment by xudafeng** [comment]
@meowtec 是数组传参问题吗

**Comment by fengguochao** [comment]
https://github.com/macacajs/app-inspector/issues/199

D:\Program Files\nodejs8.9\node-global\node_modules\app-inspector
"Program Files" 安装目录中有空格，请暂时先移除空格。
