### ISSUE TITLE
app-inspector@2.0.18 启动报错：TypeError: hierarchy.node.reverse is not a function

### ISSUE THREAD

**Issue by FLZTester** [macacajs/app-inspector#197]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```
macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.2.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/Shared/android-sdk-macosx`
  Platforms is set to `/Users/Shared/android-sdk-macosx/platforms/android-26`
  ADB tool is set to `/Users/Shared/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 3.3

  Installed driver list:

  android: 2.0.48
  ios: 2.0.34
---

- app inspector version / 版本号:

app-inspector@2.0.18 

- os version / 系统:

MAC 10.12.6 

- device  information / 设备版本:
Android 4.8

- terminal log / 终端输出信息:

>> UIAutomatorWD http server ready
>> Android device started: 10.10.204.156:5555
>> inspector start at: http://10.10.205.118:5678
  <-- GET /

  TypeError: hierarchy.node.reverse is not a function
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/android.js:48:31)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:68:7)
![2018-07-16 6 47 25](https://user-images.githubusercontent.com/38759950/42755007-49182e4c-8929-11e8-89e0-dce79c9cc647.png)

===============================================================
出错的原因：/usr/local/lib/node_modules/app-inspector/lib/android.js 文件中一个函数不正确
hierarchy.node.reverse(); 
我把reverse()函数给删除之后 成功启动了。
![2018-07-16 6 49 32](https://user-images.githubusercontent.com/38759950/42755012-50f2e0da-8929-11e8-9d0c-afa39d0c7227.png)

**Comment by meowtec** [comment]
很奇怪，如果 .node 是一个数组，这一行应该不会报错。如果 .node 不是数组，那么后面的代码就会报错。
