### ISSUE TITLE
运行时出现这个错误怎么解决，output目录下的两个apk都是存在，就是运行不成功，我是win10系统

### ISSUE THREAD

**Issue by caoruihua** [macacajs/app-inspector#199]
C:\WINDOWS\system32>app-inspector -u 997030c0
{ Error: Command failed: D:\android-sdk-windows\platform-tools\adb.exe -s 997030c0 push C:\Program Files\nodejs\node_global\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'D:\\android-sdk-windows\\platform-tools\\adb.exe -s 997030c0 push C:\\Program Files\\nodejs\\node_global\\node_modules\\app-inspector\\node_modules\\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by LayTonQ** [comment]
那就手工把这两个apk装在手机上

**Comment by fengguochao** [comment]
C:\Program Files\nodejs\node_global\node_modules\app-inspector

**Comment by fengguochao** [comment]
C:\Program Files\nodejs\node_global\node_modules\app-inspector
"Program Files" 安装目录中有空格，请暂时先移除空格。
