### ISSUE TITLE
Tool for install app ?

### ISSUE THREAD

**Issue by chenchaoyi** [macacajs/app-inspector#20]
作为App inspector, 首先要有app。

目前使用inspector之前，我需要手动编译app然后安装到simulator里。然后再打开inspector。

有没有更好的建议方法？或者计划在以后实现类似功能，在inspector里直接指定app路径，然后其能完成自动安装（与Appium Inspector类似）？

**Comment by xudafeng** [comment]
@chenchaoyi  这块正在开发，待iOS端真机签名解决后release

@zenzhu

**Comment by xudafeng** [comment]
@chenchaoyi 安装功能没必要集成在app-inspector上

模拟器

`xcrun simctl uninstall "${this.deviceId}" "${pkg}"`;

真机装个deviceinstaller吧
