### ISSUE TITLE
app-inspector 安装失败

### ISSUE THREAD

**Issue by wenshi11019** [macacajs/app-inspector#201]
Environment check:

```
~ » macaca doctor

  macaca-doctor version: 2.0.14


  Node.js checklist:

  node env: /usr/local/opt/node@8/bin/node
  node version: v8.11.4

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.4.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/macos/android-sdk-macosx`
  Platforms is set to `/Users/macos/android-sdk-macosx/platforms/android-28`
  ADB tool is set to `/Users/macos/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.48
  electron: 2.0.3
  ios: 2.0.34
```

---

- app inspector version / 版本号:2.0.19

- os version / 系统:mac os 10.13.6

- device  information / 设备版本:

- terminal log / 终端输出信息:

```
~ » npm i -g app-inspector 
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
/usr/local/bin/app-inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector
/usr/local/bin/inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector

> xctestwd@1.4.0 install /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
> node ./scripts/install.js

start to mv /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd-frameworks-94/Carthage /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
mv: no such file or directory: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd-frameworks-94/Carthage

/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/scripts/install.js:89
  throw _.chalk.red('Carthage is not existed, please reinstall!');
  ^
Carthage is not existed, please reinstall!
npm WARN react-syntax-highlighter@7.0.4 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.0 (node_modules/app-inspector/node_modules/xctestwd):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.0 install: `node ./scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ app-inspector@2.0.19
updated 1 package in 6.511s
```

**Comment by pespinel** [comment]
I'm getting the same error with the 2.0.21 version and macOS Mojave.

Macaca doctor doesn't show any error:

`~ » macaca doctor
macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.11.4

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/pablo/Library/Android/sdk`
  Platforms is set to `/Users/pablo/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/pablo/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  ios: 2.0.35`

- app inspector version / 版本号: 2.0.21
- os version / 系统: mac os 10.14.1
- terminal log / 终端输出信息:

`~ » npm i -g app-inspector
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
/usr/local/bin/inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector
/usr/local/bin/app-inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector

> xctestwd@1.4.5 install /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
> node ./scripts/install.js

start to mv /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd-frameworks/Carthage /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
mv: no such file or directory: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd-frameworks/Carthage

/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/scripts/install.js:93
  throw _.chalk.red('Carthage is not existed, please reinstall!');
  ^
Carthage is not existed, please reinstall!
npm WARN react-syntax-highlighter@7.0.4 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.5 (node_modules/app-inspector/node_modules/xctestwd):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.5 install: `node ./scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ app-inspector@2.0.21
updated 1 package in 27.82s`

**Comment by paradite** [comment]
this is fixed by @xudafeng in https://github.com/macacajs/XCTestWD/commit/7ecd122b19843affbcac4263e63b5bfc7495e199
