### ISSUE TITLE
npm install app-inspector  NO WORK

### ISSUE THREAD

**Issue by sdlr** [macacajs/app-inspector#203]
Hi, when I try to install the inspector it gives me this error. I tried in every way but the result is always this. 
I ask you for help thanks.

npm install app-inspector
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/app-inspector failed, reason: write EPROTO 140735559447424:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
npm ERR! 

-------------------------LOG------------------------

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'app-inspector' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose config Skipping project config: /Users/walter/.npmrc. (matches userconfig)
5 verbose npm-session 96da95e70f2ff913
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for app-inspector@latest request to https://registry.npmjs.org/app-inspector failed, reason: write EPROTO 140735559447424:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 189ms
11 verbose type system
12 verbose stack FetchError: request to https://registry.npmjs.org/app-inspector failed, reason: write EPROTO 140735559447424:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
12 verbose stack
12 verbose stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
12 verbose stack     at emitOne (events.js:116:13)
12 verbose stack     at ClientRequest.emit (events.js:211:7)
12 verbose stack     at onerror (/usr/local/lib/node_modules/npm/node_modules/agent-base/index.js:100:9)
12 verbose stack     at callbackError (/usr/local/lib/node_modules/npm/node_modules/agent-base/index.js:122:5)
12 verbose stack     at <anonymous>

**Comment by xudafeng** [comment]
network issue
