### ISSUE TITLE
浏览器android-screenshot.png 加载不出来，谷歌和火狐浏览器都已经试过不行

### ISSUE THREAD

**Issue by pepsicoffee** [macacajs/app-inspector#206]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

laster new
- os version / 系统:

windows 7 x64
- device  information / 设备版本:

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.

app-inspector -u emulator-5554 --verbose
>> request.js:11:12 [master] pid:7664 get remote update info failed.
>> server.js:16:12 [master] pid:7664 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'emulator-5554',
  ip: '10.255.2.6',
  host: '17031316-PC',
  loaded_time: '2018-09-23 18:19:19' }
>> app-inspector.js:45:12 [master] pid:7664 server start at: http://10.255.2.6:5678
>> uiautomator-client.js:32:14 [master] pid:7664 Package com.macaca.android.testing already exists. No need reinstall.
>> uiautomator-client.js:51:14 [master] pid:7664 Package com.macaca.android.testing.test already exists. No need reinstall.
>> uiautomator-client.js:92:14 [master] pid:7664 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:92:14 [master] pid:7664 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9008<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> Android device started: emulator-5554
>> inspector start at: http://10.255.2.6:5678
  <-- GET /
>> proxy.js:56:14 [master] pid:7664 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9008/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:86:20 [master] pid:7664 Got response with status 200: {"status":0,"value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy rotation=\"0\">\r\n  <node index=\"0\" text=\"\" resource-id=\"\" class=\"android.widget.LinearLayout\" p...
>> Dump Android XML success, save to C:\Java\nodejs\node-global\node_modules\app-inspector\.temp\android.json
  --> GET / 200
  <-- GET /
>> proxy.js:56:14 [master] pid:7664 Proxy: /wd/hub/session/:sessionId/source:GET to http://127.0.0.1:9008/wd/hub/session/:sessionId/source:GET with body: null
>> proxy.js:86:20 [master] pid:7664 Got response with status 200: {"status":0,"value":"<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>\r\n<hierarchy rotation=\"0\">\r\n  <node index=\"0\" text=\"\" resource-id=\"\" class=\"android.widget.LinearLayout\" p...
>> Dump Android XML success, save to C:\Java\nodejs\node-global\node_modules\app-inspector\.temp\android.json
  --> GET / 200

**Comment by xudafeng** [comment]
跟浏览器没关系，检查下网络

**Comment by LLLucian** [comment]
你是不是用虚拟机了？我用虚拟机的，android-screenshot.png 加载不出来

**Comment by pepsicoffee** [comment]
没用


| |
宝贝儿宅
邮箱：zhaigaofeng@126.com
|

签名由 网易邮箱大师 定制

在2018年11月05日 10:20，小骆 写道：

你是不是用虚拟机了？我用虚拟机的，android-screenshot.png 加载不出来
