### ISSUE TITLE
pid:2641 xctest client exit with code: 65, signal: null

### ISSUE THREAD

**Issue by rafaelcs** [macacajs/app-inspector#209]
Actually the inspector was working perfectly, but it suddenly stopped working

Environment check:

```bash
  macaca-doctor version: 2.0.15


  Node.js checklist:

  node env: /usr/local/opt/node@10/bin/node
  node version: v10.13.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `11`
  JAVA_HOME is not set
  ANDROID_HOME is set to `/Users/rafaelcarvalho/Library/Android/sdk`
  Platforms is set to `/Users/rafaelcarvalho/Library/Android/sdk/platforms/android-28`
  ADB tool is set to `/Users/rafaelcarvalho/Library/Android/sdk/platform-tools/adb`
  Not accepted Android SDK license agreements
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.35
```

---

- app inspector version / 版本号:
```bash
2.0.21
```
- os version / 系统:
```bash
Mojave 10.14.1 (18B75)
```
- device  information / 设备版本:
```bash
Simulator iphone SE 11.4 (but it doesn not work with any version)
```
- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.
```bash
 ✘  ~  app-inspector -u 40B4361A-6FCA-45B9-994C-6E58352CD063 --verbose
>> server.js:16:12 [master] pid:2641 server start with config:
 { port: 5678,
  verbose: true,
  udid: '40B4361A-6FCA-45B9-994C-6E58352CD063',
  ip: '192.168.0.3',
  host: 'MacBook-Rafael.local',
  loaded_time: '2018-11-29 21:13:57' }
>> app-inspector.js:45:12 [master] pid:2641 server start at: http://192.168.0.3:5678
>> xctest-client.js:55:14 [master] pid:2641 project path: /Users/rafaelcarvalho/.npm-global/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:247:14 [master] pid:2641 xcode version: 10.1
>> XCTestWD version: 1.4.5
>> xctest-client.js:195:18 [master] pid:2641 please check project: /Users/rafaelcarvalho/.npm-global/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:2641 please check project: /Users/rafaelcarvalho/.npm-global/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:2641 please check project: /Users/rafaelcarvalho/.npm-global/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:286:14 [master] pid:2641 killing runnerProc pid: 2644
>> xctest-client.js:206:16 [master] pid:2641 xctest client exit with code: 65, signal: null
```

**Comment by jade685** [comment]
Hi, I'm having the same problem. Wondering if you've solved this yet?

**Comment by SamuelZhaoY** [comment]
Hi @jade685 @rafaelcs  please check the xcode project installed under the node global directory: /Users/rafaelcarvalho/.npm-global/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj , I think there is some compilation issue on your device

**Comment by jade685** [comment]
Hi, @SamuelZhaoY. Thanks for the reply. 
Actually I do have a problem running the project.

Following is the error message:
![bug](https://user-images.githubusercontent.com/17906011/51300195-038bf100-1a66-11e9-8125-63e7b0bdcbba.png)

Also I found two XCTestWD.xcodeproj, one in **app-inspector** folder and another in **masaca-ios.**
And I signed them both. Is this going to be a problem?

**Comment by SirCYong** [comment]
I also encountered the same problem, how can I solve it?

**Comment by jade685** [comment]
@SirCYong 
This is how I solve the problem.

step1 : recompile your `XCTestWD.xcodeproj` in xcode, make sure it's signed.
step2 : check if there's an app called `XCTestWDUITests` installed on your device. 
If not, go to `/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD` on your terminal. You might not have same path as mine, just find where `XCTestWD` is. 
Then compile `XCTestWD.xcodeproj` ( command : `xcodebuild -project XCTestWD.xcodeproj -scheme XCTestWDUITests -destination 'id=DEVICE-ID' test`)

Then try restart app inspector, it should be working.
