### ISSUE TITLE
Error when running XCTestWDUnitTest

### ISSUE THREAD

**Issue by jade685** [macacajs/app-inspector#214]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```
  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.15.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yaoweiqi/Applications/android-sdk-macosx`
  Android SDK Platforms directory is not exist, please install the whole thing
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.35

---

- app inspector version / 版本号: 2.0.22 

- os version / 系统: 10.14.1 

- device  information / 设备版本: iPhone 7 (real device)

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.

>> server.js:16:12 [master] pid:19000 server start with config:
 { port: 5678,
  verbose: true,
  udid: '8f4ac7de8f045e70a0b8c18d1b09cf36e3de3a67',
  ip: '192.168.199.187',
  host: 'yaoweiqideMBP.lan',
  loaded_time: '2019-01-11 17:44:12' }
>> app-inspector.js:45:12 [master] pid:19000 server start at: http://192.168.199.187:5678
>> xctest-client.js:55:14 [master] pid:19000 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:247:14 [master] pid:19000 xcode version: 10.1
>> XCTestWD version: 1.4.5
>> xctest-client.js:195:18 [master] pid:19000 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:19000 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:19000 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:286:14 [master] pid:19000 killing runnerProc pid: 19003
>> xctest-client.js:206:16 [master] pid:19000 xctest client exit with code: 65, signal: null

Following is the error when running XCTestWDUnitTest:
Command PhaseScriptExecution failed with a nonzero exit code

Also, I have two XCTestWD. One is in app-inspector and the other is in macaca-ios. Both signed.
Is this going to be a problem?

**Comment by jade685** [comment]
This is the error running XCTestWDUnitTests:
![default](https://user-images.githubusercontent.com/17906011/51094697-26aa6c80-17ea-11e9-9008-5e87f5c87f78.png)

**Comment by SamuelZhaoY** [comment]
install ideviceinstaller first, or alternatively, remove that script in build phase
