### ISSUE TITLE
app-inspector -u 00008020-00067CA91EXXXXXXX 不支持这个格式的iPhone xr 以上的真机，有机会兼容吗

### ISSUE THREAD

**Issue by lin8090** [macacajs/app-inspector#217]
app-inspector -u 00008020-00067CA91EXXXXXXX 不支持这个格式的iPhone xr 以上的真机，有机会兼容吗

**Comment by lin8090** [comment]
有考虑兼容吗

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/pull/218
