### ISSUE TITLE
Error updating app-inspector

### ISSUE THREAD

**Issue by jade685** [macacajs/app-inspector#225]
I was using app inspector fine before this update, but after this update, my 'xctestwd' seems got deleted. 

I tried reinstall app inspector, but I got error : Carthage is not existed, please reinstall!
But I've already installed Carthage. So I'm really confused. Please help, thanks!

I will put the log in the end. 

P.S. I'm only using iOS, so you should ignore Android checklist.

Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor

 macaca-doctor version: 2.0.16


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.15.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yaoweiqi/Applications/android-sdk-macosx`
  Android SDK Platforms directory is not exist, please install the whole thing
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.35
  location: /usr/local/lib/node_modules/macaca-ios

```
---

- app inspector version / 版本号:  2.0.24 

- os version / 系统: 10.14.3

- device  information / 设备版本: iPhone7 ;  iOS 12.1.2

- terminal log / 终端输出信息:
>> server.js:16:12 [master] pid:13542 server start with config:
 { port: 5678,
  verbose: true,
  udid: '8f4ac7de8f045e70a0b8c18d1b09cf36e3de3a67',
  ip: '192.168.199.164',
  host: 'yaoweiqideMBP.lan',
  loaded_time: '2019-02-20 14:29:05' }
>> app-inspector.js:45:12 [master] pid:13542 server start at: http://192.168.199.164:5678
{ Error: Cannot find module 'xctestwd'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/lib/ios.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }

> try `app-inspector -u xxxx --verbose` for more log detail.

**Log for `npm i app-inspector -g`:**
```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
/usr/local/bin/inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector.js
/usr/local/bin/app-inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector.js

> xctestwd@1.4.6 install /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
> node ./scripts/install.js

start to mv /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd-frameworks/Carthage /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
mv: no such file or directory: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd-frameworks/Carthage

/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/scripts/install.js:104
  throw _.chalk.red('Carthage is not existed, please reinstall!');
  ^
Carthage is not existed, please reinstall!
npm WARN react-syntax-highlighter@7.0.4 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.6 (node_modules/app-inspector/node_modules/xctestwd):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.6 install: `node ./scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ app-inspector@2.0.24
updated 1 package in 44.74s
```

**Log for `brew install carthage`:**
```
Warning: carthage 0.31.2 is already installed and up-to-date
To reinstall 0.31.2, run `brew reinstall carthage`
```

**Comment by paradite** [comment]
I cannot reproduce the issue. It is working fine for me.
Try `npm uninstall -g app-inspector`, then `npm i app-inspector -g`.
Also, you can try manually doing `npm i -g xctestwd-frameworks` and see if it contains `Carthage` inside `usr/local/lib/node_modules/xctestwd-frameworks`. It should be there.

**Comment by jade685** [comment]
I tried `npm uninstall -g app-inspector`, then `npm i app-inspector -g`.
I didn't get the error. And I got xctestwd, and it's working fine now! 
Thanks a lot @paradite !

I tried second method as well. I tried `cd usr/local/lib/node_modules/xctestwd-frameworks` after `npm i -g xctestwd-frameworks`. But it says `No such file or directory`. So how do I find where `Carthage` was installed? 

p.s. I tried `macaca doctor`, I still didn't see information regarding `Carthage`.
```

  macaca-doctor version: 2.0.16


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.15.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yaoweiqi/Applications/android-sdk-macosx`
  Android SDK Platforms directory is not exist, please install the whole thing
  Command Line Tools: gradle is uninstalled

  Installed driver list:
```

**Comment by jade685** [comment]
Also I used to have two XCTestWD.xcodeproj, one in `/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD` and another in `/usr/local/lib/node_modules/masaca-ios/node_modules/xctestwd/XCTestWD`. And I signed them both.

Though I only have one in  `app-inspector` now, the other one in `masaca-ios` disappeared after I tried to run app-inspector before I solve this error.

So what's the difference between these two `XCTestWD`? Thank you!

**Comment by paradite** [comment]
When you install `app-inspector`, npm installs its dependencies including `xctestwd` inside `app-inspector/node_modules`.
`masaca-ios/node_modules/xctestwd` will only appear when you do `npm install masaca-ios` and only disappear when you do `npm uninstall masaca-ios`.
So I don't think it has anything to do with uninstalling `app-inspector`.
You can read more on node module resolution here: https://medium.freecodecamp.org/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8
