### ISSUE TITLE
编译xctestwd的时候，提示签名错误，导致xctestwd没有在node_modules里面，想手动更换签名也不可

### ISSUE THREAD

**Issue by testerSunshine** [macacajs/app-inspector#226]
Environment check:

```bash
安装命令
DEVELOPMENT_TEAM_ID=JXB9U7MJCZ  npm install app-inspector@2.0.9 -g
有一个疑问，我指定了TEAM_ID，但是编译xctestwd的时候还是拿的别的TEAM_ID，而且我不知道这个TEAM_ID是哪里来的
ps: DEVELOPMENT_TEAM_ID这个也加入了环境变量
```

---

- app inspector version / 版本号:

app-inspector@2.0.9

- os version / 系统:

10.13.4 
- device  information / 设备版本:

- terminal log / 终端输出信息:

(node:71991) UnhandledPromiseRejectionWarning: ,WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Checking the license for package Android SDK Build-Tools 28.0.3 in /usr/local/mysoftware/android-sdk-macosx/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
Checking the license for package Android SDK Platform 26 in /usr/local/mysoftware/android-sdk-macosx/licenses
Warning: License for package Android SDK Platform 26 not accepted.
,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-26 Android SDK Platform 26
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: /usr/local/mysoftware/android-sdk-macosx

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

(node:71991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:71991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> xctestwd@1.4.7 install /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
> node ./scripts/install.js

start to mv /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd-frameworks-94/Carthage /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd
Carthage is existed: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/Carthage
preparing xctestrun build
User defaults from command line:
    IDEDerivedDataPathOverride = /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build

=== BUILD TARGET XCTestWD OF PROJECT XCTestWD WITH CONFIGURATION Debug ===

Check dependencies
2019-03-19 17:25:41.474 xcodebuild[72020:478492] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “XCTestWDUITests_iphoneos11.4-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products/XCTestWDUITests_iphoneos11.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fc636ac8450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2019-03-19 17:25:41.475 xcodebuild[72020:478492] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder “XCTestWDUITests_iphoneos11.4-arm64.xctestrun” doesn’t exist." UserInfo={NSFilePath=/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products/XCTestWDUITests_iphoneos11.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fc636ab3fb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Code Signing Error: No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "CM2CQ7U9GM" with a private key was found.

** TEST BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
fs.js:928
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/build/Build/Products'
    at Object.fs.readdirSync (fs.js:928:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/scripts/install.js:116:17)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.7 (node_modules/app-inspector/node_modules/xctestwd):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xctestwd@1.4.7 install: `node ./scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by SamuelZhaoY** [comment]
reinstall xctestwd@1.4.10, the issue has been fixed
