### ISSUE TITLE
app-inspector连iOS真机查看元素报错：xctest-client.js:309:14 [master] pid:34606 Fail to start xctest: Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/xctestwd/XCTestWD/build/Build/Products' Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/xctestwd/XCTestWD/build/Build/Products'

### ISSUE THREAD

**Issue by YGQ8988** [macacajs/app-inspector#238]
环境:

```macaca doctor

  macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v12.10.0

  iOS checklist:

  macOS version: 10.14.6
  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/ygq/Documents/android-sdk`
  Platforms is set to `/Users/ygq/Documents/android-sdk/platforms/android-26`
  ADB tool is set to `/Users/ygq/Documents/android-sdk/platform-tools/adb`
  gradle is installed, version: 5.1

  Installed driver list:

  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android

  ios: 2.0.36
  location: /usr/local/lib/node_modules/macaca-ios
```

---

- app inspector version / 版本号: 2.0.24

- os version / 系统:Mac 10.14.6

- device  information / 设备版本:iOS 12.4.1

- terminal log / 终端输出信息:

>> server.js:16:12 [master] pid:34606 server start with config:
 {
  port: 5678,
  verbose: true,
  udid: 'fca2ddc52a5b19d6d997c6d6d2cb0a5570629257',
  ip: '172.16.16.225',
  host: 'ygqs-MacBook-Pro.local',
  loaded_time: '2019-09-10 15:56:46'
}
>> app-inspector.js:45:12 [master] pid:34606 server start at: http://172.16.16.225:5678
>> xctest-client.js:56:14 [master] pid:34606 project path: /usr/local/lib/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:34606 xcode version: 10.3
>> XCTestWD version: 1.4.18
>> xctest-client.js:309:14 [master] pid:34606 Fail to start xctest: Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/xctestwd/XCTestWD/build/Build/Products'
Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/xctestwd/XCTestWD/build/Build/Products'
    at Object.readdirSync (fs.js:865:3)
    at /usr/local/lib/node_modules/xctestwd/lib/xctest-client.js:189:26
    at new Promise (<anonymous>)
    at XCTest.startBootstrap (/usr/local/lib/node_modules/xctestwd/lib/xctest-client.js:182:12)
    at startBootstrap.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/usr/local/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/app-inspector/node_modules/_co@4.6.0@co/index.js:118:63) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/usr/local/lib/node_modules/xctestwd/XCTestWD/build/Build/Products'
}
>> iOS device started: fca2ddc52a5b19d6d997c6d6d2cb0a5570629257
>> inspector start at: http://172.16.16.225:5678
  <-- GET /
  <-- GET /android.json
  --> GET /android.json 404
  <-- GET /android-screenshot.png
  --> GET /android-screenshot.png 404
>> helper.js:94:16 [master] pid:34606 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14)

**Comment by YGQ8988** [comment]
/usr/local/lib/node_modules/xctestwd/XCTestWD/build/Build/Products
手动创建，Build及Products后运行成功，大家参考下吧

**Comment by liyaoyao6342** [comment]
> /usr/local/lib/node_modules/xctestwd/XCTestWD/build/Build/Products
> 手动创建，Build及Products后运行成功，大家参考下吧

请问具体是怎么做呢，我一直遇到这个问题，刚才还提了个issue
