### ISSUE TITLE
Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by dubrova** [macacajs/app-inspector#239]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```
  macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: /Users/luba/.nvm/versions/node/v11.13.0/bin/node
  node version: v11.13.0

  iOS checklist:

  macOS version: 10.14.6
  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 11.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

- app inspector version / 版本号:
app-inspector@2.0.24

- os version / 系统:
Mojave 10.14.6

- device  information / 设备版本:
real device iphone 6s

- terminal log / 终端输出信息:
/Users/***/.config/yarn/global/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift:9:8: Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/***/.config/yarn/global/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/arm64.swiftmodule
> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by dubrova** [comment]
After installing app-inspector, I have code 65. I update signing in /Users/***/.config/yarn/global/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj

When I rebuild it, I got the following error for XCTestWD target:
`/Users/***/.config/yarn/global/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift:9:8: Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /Users/***/.config/yarn/global/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/arm64.swiftmodule`

**Comment by rafaelcs** [comment]
I'm getting the same error.

**Comment by rafaelcs** [comment]
Any update here? :)

**Comment by rafaelcs** [comment]
Update?

**Comment by WhalenMarting** [comment]
I had the same problem when I updated to xcode11

Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.4.21@xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by tking16** [comment]
I just tried to run the [fix in this issue here](https://github.com/macacajs/app-inspector/issues/209#issuecomment-471971526), and I got
```
 error: module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64.swiftmodule
import Swifter
       ^
```

**Comment by dubrova** [comment]
I fixed it by `carthage update --platform iOS --no-use-binaries` from `yarn/global/node_modules/xctestwd/`

**Comment by tking16** [comment]
Running @dubrova 's carthage command above finally got the port to open, but I get `internal server error` in Chrome now.

My verbose run ⬇️

`>> XCTestWD version: 1.4.18`
>> xctestwd start with port: 8001
Error: connect ECONNREFUSED 127.0.0.1:8001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8001
}
>> iOS device started: 97E29B63-71B9-4F61-A397-5A8ACD3928CF
>> inspector start at: http://10.63.140.13:5678
  <-- GET /
`
  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
`
  <-- GET /favicon.ico
  --> GET /favicon.ico 404
  <-- GET /
`
  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
`
^C
 ✘ theo.king@g116249mac  ~/code/global/app/ios/guacamole/testing/app-at   at-enable-localisation  app-inspector -u 97E29B63-71B9-4F61-A397-5A8ACD3928CF --verbose
>> server.js:16:12 [master] pid:23289 server start with config:
 {
  port: 5678,
  verbose: true,
  udid: '97E29B63-71B9-4F61-A397-5A8ACD3928CF',
  ip: '10.63.140.13',
  host: 'g116249mac',
  loaded_time: '2019-11-27 16:57:19'
}
>> app-inspector.js:45:12 [master] pid:23289 server start at: http://10.63.140.13:5678
>> xctest-client.js:56:14 [master] pid:23289 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:23289 xcode version: 11.1
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:23289 hitted for default mode
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:23289 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{}}
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: socket hang up
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:227:20 [master] pid:23289 hitted for default mode
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:23289 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:309:14 [master] pid:23289 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:322:14 [master] pid:23289 killing runnerProc pid: 23294
Error: connect ECONNREFUSED 127.0.0.1:8001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8001
}
>> iOS device started: 97E29B63-71B9-4F61-A397-5A8ACD3928CF
>> inspector start at: http://10.63.140.13:5678
>> xctest-client.js:242:16 [master] pid:23289 xctest client exit with code: null, signal: SIGKILL
  <-- GET /
>> helper.js:94:16 [master] pid:23289 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
`
  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
`

**Comment by paradite** [comment]
should be fixed now. if still having issues, please create new issue here:
https://github.com/alibaba/macaca/issues
