### ISSUE TITLE
查找元素不准确

### ISSUE THREAD

**Issue by xudafeng** [macacajs/app-inspector#24]
- app inspector version / 版本号:latest

- os version / 系统:ios10

- device  information / 设备版本:iphone6 真机

**Comment by xudafeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1011681/18613694/52ef47b8-7db2-11e6-8f04-f08fc566628f.png)

**Comment by meowtec** [comment]
我看了一遍，就是这个样子。你可以在树状图里面找一下，是找不到最小单元格的。

**Comment by xudafeng** [comment]
@meowtec 可是我点击的是`移动网络`

**Comment by meowtec** [comment]
你这个就是蜂窝移动网络

**Comment by meowtec** [comment]
貌似渲染区块有点问题

**Comment by xudafeng** [comment]
@meowtec 要npm升级吧？

**Comment by meowtec** [comment]
刚 publish

**Comment by xudafeng** [comment]
💯
