### ISSUE TITLE
安装app-inspector时，最后提示编译失败，运行app-inspector时，提示没有该命令

### ISSUE THREAD

**Issue by sherry1993** [macacajs/app-inspector#240]
**$ npm install app-inspector -g**
输出以下报错
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/xxxx/.nvm/versions/node/v6.11.4/lib/node_modules/node/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
simulator optimization .xctestrun file generated: undefined
Successfully updated Bundle Id, but no Team Id was provided. Please update your team id manually in /Users/XXXXXX/.nvm/versions/node/v6.11.4/lib/node_modules/node/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj/project.pbxproj, or reinstall the module with DEVELOPMENT_TEAM_ID in environment variable.

> core-js@2.6.9 postinstall /Users/XXXXX/.nvm/versions/node/v6.11.4/lib/node_modules/node/lib/node_modules/app-inspector/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN react-syntax-highlighter@7.0.4 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.

+ app-inspector@2.0.24
added 523 packages from 549 contributors in 38.661s

**$ app-inspector -u YOUR-DEVICE-ID（设备id）**
-bash: app-inspector: command not found

 **$ macaca doctor**

macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: /Users/XXX/.nvm/versions/node/v6.11.4/bin/node
  node version: v12.9.0

  iOS checklist:

  macOS version: 10.13.6
  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/XXXX/Library/Android/sdk`
  Platforms is set to `/Users/XXXX/Library/Android/sdk/platforms/android-28`
  ADB tool is set to `/Users/XXXXX/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.2

  Installed driver list:

**Comment by xudafeng** [comment]
可以装最新版
