### ISSUE TITLE
Installing app-inspector fails with xcode 11 .0

### ISSUE THREAD

**Issue by rayt8909** [macacajs/app-inspector#241]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```
macaca-doctor version: 2.0.18
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v11.13.0

  iOS checklist:

  macOS version: 10.14.6
  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 11.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/raytrejo/android/`
  Platforms is set to `/Users/raytrejo/android/platforms/android-29`
  ADB tool is set to `/Users/raytrejo/android/platform-tools/adb`
  Command Line Tools: gradle is uninstalled

  Installed driver list:
---

- app inspector version / 版本号:
npm list -g app-inspector
/usr/local/lib
└── app-inspector@2.0.24 

- os version / 系统:
macOS Mojave
Version 10.14.6

xcode version:  11.0 (11A420a)

- device  information / 设备版本:
iOS simulator: iPhone X
iOS version:  13.0

- terminal log / 终端输出信息:
I ran npm i app-inspector -g 

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDAlertController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDElementController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDScreenshotController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDSessionController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDSourceController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDTitleController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDUrlController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDWindowController.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/XCTestWDAlert.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/XCTestWDErrors.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/XCTestWDReponse.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDFailureProofTestCase.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/XCTestWDSession.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/XCTestWDStatus.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/XCUIElementTypeTransformer.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/Extensions/XCTestWDFindElementUtils.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/Extensions/XCTestWDMathUtils.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/Extensions/XCTestWDXPath.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/Utils/XCTestWDAccessibility.swift
	CompileSwift normal x86_64 /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Modules/Utils/XCTestWDApplicationTree.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(22 failures)
simulator optimization .xctestrun file generated: undefined
Successfully updated Bundle Id, but no Team Id was provided. Please update your team id manually in /Users/raytrejo/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj/project.pbxproj, or reinstall the module with DEVELOPMENT_TEAM_ID in environment variable.

> core-js@2.6.9 postinstall /Users/raytrejo/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN react-syntax-highlighter@7.0.4 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN raytrejo@1.0.0 No description
npm WARN raytrejo@1.0.0 No repository field.

+ app-inspector@2.0.24
added 449 packages from 517 contributors and audited 3854 packages in 41.721s
found 60 vulnerabilities (26 low, 29 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by chemanth** [comment]
follow steps here at https://github.com/macacajs/app-inspector#ios-real-device
and see if you get past this error.

**Comment by WhalenMarting** [comment]
I had the same problem when I updated to xcode11,
Here are the tips when compiling:

Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.4.21@xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

My environment is  Macos10.14.6  xcode Version 11.2 (11B52)

**Comment by paradite** [comment]
should be fixed now. if still having issues, please create new issue here:
https://github.com/alibaba/macaca/issues

**Comment by rayt8909** [comment]
npm install -g app-inspector
the version did not change?  app-inspector@2.0.24

**Comment by paradite** [comment]
> npm install -g app-inspector
> the version did not change? app-inspector@2.0.24

yes. uninstalling and reinstalling should fix it. only dependency `xctestwd`'s version was updated.
