### ISSUE TITLE
[Question] How does the inspector work?

### ISSUE THREAD

**Issue by patchthecode** [macacajs/app-inspector#242]
Hi, is there any documentation/articles on how this inspector works?
I have been looking at Appium inspector, and now this one, but I cant seem to find out how the iOS app grabs the view hierarchy and sends it to the stand alone app.

Did you guys have any explanation anywhere or can you guide me in the right direction?

**Comment by tking16** [comment]
This is all I know of https://macacajs.github.io/app-inspector/

**Comment by zuaaef** [comment]
@patchthecode check out our [Inspector here](https://www.simpleuitesting.com)
It is open source and you can see the code how we did it.
Cheers 🍻

**Comment by patchthecode** [comment]
@zuaaef 
found it.
thank you so much!
