### ISSUE TITLE
Xcode11.1可以正常使用，Xcode11.2无法使用

### ISSUE THREAD

**Issue by WhalenMarting** [macacajs/app-inspector#243]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by WhalenMarting** [comment]
在xcode11.2下，提示65

**Comment by paradite** [comment]
已经兼容xcode 11.2了，重新安装试试。

**Comment by willisfeng** [comment]
{
  port: '5682',
  verbose: true,
  udid: '6F60B20C-B3B5-5426-8AA1-004D1B1B5879',
  ip: '172.16.9.250',
  host: 'iosdeiMac.local',
  loaded_time: '2019-12-04 09:34:24'
}
>> app-inspector.js:45:12 [master] pid:19160 server start at: http://172.16.9.250:5682
process.env.MACACA_XCTESTWD_ROOT_PATH
undefined
>> xctest-client.js:56:14 [master] pid:19160 project path: /usr/local/Cellar/node/12.12.0/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:19160 xcode version: 11.2.1
>> XCTestWD version: 1.4.22
>> xctest-client.js:230:20 [master] pid:19160 please check project: /usr/local/Cellar/node/12.12.0/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:19160 please check project: /usr/local/Cellar/node/12.12.0/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:19160 please check project: /usr/local/Cellar/node/12.12.0/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:322:14 [master] pid:19160 killing runnerProc pid: 19164
>> xctest-client.js:242:16 [master] pid:19160 xctest client exit with code: 65, signal: null

**Comment by willisfeng** [comment]
still  have the promble, xcode version 11.2.1

**Comment by paradite** [comment]
> still have the promble, xcode version 11.2.1

please run with `--verbose` and provide the logs.
also please try to uninstall `app-inspector` and `xctestwd ` globally and re-try.
