### ISSUE TITLE
使用ipad，元素的位置定位不准确，而且orientation不对。有什么方法可以调整orientation吗？

### ISSUE THREAD

**Issue by fb0122** [macacajs/app-inspector#246]
Environment check:
---

- app inspector version / 版本号: 2.0.27

- os version / 系统:  Mac OS

- device  information / 设备版本:   ios13.3

如题，使用的是ipad，但是app-inspector出来的方向不对，所以元素也选不上，请问有什么修改orientation的方法吗？

**Comment by xudafeng** [comment]
没有适配ipad，欢迎pr
