### ISSUE TITLE
APP-INSPECTOR RUNNING on XCODE Version 11.4 (11E146) can't install XCTestWD 

### ISSUE THREAD

**Issue by mariushorvat** [macacajs/app-inspector#247]
Hi right after I've update the XCode to 11.4 I got the following error.
It looks like it can't not install the XCTestWD.

Please NOTE : I've uninstalled app-inspector and xctestwd then I've re-install them > same error

Is there a work around to get this back and running?

Thanks!

>> port: 5678 was occupied, changed port: 5679
>> server.js:16:12 [master] pid:76107 server start with config:
 { port: 5679,
  verbose: true,
  udid: 'xxxxxx-xxxxxxx,
  ip: 'xxx.xxx.xxx.xx',
  host: 'JAKE-Brown',
  loaded_time: '2020-04-14 09:30:59' }
>> app-inspector.js:45:12 [master] pid:76107 server start at: http://188.555.332.32:5679
process.env.MACACA_XCTESTWD_ROOT_PATH
undefined
>> xctest-client.js:56:14 [master] pid:76107 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:76107 xcode version: 11.4
>> XCTestWD version: 1.4.23
>> xctest-client.js:230:20 [master] pid:76107 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:76107 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:322:14 [master] pid:76107 killing runnerProc pid: 76115
>> xctest-client.js:242:16 [master] pid:76107 xctest client exit with code: 65, signal: null

**Comment by paradite** [comment]
tracking this here: https://github.com/alibaba/macaca/issues/970

**Comment by paradite** [comment]
@mariushorvat this issue should be fixed now. please create a new issue if the error persists.

**Comment by mariushorvat** [comment]
@paradite I've test it - All good now. Thanks for taking care of this!
