### ISSUE TITLE
can't use on xcode12 and iOS14

### ISSUE THREAD

**Issue by Shaobo-Zhang-Bose** [macacajs/app-inspector#254]
Environment check:

```bash
$ npm i macaca-cli -g && macaca doctor
```

---

- app inspector version / 版本号:  2.0.29 from npm

- os version / 系统: 

- device  information / 设备版本: 14.0.1

- terminal log / 终端输出信息:

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by mariushorvat** [comment]
these are the errors when I run: app-inspector -u xxxx --verbose on IOS 14 - Xcode 12

>> xctest-client.js:222:18 [master] pid:17443 Testing failed:
	Module compiled with Swift 5.2 cannot be imported by the Swift 5.3 compiler: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDAlertController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDElementController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDScreenshotController.swift
	CompileS...
>> xctest-client.js:233:20 [master] pid:17443 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:329:14 [master] pid:17443 killing runnerProc pid: 17479
>> xctest-client.js:245:16 [master] pid:17443 xctest client exit with code: 65, signal: null

**Comment by kasia-heetch** [comment]
I am having the same issue - any progress here? :pray:

**Comment by Shaobo-Zhang-Bose** [comment]
If I use xcode 12 to build, it is failed to build.
If I use xcode 11 to build, it can build successfully, but it fail to connect to iOS14.

**Comment by tking16** [comment]
Same issue here, got a different error to original post though I believe

`iates.noindex/XCTestWD.build/Debug-iphonesimulator/XCTestWD.build/Objects-normal/x86_64/XCTestWDApplicationTree.o -index-store-path /Users/theo.king/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Index/DataStore -index-system-modules
/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift:9:8: error: module compiled with Swift 5.1.2 cannot be imported by the Swift 5.3 compiler: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
import Swifter
       ^


>> xctest-client.js:206:16 [master] pid:20631
Test session results, code coverage, and logs:
	/Users/theo.king/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/Run-XCTestWDUITests-2020.10.19_10-59-27-+0100.xcresult


>> xctest-client.js:222:18 [master] pid:20631 Testing failed:
	Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.3 compiler: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
	Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDAlertController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDElementController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD/Server/Controllers/XCTestWDScreenshotController.swift
	Compil...
>> xctest-client.js:233:20 [master] pid:20631 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:329:14 [master] pid:20631 killing runnerProc pid: 20634
>> xctest-client.js:245:16 [master] pid:20631 xctest client exit with code: 65, signal: null`

**Comment by ganjarpanji** [comment]
any other workaround inspector besides appium-desktop and macaca-inspector ?

**Comment by kmilic** [comment]
I'm having same issue with failed build when using xcode 12 and thus not being able to use Macaca for automation on iOS 14. 
Can you please suggest workaround or let us know if there is a plan to support iOS 14.

**Comment by tking16** [comment]
Macaca is clearly dead... You guys are better off using the Appium inspector XCode's built-in app inspector

**Comment by mariushorvat** [comment]
I had found a workaround (if you guys still want to use Macaca).

- Install Xcode11 (it can be used side by side with Xcode12)
- You need to build the app using Xcode11 so that the Product .app build is created for a IOS13
- After that Macaca would pick it up the build created by Xcode11 /IOS13.

It works but you will need to have now 2 Xcode's side by side.

**Comment by paradite** [comment]
> Macaca is clearly dead... You guys are better off using the Appium inspector XCode's built-in app inspector

Sorry I was busy with other things, taking a look this week.

You can use the walkaround that @mariushorvat suggested, or manually compile `XCTestWD` Carthage dependencies and replace the old dependencies in `xctestwd-frameworks` with new ones. the `xctestwd-frameworks` is merely an optimization to pre-compile the Carthage dependencies and save some time. Unfortunately it needs to be updated with every Swift update.

Meanwhile, let's track the issue here:
https://github.com/alibaba/macaca/issues/985

**Comment by tking16** [comment]
Thanks for the workaround and update!

**Comment by paradite** [comment]
> Thanks for the workaround and update!

fixed. please remove the old app-inspector package and reinstall it
