### ISSUE TITLE
WebView support

### ISSUE THREAD

**Issue by ahmetkocu** [macacajs/app-inspector#28]
**Are you thinking to support hybrid app?**

I review the code, maybe I can make some enhancements and share a working example with you for android.

However, uiautomator is not sufficent, I try to integrate selendroid or appium server with app-inspector.

**Comment by meowtec** [comment]
It sounds good, while we recommend chrome inspect(chrome://inspect) for this purpose, it is very powerful and convenient to debug webView.

Even so, I am quite interested in your working example.

cc @xudafeng

**Comment by xudafeng** [comment]
It sounds good https://testerhome.com/topics/5054
