### ISSUE TITLE
Android Error: Command failed: /Users/zhouzhonglin/android-sdks/platform-tools/adb -s emulator-5554 shell "cat /data/local/tmp/macaca-dump.xml"

### ISSUE THREAD

**Issue by joesky88** [macacajs/app-inspector#31]
- app inspector version / 版本号:1.2.12

- os version / 系统: macOS Sierra

- device  information / 设备版本:Android7.0 模拟器

- terminal log / 终端输出信息:

$ app-inspector -u emulator-5554 --verbose
>> server.js:16:12 [master] pid:5340 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'emulator-5554',
  ip: '172.16.30.46',
  host: 'zhouzhonglindeMacBook-Pro.local',
  loaded_time: '2016-10-11 15:10:21' }
>> app-inspector.js:42:10 [master] pid:5340 server start at: http://172.16.30.46:5678
Warning: This version of UI Automator is deprecated. New tests should be written using

UI Automator 2.0 which is available as part of the Android Testing Support Library.

See https://developer.android.com/training/testing/ui-testing/uiautomator-testing.html

for more details.

INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:

INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner

INSTRUMENTATION_STATUS: test=testStartServer

INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize

INSTRUMENTATION_STATUS: current=1

INSTRUMENTATION_STATUS_CODE: 1

uiautomator start socket server.

>> socket server ready
>> socket client ready
>> Android device started: emulator-5554
>> inspector start at: http://172.16.30.46:5678

  <-- GET /
recive: {"cmd":"getSource","args":{}}

return: {"success":true,"data":{"status":0,"value":true}}

  Error: Command failed: /Users/zhouzhonglin/android-sdks/platform-tools/adb -s emulator-5554 shell "cat /data/local/tmp/macaca-dump.xml"
  /system/bin/sh: cat: /data/local/tmp/macaca-dump.xml: No such file or directory

      at ChildProcess.exithandler (child_process.js:207:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:852:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by joesky88** [comment]
execute the command,then it works!
adb  -s emulator-5554 root

**Comment by meowtec** [comment]
interesting...
这是什么原理

**Comment by joesky88** [comment]
是权限的原因，需要root用户登录才可以

**Comment by ansonliao** [comment]
@joesky88 
如果是真机，请问怎么解决?
`adb -s root`提示:

```bash
adbd cannot run as root in production builds
```
