### ISSUE TITLE
总是提示我java_home没有设置，但我已经设置

### ISSUE THREAD

**Issue by niasand** [macacajs/app-inspector#32]
- app inspector version / 版本号:
 1.2.12

- os version / 系统:

mac sirrea
- device  information / 设备版本:

- terminal log / 终端输出信息:

```
jerry:Home/ $ sudo npm install app-inspector -g                                                                [0:19:31]
Password:
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/app-inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector
/usr/local/bin/inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector

> uiautomator-client@1.0.27 install /usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client
> node ./scripts/build.js

/usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:178
      throw e;
      ^

Error: $JAVA_HOME is not set
    at checkJavaHome.then.catch.then.then.catch.then.std (/usr/local/lib/node_modules/app-inspector/node_modules/java-home/lib/java-home.js:89:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
npm WARN install:uiautomator-client@1.0.27 uiautomator-client@1.0.27 install: `node ./scripts/build.js`
npm WARN install:uiautomator-client@1.0.27 Exit status 1
/usr/local/lib
└── app-inspector@1.2.12
```

> try `macaca doctor` for more log detail.
jerry:node_modules/ $ macaca doctor                                                                            [0:26:17]

  macaca-doctor version: 1.0.21

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.7.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/jerry/Library/Android/sdk`
  Platforms is set to `/Users/jerry/Library/Android/sdk/platforms/android-24`
  Android tools is set to `/Users/jerry/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/jerry/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.38

jerry:node_modules/ $

**Comment by meowtec** [comment]
sudo 安装的问题，uiautomator-client 的 install 脚本会读环境变量，sudo 执行时没有这个环境变量。

建议不要用 sudo 安装 node 模块，默认 Node 以及模块默认安装在 `/usr/local/` 下，而这个目录是 root 用户的， 使用起来很麻烦，而且不安全。

两种解决办法：

1. 把 `/usr/local/` 目录的 owner 设为当前用户，这个方法会影响这个目录下已安装的程序，如果不熟悉不推荐使用。
2. 安装 nvm https://github.com/creationix/nvm，通过 nvm 安装 Node. 之后 Node 和全局 modules 目录都在 `~/.nvm` 下，这个目录的 owner 是当前用户，不会出现安装模块需要 sudo 权限的问题。

**Comment by niasand** [comment]
@meowtec 好的，感谢，我去改一下
