### ISSUE TITLE
app-inspector安卓真机跑淘宝客户端，浏览器无法显示客户端登录页面

### ISSUE THREAD

**Issue by SmallBlackboard** [macacajs/app-inspector#36]
淘宝客户端其他页面可以显示，但登录页无法显示
- app inspector version / 版本号:
  @1.2.12
- os version / 系统:
  win 7  64位
- device  information / 设备版本:
  android 4.4.2
- terminal log / 终端输出信息:
  $ app-inspector -u DU2MYN146D002912 --verbose
  
  > > server.js:16:12 [master] pid:3128 server start with config:
  > > { port: 5678,
  > > verbose: true,
  > > udid: 'DU2MYN146D002912',
  > > ip: '192.168.42.241',
  > > host: 'shisy',
  > > loaded_time: '2016-10-25 13:01:53' }
  > > app-inspector.js:42:10 [master] pid:3128 server start at: http://192.168.42.2                                                                                                                41:5678
  > > INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testStartServer
INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1
uiautomator start socket server.

> > socket server ready
> > socket client ready
> > Android device started: DU2MYN146D002912
> > inspector start at: http://192.168.42.241:5678
> >   <-- GET /
> > recive: {"cmd":"getSource","args":{}}

return: {"data":{"value":true,"status":0},"success":true}

> > Dump Android XML success, save to C:\Users\Administrator\AppData\Roaming\npm\                                                                                                                node_modules.app-inspector_npminstall\node_modules.1.2.12@app-inspector.temp\                                                                                                                android.json
> >   --> GET / 200
> >   <-- GET /
> > recive: {"cmd":"getSource","args":{}}

return: {"data":{"value":true,"status":0},"success":true}

> > Dump Android XML success, save to C:\Users\Administrator\AppData\Roaming\npm\                                                                                                                node_modules.app-inspector_npminstall\node_modules.1.2.12@app-inspector.temp\                                                                                                                android.json
> >   --> GET / 200
> > ![default](https://cloud.githubusercontent.com/assets/20770808/19673887/915a7312-9ab6-11e6-9c13-a3766928172d.png)

**Comment by meowtec** [comment]
这个界面不能用 adb 截图。

不要问我为什么，我也不知道。淘宝客户端的开发应该知道为什么。
