### ISSUE TITLE
您好，安装的时候提示Error: $JAVA_HOME is not set，但是全局变量都配置了

### ISSUE THREAD

**Issue by damengwang** [macacajs/app-inspector#37]
您好，安装的时候报没有配置java_home，但是doctor检测没有问题，全局环境变量也配置，但是还是一直报这个错误
JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhangshengjie/Downloads/android-sdk-macosx/`
  Platforms is set to `/Users/zhangshengjie/Downloads/android-sdk-macosx/platforms/android-24`
- os version / 系统:
  os 10.11.6
- terminal log / 终端输出信息:
  
  > uiautomator-client@1.0.28 install /usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client
  > node ./scripts/build.js

/usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:177
      throw e;
      ^

Error: $JAVA_HOME is not set
    at /usr/local/lib/node_modules/app-inspector/node_modules/java-home/lib/java-home.js:89:25

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by meowtec** [comment]
https://github.com/macacajs/app-inspector/issues/32
