### ISSUE TITLE
Mac真机连接IOS时报Internal Server Error错误看日志应该是以连接设备（用webdriveragent自带的inspector能正常显示）谢谢

### ISSUE THREAD

**Issue by wwjackli** [macacajs/app-inspector#38]
- app inspector version / 
版本号:1.2.14

- os version / 系统:
OS X EI Caption version 10.11.6
Xcode 8

- device  information / 设备版本:
Iphone 5s IOS10.0

- terminal log / 终端输出信息:

jacklis-Mac:~ jackli$ app-inspector -u 6ae3e04ce93ef5680a0cd096dace6b7e67d74748 --verbose
>> server.js:16:12 [master] pid:483 server start with config:
 { port: 5678,
  verbose: true,
  udid: '6ae3e04ce93ef5680a0cd096dace6b7e67d74748',
  ip: '192.168.219.108',
  host: 'jacklis-Mac.local',
  loaded_time: '2016-11-04 20:00:06' }
>> app-inspector.js:42:10 [master] pid:483 server start at: http://192.168.219.108:5678
>> xctest-client.js:43:14 [master] pid:483 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:183:12 [master] pid:483 xcode version: 8.1
>> WebDriverAgent version: 1.0.28
>> xctest-client.js:156:14 [master] pid:483 2016-11-04 20:00:11.497 xcodebuild[487:6655]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/jackli/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/5AADB4BB-89CC-4454-B227-51949C9AB25C/Session-WebDriverAgentRunner-2016-11-04_200011-pl0sBe.log

>> xctest-client.js:156:14 [master] pid:483 2016-11-04 20:00:11.499 xcodebuild[487:6644] [MT] IDETestOperationsObserverDebug: (3FEDBF41-3245-49C2-840D-2DE8DFF9B30D) Beginning test session WebDriverAgentRunner-3FEDBF41-3245-49C2-840D-2DE8DFF9B30D at 2016-11-04 20:00:11.496 with Xcode 8B62 on target <DVTiOSDevice: 0x7ff11ae440d0> {
		deviceSerialNumber:         C36MQZWWFRC6
		identifier:                 6ae3e04ce93ef5680a0cd096dace6b7e67d74748
		deviceClass:                iPhone
		deviceName:                 5s
		deviceIdentifier:           6ae3e04ce93ef5680a0cd096dace6b7e67d74748
		productVersion:             10.0.2
		buildVersion:               14A456
		deviceSoftwareVersion:      10.0.2 (14A456)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12263628800
		deviceAvailableCapacity:    9966419968
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7ff118575ac0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.0.2 (14A456))

>> xctest-client.js:156:14 [master] pid:483 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/135b0fa5d8cadb8331b7178610951022/6ae3e04ce93ef5680a0cd096dace6b7e67d74748/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/jackli/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dW8kfW/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dW8kfW/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:156:14 [master] pid:483 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dW8kfW/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:156:14 [master] pid:483 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/z3/dv8jp6ks63540gr1b6styz9m0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.dW8kfW/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> proxy.js:54:14 [master] pid:483 Proxy: /session:POST to http://192.168.219.102:8100/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:67:16 [master] pid:483 Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":null,"status":13}
>> iOS device started: 6ae3e04ce93ef5680a0cd096dace6b7e67d74748
>> inspector start at: http://192.168.219.108:5678
  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 20}, {320, 436}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{-960, 20}, {0, 0}}","rect":{"y":20,"x":-960,"width":0,"height":0},"value":null,"label":null,"type":"ScrollView","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{-960, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{-960, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{-960, 0}, {320, 568}}","rect":{"y":0,"x":-960,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":-960,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":-960,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{-640, 20}, {320, 436}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{-626, 25}, {64, 86}}","rect":{"y":25,"x":-626,"width":64,"height":86},"value":null,"label":"Messages","type":"Icon","name":"Messages","rawIdentifier":"Messages"},{"isEnabled":"1","isVisible":"0","frame":"{{-550, 25}, {64, 86}}","rect":{"y":25,"x":-550,"width":64,"height":86},"value":"Friday, 04 November","label":"Calendar","type":"Icon","name":"Calendar","rawIdentifier":"Calendar"},{"isEnabled":"1","isVisible":"0","frame":"{{-474, 25}, {64, 86}}","rect":{"y":25,"x":-474,"width":64,"height":86},"value":null,"label":"Photos","type":"Icon","name":"Photos","rawIdentifier":"Photos"},{"isEnabled":"1","isVisible":"0","frame":"{{-398, 25}, {64, 86}}","rect":{"y":25,"x":-398,"width":64,"height":86},"value":null,"label":"Camera","type":"Icon","name":"Camera","rawIdentifier":"Camera"},{"isEnabled":"1","isVisible":"0","frame":"{{-626, 113}, {64, 86}}","rect":{"y":113,"x":-626,"width":64,"height":86},"value":null,"label":"Weather","type":"Icon","name":"Weather","rawIdentifier":"Weather"},{"isEnabled":"1","isVisible":"0","frame":"{{-550, 113}, {64, 86}}","rect":{"y":113,"x":-550,"width":64,"height":86},"value":"8:01 PM","label":"Clock","type":"Icon","name":"Clock","rawIdentifier":"Clock"},{"isEnabled":"1","isVisible":"0","frame":"{{-474, 113}, {64, 86}}","rect":{"y":113,"x":-474,"width":64,"height":86},"value":null,"label":"Maps","type":"Icon","name":"Maps","rawIdentifier":"Maps"},{"isEnabled":"1","isVisible":"0","frame":"{{-398, 113}, {64, 86}}","rect":{"y":113,"x":-398,"width":64,"height":86},"value":null,"label":"Videos","type":"Icon","name":"Videos","rawIdentifier":"Videos"},{"isEnabled":"1","isVisible":"0","frame":"{{-626, 201}, {64, 86}}","rect":{"y":201,"x":-626,"width":64,"height":86},"value":null,"label":"Wallet","type":"Icon","name":"Wallet","rawIdentifier":"Wallet"},{"isEnabled":"1","isVisible":"0","frame":"{{-552, 201}, {69, 86}}","rect":{"y":201,"x":-552,"width":69,"height":86},"value":null,"label":"Notes","type":"Icon","name":"Notes","rawIdentifier":"Notes"},{"isEnabled":"1","isVisible":"0","frame":"{{-474, 201}, {64, 86}}","rect":{"y":201,"x":-474,"width":64,"height":86},"value":null,"label":"Reminders","type":"Icon","name":"Reminders","rawIdentifier":"Reminders"},{"isEnabled":"1","isVisible":"0","frame":"{{-406, 201}, {80, 86}}","rect":{"y":201,"x":-406,"width":80,"height":86},"value":null,"label":"Stocks","type":"Icon","name":"Stocks","rawIdentifier":"Stocks"},{"isEnabled":"1","isVisible":"0","frame":"{{-627, 289}, {66, 86}}","rect":{"y":289,"x":-627,"width":66,"height":86},"value":null,"label":"iTunes Store","type":"Icon","name":"iTunes Store","rawIdentifier":"iTunes Store"},{"isEnabled":"1","isVisible":"0","frame":"{{-550, 289}, {64, 86}}","rect":{"y":289,"x":-550,"width":64,"height":86},"value":null,"label":"App Store","type":"Icon","name":"App Store","rawIdentifier":"App Store"},{"isEnabled":"1","isVisible":"0","frame":"{{-474, 289}, {64, 86}}","rect":{"y":289,"x":-474,"width":64,"height":86},"value":null,"label":"iBooks","type":"Icon","name":"iBooks","rawIdentifier":"iBooks"},{"isEnabled":"1","isVisible":"0","frame":"{{-398, 289}, {64, 86}}","rect":{"y":289,"x":-398,"width":64,"height":86},"value":null,"label":"Health","type":"Icon","name":"Health","rawIdentifier":"Health"},{"isEnabled":"1","isVisible":"0","frame":"{{-626, 377}, {64, 78}}","rect":{"y":377,"x":-626,"width":64,"height":78},"value":null,"label":"Home","type":"Icon","name":"Home","rawIdentifier":"Home"},{"isEnabled":"1","isVisible":"0","frame":"{{-550, 367}, {74, 96}}","rect":{"y":367,"x":-550,"width":74,"height":96},"value":"1 new item","label":"Settings","type":"Icon","name":"Settings","rawIdentifier":"Settings"},{"isEnabled":"1","isVisible":"0","frame":"{{-474, 377}, {64, 78}}","rect":{"y":377,"x":-474,"width":64,"height":78},"value":null,"label":"Chrome","type":"Icon","name":"Chrome","rawIdentifier":"Chrome"},{"isEnabled":"1","isVisible":"0","frame":"{{-398, 377}, {64, 86}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {0, 0}}","rect":{"y":0,"x":0,"width":0,"height":0},"value":null,"label":"Compass","type":"Other","name":"Compass","rawIdentifier":"Compass"},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {0, 0}}","rect":{"y":0,"x":0,"width":0,"height":0},"value":null,"label":"Find My iPhone","type":"Other","name":"Find iPhone","rawIdentifier":"Find iPhone"},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {0, 0}}","rect":{"y":0,"x":0,"width":0,"height":0},"value":null,"label":"Tips","type":"Other","name":"Tips","rawIdentifier":"Tips"},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {0, 0}}","rect":{"y":0,"x":0,"width":0,"height":0},"value":null,"label":"Contacts","type":"Other","name":"Contacts","rawIdentifier":"Contacts"},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {0, 0}}","rect":{"y":0,"x":0,"width":0,"height":0},"value":null,"label":"Voice Memos","type":"Other","name":"Voice Memos","rawIdentifier":"Voice Memos"}],"rect":{"y":377,"x":-398,"width":64,"height":86},"value":"5 apps","label":"Extras folder","type":"Icon","name":"Extras","rawIdentifier":"Extras"}],"rect":{"y":20,"x":-640,"width":320,"height":436},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{-320, 20}, {320, 436}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{-306, 25}, {64, 86}}","rect":{"y":25,"x":-306,"width":64,"height":86},"value":null,"label":"FaceTime","type":"Icon","name":"FaceTime","rawIdentifier":"FaceTime"},{"isEnabled":"1","isVisible":"0","frame":"{{-231, 25}, {67, 86}}","rect":{"y":25,"x":-231,"width":67,"height":86},"value":null,"label":"Calculator","type":"Icon","name":"Calculator","rawIdentifier":"Calculator"},{"isEnabled":"1","isVisible":"0","frame":"{{-154, 25}, {64, 86}}","rect":{"y":25,"x":-154,"width":64,"height":86},"value":null,"label":"Podcasts","type":"Icon","name":"Podcasts","rawIdentifier":"Podcasts"},{"isEnabled":"1","isVisible":"0","frame":"{{-78, 25}, {64, 86}}","rect":{"y":25,"x":-78,"width":64,"height":86},"value":null,"label":"Watch","type":"Icon","name":"Watch","rawIdentifier":"Watch"},{"isEnabled":"1","isVisible":"0","frame":"{{-309, 113}, {71, 86}}","rect":{"y":113,"x":-309,"width":71,"height":86},"value":null,"label":"乐天免税店","type":"Icon","name":"乐天免税店","rawIdentifier":"乐天免税店"},{"isEnabled":"1","isVisible":"0","frame":"{{-230, 113}, {64, 86}}","rect":{"y":113,"x":-230,"width":64,"height":86},"value":null,"label":"WeChat","type":"Icon","name":"WeChat","rawIdentifier":"WeChat"},{"isEnabled":"1","isVisible":"0","frame":"{{-163, 113}, {83, 86}}","rect":{"y":113,"x":-163,"width":83,"height":86},"value":null,"label":"乐天釜山免税店","type":"Icon","name":"乐天釜山免税店","rawIdentifier":"乐天釜山免税店"},{"isEnabled":"1","isVisible":"0","frame":"{{-78, 113}, {64, 86}}","rect":{"y":113,"x":-78,"width":64,"height":86},"value":null,"label":"Alipay","type":"Icon","name":"Alipay","rawIdentifier":"Alipay"},{"isEnabled":"1","isVisible":"0","frame":"{{-315, 201}, {83, 86}}","rect":{"y":201,"x":-315,"width":83,"height":86},"value":null,"label":"安全支付助手","type":"Icon","name":"安全支付助手","rawIdentifier":"安全支付助手"},{"isEnabled":"1","isVisible":"0","frame":"{{-230, 201}, {64, 86}}","rect":{"y":201,"x":-230,"width":64,"height":86},"value":null,"label":"롯데면세점","type":"Icon","name":"롯데면세점","rawIdentifier":"롯데면세점"}],"rect":{"y":20,"x":-320,"width":320,"height":436},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 20}, {320, 436}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{7, 25}, {78, 86}}","rect":{"y":25,"x":7,"width":78,"height":86},"value":null,"label":"WebDriverAgentRunner","type":"Icon","name":"WebDriverAgentRunner","rawIdentifier":"WebDriverAgentRunner"}],"rect":{"y":20,"x":0,"width":320,"height":436},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":20,"x":0,"width":320,"height":436},"value":null,"label":null,"type":"ScrollView","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 445}, {320, 43}}","rect":{"y":445,"x":0,"width":320,"height":43},"value":"Page 4 of 4","label":null,"type":"PageIndicator","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 472}, {320, 96}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 471}, {320, 3}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 471}, {320, 3}}","rect":{"y":471,"x":0,"width":320,"height":3},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":471,"x":0,"width":320,"height":3},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 472}, {320, 96}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{14, 484}, {64, 86}}","rect":{"y":484,"x":14,"width":64,"height":86},"value":null,"label":"Phone","type":"Icon","name":"Phone","rawIdentifier":"Phone"},{"isEnabled":"1","isVisible":"1","frame":"{{90, 484}, {64, 86}}","rect":{"y":484,"x":90,"width":64,"height":86},"value":null,"label":"Safari","type":"Icon","name":"Safari","rawIdentifier":"Safari"},{"isEnabled":"1","isVisible":"1","frame":"{{166, 484}, {64, 86}}","rect":{"y":484,"x":166,"width":64,"height":86},"value":"No unread e-mails","label":"Mail","type":"Icon","name":"Mail","rawIdentifier":"Mail"},{"isEnabled":"1","isVisible":"1","frame":"{{242, 484}, {64, 86}}","rect":{"y":484,"x":242,"width":64,"height":86},"value":null,"label":"Music","type":"Icon","name":"Music","rawIdentifier":"Music"}],"rect":{"y":472,"x":0,"width":320,"height":96},"value":null,"label":"Dock","type":"Other","name":"Dock","rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 472}, {320, 126}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 472}, {320, 568}}","rect":{"y":472,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":472,"x":0,"width":320,"height":126},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":472,"x":0,"width":320,"height":96},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {640, 1136}}","rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":640,"height":1136},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 20}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 20}}","rect":{"y":0,"x":0,"width":320,"height":20},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{0, 0}, {320, 20}}","children":[{"isEnabled":"1","isVisible":"1","frame":"{{6, 0}, {35, 20}}","rect":{"y":0,"x":6,"width":35,"height":20},"value":null,"label":"4 of 5 bars, signal strength","type":"Other","name":"4 of 5 bars, signal strength","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{44, 0}, {16, 20}}","rect":{"y":0,"x":44,"width":16,"height":20},"value":null,"label":"KT network","type":"Other","name":"KT network","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{65, 0}, {13, 20}}","rect":{"y":0,"x":65,"width":13,"height":20},"value":"SSID","label":"3 of 3 Wi-Fi bars","type":"Other","name":"3 of 3 Wi-Fi bars","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{138, 0}, {48, 20}}","rect":{"y":0,"x":138,"width":48,"height":20},"value":null,"label":"8:01 PM","type":"Other","name":"8:01 PM","rawIdentifier":null},{"isEnabled":"1","isVisible":"1","frame":"{{282, 0}, {33, 20}}","rect":{"y":0,"x":282,"width":33,"height":20},"value":null,"label":"96% battery power, Charging","type":"Other","name":"96% battery power, Charging","rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":20},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":20},"value":null,"label":null,"type":"StatusBar","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","children":[{"isEnabled":"1","isVisible":"0","frame":"{{0, 0}, {320, 568}}","rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":320,"height":568},"value":null,"label":" ","type":"Application","name":" ","rawIdentifier":null}},"sessionId":"BADEC7F1-1FC6-4C82-A713-4C2907A77620","status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'x' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:16)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by xudafeng** [comment]
升级iOS驱动，参考 https://testerhome.com/topics/6314
