### ISSUE TITLE
iOS simulator screenshot does not refresh

### ISSUE THREAD

**Issue by sepiol** [macacajs/app-inspector#41]
After the app-inspector starts correctly (using the command "app-inspector -u XXXX-XXXX-XXXX-XXXX") i can see the main screen but after going into an application in the simulator, i try to refresh the app-inspector server but it times out. Any thoughts on this?

**Comment by meowtec** [comment]
Please use issue template: https://github.com/macacajs/app-inspector/blob/master/issue_template.md
