### ISSUE TITLE
如何生成xpath文件的？

### ISSUE THREAD

**Issue by wangtao169447** [macacajs/app-inspector#46]
1.想了解一下生成xpath的原理

**Comment by meowtec** [comment]
xml 还是 xpath？一个是文档格式，一个是节点查询语句

**Comment by wangtao169447** [comment]
想了解两点：
1.如果获取当前window的元素结构的xml文件。即类似于getPageSource方法
2.获取到页面结构的xml文件后，如何生成各个元素的xpath值

谢谢！

**Comment by meowtec** [comment]
https://github.com/macacajs/app-inspector/blob/f0be888f1f13e646c29306670d30aa38d2d90f63/lib/android.js#L15

https://github.com/macacajs/app-inspector/blob/a5b1ff27dd308911e929546ed8a45ad0e8cd9484/lib/ios.js#L51

你看看源码吧。
你可能还需要了解下 uiautomator-client uiautomator xctest webdriveragent

生成 xpath 是遍历 xml 树，拿到根节点到目标节点的路径，然后拼接，比较粗糙。

**Comment by wangtao169447** [comment]
好的，谢了。
@meowtec
