### ISSUE TITLE
Internal Server Error on http://192.168.1.58:5683/

### ISSUE THREAD

**Issue by RaviBadugu** [macacajs/app-inspector#49]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号: macaca-cli@1.1.20

- os version / 系统: 9.3

- device  information / 设备版本: iPhone 6S 9.3

- terminal log / 终端输出信息:

****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {0, 0}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{-2, 5}, {64, 78}}","isEnabled":"1","isVisible":"0","rect":{"y":5,"x":-2,"width":64,"height":78},"value":null,"label":null,"type":"Icon","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":0,"height":0},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 20}, {375, 535}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{-750, 20}, {0, 0}}","isEnabled":"1","isVisible":"0","rect":{"y":20,"x":-750,"width":0,"height":0},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{-375, 20}, {375, 535}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{-350, 26}, {64, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":26,"x":-350,"width":64,"height":85.5},"value":"Monday, December 19","label":"Calendar","type":"Icon","name":"Calendar","rawIdentifier":"Calendar"},{"bounds":"{{-263, 26}, {64, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":26,"x":-263,"width":64,"height":85.5},"value":null,"label":"Photos","type":"Icon","name":"Photos","rawIdentifier":"Photos"},{"bounds":"{{-176, 26}, {64, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":26,"x":-176,"width":64,"height":85.5},"value":null,"label":"Maps","type":"Icon","name":"Maps","rawIdentifier":"Maps"},{"bounds":"{{-89, 26}, {64, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":26,"x":-89,"width":64,"height":85.5},"value":null,"label":"Wallet","type":"Icon","name":"Wallet","rawIdentifier":"Wallet"},{"bounds":"{{-351.5, 114}, {68, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":114,"x":-351.5,"width":68,"height":85.5},"value":null,"label":"Reminders","type":"Icon","name":"Reminders","rawIdentifier":"Reminders"},{"bounds":"{{-263, 114}, {64, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":114,"x":-263,"width":64,"height":85.5},"value":null,"label":"News","type":"Icon","name":"News","rawIdentifier":"News"},{"bounds":"{{-176, 114}, {64, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":114,"x":-176,"width":64,"height":85.5},"value":null,"label":"Health","type":"Icon","name":"Health","rawIdentifier":"Health"},{"bounds":"{{-89, 114}, {64, 85.5}}","isEnabled":"1","isVisible":"0","rect":{"y":114,"x":-89,"width":64,"height":85.5},"value":null,"label":"Settings","type":"Icon","name":"Settings","rawIdentifier":"Settings"}],"rect":{"y":20,"x":-375,"width":375,"height":535},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 20}, {375, 535}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{15.5, 26}, {83, 85.5}}","isEnabled":"1","isVisible":"1","rect":{"y":26,"x":15.5,"width":83,"height":85.5},"value":null,"label":"Game Center","type":"Icon","name":"Game Center","rawIdentifier":"Game Center"},{"bounds":"{{112, 26}, {64, 85.5}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {0, 0}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":0,"height":0},"value":null,"label":"Contacts","type":"Other","name":"Contacts","rawIdentifier":"Contacts"}],"rect":{"y":26,"x":112,"width":64,"height":85.5},"value":"1 app","label":"Extras folder","type":"Icon","name":"Extras","rawIdentifier":"Extras"},{"bounds":"{{199, 26}, {64, 85.5}}","isEnabled":"1","isVisible":"1","rect":{"y":26,"x":199,"width":64,"height":85.5},"value":null,"label":"Watch","type":"Icon","name":"Watch","rawIdentifier":"Watch"},{"bounds":"{{279.5, 26}, {77, 85.5}}","isEnabled":"1","isVisible":"1","rect":{"y":26,"x":279.5,"width":77,"height":85.5},"value":null,"label":"WebDriverAgentRunner","type":"Icon","name":"WebDriverAgentRunner","rawIdentifier":"WebDriverAgentRunner"},{"bounds":"{{22.5, 114}, {70, 85.5}}","isEnabled":"1","isVisible":"1","rect":{"y":114,"x":22.5,"width":70,"height":85.5},"value":null,"label":"Health Lab","type":"Icon","name":"Health Lab","rawIdentifier":"Health Lab"}],"rect":{"y":20,"x":0,"width":375,"height":535},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{-375, 20}, {375, 535}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{-372, 549.5}, {369, 2.5}}","isEnabled":"1","isVisible":"0","rect":{"y":549.5,"x":-372,"width":369,"height":2.5},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":20,"x":-375,"width":375,"height":535},"value":null,"label":null,"type":"ScrollView","name":null,"rawIdentifier":null}],"rect":{"y":20,"x":0,"width":375,"height":535},"value":null,"label":null,"type":"ScrollView","name":null,"rawIdentifier":null},{"bounds":"{{0, 545}, {375, 42}}","isEnabled":"1","isVisible":"1","rect":{"y":545,"x":0,"width":375,"height":42},"value":"Page 2 of 2","label":null,"type":"PageIndicator","name":null,"rawIdentifier":null},{"bounds":"{{0, 571}, {375, 96}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 570}, {375, 2.5}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 570}, {375, 2.5}}","isEnabled":"1","isVisible":"1","rect":{"y":570,"x":0,"width":375,"height":2.5},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":570,"x":0,"width":375,"height":2.5},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 571}, {375, 96}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{155, 583}, {64, 85.5}}","isEnabled":"1","isVisible":"1","rect":{"y":583,"x":155,"width":64,"height":85.5},"value":null,"label":"Safari","type":"Icon","name":"Safari","rawIdentifier":"Safari"}],"rect":{"y":571,"x":0,"width":375,"height":96},"value":null,"label":"Dock","type":"Other","name":"Dock","rawIdentifier":null},{"bounds":"{{0, 571}, {375, 126}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 571}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 571}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{-0.21856287425148935, 571}, {375.43712574850292, 667}}","isEnabled":"1","isVisible":"0","rect":{"y":571,"x":-0.2185628742514893,"width":375.4371257485029,"height":667},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":571,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":571,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":571,"x":0,"width":375,"height":126},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":571,"x":0,"width":375,"height":96},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":"Dismiss Spotlight","type":"Button","name":"Dismiss Spotlight","rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 20}, {375, 44}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 64}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":375,"height":64},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{8, 27.5}, {359, 29}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{16, 27.5}, {343, 29}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{16, 27.5}, {343, 29}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{335, 32.5}, {19, 19}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{337.5, 35}, {14, 14}}","isEnabled":"1","isVisible":"0","rect":{"y":35,"x":337.5,"width":14,"height":14},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":32.5,"x":335,"width":19,"height":19},"value":null,"label":"Clear text","type":"Button","name":"Clear text","rawIdentifier":null}],"rect":{"y":27.5,"x":16,"width":343,"height":29},"value":null,"label":null,"type":"SearchField","name":null,"rawIdentifier":null}],"rect":{"y":27.5,"x":16,"width":343,"height":29},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{371, 27.5}, {53, 30}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{371, 32}, {53, 20.5}}","isEnabled":"1","isVisible":"0","rect":{"y":32,"x":371,"width":53,"height":20.5},"value":"Cancel","label":"Cancel","type":"StaticText","name":"Cancel","rawIdentifier":null}],"rect":{"y":27.5,"x":371,"width":53,"height":30},"value":null,"label":"Cancel","type":"Button","name":"Cancel","rawIdentifier":null}],"rect":{"y":27.5,"x":8,"width":359,"height":29},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{8, 31.5}, {21, 21}}","isEnabled":"1","isVisible":"0","rect":{"y":31.5,"x":8,"width":21,"height":21},"value":null,"label":"Back","type":"Button","name":"Back","rawIdentifier":null}],"rect":{"y":20,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"NavigationBar","name":"SPUISearchView","rawIdentifier":"SPUISearchView"},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 64}, {375, 603}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 64}, {375, 0.5}}","isEnabled":"1","isVisible":"0","rect":{"y":64,"x":0,"width":375,"height":0.5},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 64}, {375, 44}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 64}, {375, 44}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 64}, {375, 44}}","isEnabled":"1","isVisible":"0","rect":{"y":64,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 64}, {375, 44}}","isEnabled":"1","isVisible":"0","rect":{"y":64,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 64}, {375, 44}}","isEnabled":"1","isVisible":"0","rect":{"y":64,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":64,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":64,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":64,"x":0,"width":375,"height":603},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 667}, {375, 44}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 666.5}, {375, 0.5}}","isEnabled":"1","isVisible":"0","rect":{"y":666.5,"x":0,"width":375,"height":0.5},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null},{"bounds":"{{0, 667}, {375, 44}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 667}, {375, 44}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 667}, {375, 44}}","isEnabled":"1","isVisible":"0","rect":{"y":667,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 667}, {375, 44}}","isEnabled":"1","isVisible":"0","rect":{"y":667,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":667,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":667,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Image","name":null,"rawIdentifier":null}],"rect":{"y":667,"x":0,"width":375,"height":44},"value":null,"label":null,"type":"Toolbar","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {750, 1334}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":750,"height":1334},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"0","children":[{"bounds":"{{0, 667}, {375, 0}}","isEnabled":"1","isVisible":"0","rect":{"y":667,"x":0,"width":375,"height":0},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 667}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {375, 20}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{0, 0}, {375, 20}}","isEnabled":"1","isVisible":"0","rect":{"y":0,"x":0,"width":375,"height":20},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{0, 0}, {375, 20}}","isEnabled":"1","isVisible":"1","children":[{"bounds":"{{6, 0}, {39, 20}}","isEnabled":"1","isVisible":"1","rect":{"y":0,"x":6,"width":39,"height":20},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null},{"bounds":"{{50, 0}, {13, 20}}","isEnabled":"1","isVisible":"1","rect":{"y":0,"x":50,"width":13,"height":20},"value":"SSID","label":"3 of 3 Wi-Fi bars","type":"Other","name":"3 of 3 Wi-Fi bars","rawIdentifier":null},{"bounds":"{{165, 0}, {48, 20}}","isEnabled":"1","isVisible":"1","rect":{"y":0,"x":165,"width":48,"height":20},"value":null,"label":"5:18 PM","type":"Other","name":"5:18 PM","rawIdentifier":null},{"bounds":"{{345, 0}, {25, 20}}","isEnabled":"1","isVisible":"1","rect":{"y":0,"x":345,"width":25,"height":20},"value":null,"label":"-100% battery power","type":"Other","name":"-100% battery power","rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":20},"value":null,"label":null,"type":"Other","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":20},"value":null,"label":null,"type":"StatusBar","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":null,"type":"Window","name":null,"rawIdentifier":null}],"rect":{"y":0,"x":0,"width":375,"height":667},"value":null,"label":" ","type":"Application","name":" ","rawIdentifier":null}},"sessionId":null,"status":0}
    '****** xctest source end *******

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by zenzhu** [comment]
应该修复了，更新一下 app-inspector。
