### ISSUE TITLE
It show the loading layout all the time.

### ISSUE THREAD

**Issue by aheadlcx** [macacajs/app-inspector#5]
mac 10.11.4 , Android , Nexus 6 .
Following log:
$ app-inspector -u ZY222Z7BMV --verbose                                                                                                                                                         [15:38:23]

****************************************
*  version 1.0.9 is outdate            *
*  run: npm i -g app-inspector@1.0.11  *
****************************************

>> server.js:28:12 [master] pid:62991 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'ZY222Z7BMV',
  ip: '10.0.92.226',
  host: 'appledeMacBook-Pro.local',
  loaded_time: '2016-08-08 15:38:38' }
>> inspector start at: http://10.0.92.226:5678
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200

**Comment by xudafeng** [comment]
npm i -g app-inspector@1.0.11

**Comment by codeskyblue** [comment]
我的的也是1.0.11不过也遇到了这个问题。

我先找到模拟器的udid

```
$ instruments -s devices
Known Devices:
qard2-macmini [C0747BBB-2373-5D4B-ADE9-FF0C4112B9F2]
Apple TV 1080p (9.2) [3B786140-4AEC-4BF8-BADA-ACD1206E3CCF] (Simulator)
iPad 2 (9.3) [4BC8321E-27FD-4E43-84E5-28A969616254] (Simulator)
iPad Air (9.3) [0566C0BD-9D14-4C83-B7D6-68814A3CF466] (Simulator)
iPad Air 2 (9.3) [D59CE504-D8D4-40D7-9E8F-7F977D1BBDB8] (Simulator)
iPad Pro (9.3) [26BF8D4B-EE87-4BF3-865F-78DF19D010A6] (Simulator)
iPad Retina (9.3) [322E7F5F-F2B2-480C-BE8B-3CB994416E1F] (Simulator)
iPhone 4s (9.3) [43882047-EB27-496D-ACB9-FA6FBB7538E7] (Simulator)
iPhone 5 (9.3) [36ED532C-1507-42DC-8ED5-45402C7FD5AB] (Simulator)
iPhone 5s (9.3) [7CC7ED67-5E3F-4A88-B19B-336B916A967E] (Simulator)
iPhone 6 (9.3) [1F77A1C8-7376-411E-82A8-0AF62BB2827C] (Simulator)
iPhone 6 Plus (9.3) [12E0EB48-8E58-4A94-AC17-209A99568C9B] (Simulator)
iPhone 6s (9.3) [A9D71F86-B151-474E-85B4-D1804CFC8279] (Simulator)
iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [24C2FA78-C1DB-4019-8856-853D89C375F3] (Simulator)
iPhone 6s Plus (9.3) [A4E79EDD-1A29-47B3-96AA-1B5FE20B5071] (Simulator)
iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [9984258D-390A-475A-BCDB-00EB04770B50] (Simulator)
```

然后运行

```
$ app-inspector -u 7CC7ED67-5E3F-4A88-B19B-336B916A967E --verbose
>> server.js:28:12 [master] pid:52089 server start with config:
 { port: 5678,
  verbose: true,
  udid: '7CC7ED67-5E3F-4A88-B19B-336B916A967E',
  ip: '10.240.187.174',
  host: 'QARD2deMac-mini.local',
  loaded_time: '2016-08-09 13:44:25' }
>> inspector start at: http://10.240.187.174:5678
>> xctest-client.js:43:14 [master] pid:52089 project path: /Users/qard2/.nvm/versions/node/v5.1.1/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:182:12 [master] pid:52089 xcode version: 7.3.1
>> xctest-client.js:155:14 [master] pid:52089 2016-08-09 13:44:27.466 xcodebuild[52093:4364883] [MT] IDETestOperationsObserverDebug: (A5EDE194-70AF-4735-A247-35F69A5631FB) Beginning test session A5EDE194-70AF-4735-A247-35F69A5631FB with Xcode 7D1014 on target <DVTiPhoneSimulator: 0x7fe233811660> {
		SimDevice: SimDevice : iPhone 5s (7CC7ED67-5E3F-4A88-B19B-336B916A967E) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 9.3 (13E230) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 }
} (9.3 (13E230))

>> xctest-client.js:155:14 [master] pid:52089 2016-08-09 13:44:27.487 xcodebuild[52093:4364886]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/qard2/Library/Developer/Xcode/DerivedData/WebDriverAgent-dwffamgnjypjqlalrgzibuqphihx/Logs/Test/406ECE91-255B-4CC5-875C-51C5F428EB6C/Session-2016-08-09_13:44:27-QJZ17v.log

  <-- GET /
  --> GET / 200
```

结果打开浏览器就什么也没看到

![image](https://cloud.githubusercontent.com/assets/3281689/17505959/7de442e2-5e37-11e6-9939-22f1ae0cb27f.png)

**Comment by dvan001** [comment]
>> inspector start at: http://192.168.56.147:5678
>> xctest-client.js:43:14 [master] pid:51780 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:182:12 [master] pid:51780 xcode version: 7.3.1
>> xctest-client.js:155:14 [master] pid:51780 2016-08-09 18:08:09.272 xcodebuild[51784:6314479] [MT] IDETestOperationsObserverDebug: (C7783F3F-BFAE-471D-9E73-486AAB7016A5) Beginning test session C7783F3F-BFAE-471D-9E73-486AAB7016A5 with Xcode 7D1014 on target <DVTiPhoneSimulator: 0x7fe70851fef0> {
		SimDevice: SimDevice : iPhone 5s (811D6064-BF16-47AA-85B6-4A39E00FD2DE) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 9.3 (13E230) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 }
} (9.3 (13E230))

>> xctest-client.js:155:14 [master] pid:51780 2016-08-09 18:08:09.273 xcodebuild[51784:6314483]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/gao_zj/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/AE8EF775-0882-4054-9CB6-C57D08A6A706/Session-2016-08-09_18:08:09-fYSWPx.log

>> xctest-client.js:155:14 [master] pid:51780 
Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

>> xctest-client.js:155:14 [master] pid:51780 ** TEST FAILED **


>> xctest-client.js:163:14 [master] pid:51780 xctest client exit with code: 65, signal: null
这个问题我也遇到了，xctest报错了

**Comment by meowtec** [comment]
@codeskyblue 多等一会呢？

**Comment by meowtec** [comment]
更新到最新版本。

如果 检测到 simulator 启动，会 log 出下面的文字：

```
iOS device started: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
```
