### ISSUE TITLE
[请教一下] 获取出来的控件信息和截屏怎么对应的

### ISSUE THREAD

**Issue by Carlgege** [macacajs/app-inspector#58]
你好，
我使用uiautomatorviewer拉取了控件树，但是控件的坐标和截图不能对应起来，所以想请教一下macaca是怎么做的，感谢!

https://testerhome.com/topics/7404

**Comment by xudafeng** [comment]
@Carlgege https://github.com/macacajs/XCTestWD#3-element-types
