### ISSUE TITLE
uiautomator-client.js:31:12 [master] pid:244 uiautomator-bootstrap was not found in: C:\Users\tantao\AppData\Roaming\npm\node_modules\app-inspector\node_modules\._uiautomator-client@1.1.9@uiautomator-client\bin\uiautomator-bootstrap.jar

### ISSUE THREAD

**Issue by Cainiaotao** [macacajs/app-inspector#71]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
update to latest version
