### ISSUE TITLE
app-inspector刷新页面后报错，Internal Server Error

### ISSUE THREAD

**Issue by lmlucky** [macacajs/app-inspector#76]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:
1.2.23

- os version / 系统:
Mac OS Sierra 10.12.4

- device  information / 设备版本:
iOS 10.2.1

- terminal log / 终端输出信息:

```
****** xctest source start *******
    {"value":"*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]\n\n(\n\t0   CoreFoundation                      0x00000001907611d0 <redacted> + 148\n\t1   libobjc.A.dylib                     0x000000018f19855c objc_exception_throw + 56\n\t2   CoreFoundation                      0x000000019063f870 <redacted> + 312\n\t3   CoreFoundation                      0x000000019064b5fc <redacted> + 52\n\t4   XCTest                              0x00000001001eb6bc -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 152\n\t5   XCTest                              0x00000001001ebad4 -[XCElementSnapshot(Hitpoint) hitPoint] + 392\n\t6   WebDriverAgentLib                   0x0000000101cd7240 -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 576\n\t7   WebDriverAgentLib                   0x0000000101ce2654 -[XCElementSnapshot(WebDriverAttributes) isWDVisible] + 40\n\t8   WebDriverAgentLib                   0x0000000101cd4298 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 1692\n\t9   WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t10  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t11  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t12  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t13  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t14  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t15  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t16  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t17  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t18  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t19  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t20  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t21  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t22  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t23  WebDriverAgentLib                   0x0000000101cd44ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t24  WebDriverAgentLib                   0x0000000101cd3b48 -[XCUIApplication(FBHelpers) fb_tree] + 100\n\t25  WebDriverAgentLib                   0x0000000101ce3f64 +[FBDebugCommands handleGetSourceCommand:] + 360\n\t26  WebDriverAgentLib                   0x0000000101cd982c -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t27  WebDriverAgentLib                   0x0000000101cd15b4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t28  RoutingHTTPServer                   0x0000000101d763cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t29  RoutingHTTPServer                   0x0000000101d76b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t30  libdispatch.dylib                   0x000000018f5ea1bc <redacted> + 16\n\t31  libdispatch.dylib                   0x000000018f5fb084 <redacted> + 320\n\t32  libdispatch.dylib                   0x000000018f5ea1bc <redacted> + 16\n\t33  libdispatch.dylib                   0x000000018f5eed68 _dispatch_main_queue_callback_4CF + 1000\n\t34  CoreFoundation                      0x000000019070e810 <redacted> + 12\n\t35  CoreFoundation                      0x000000019070c3fc <redacted> + 1660\n\t36  CoreFoundation                      0x000000019063a2b8 CFRunLoopRunSpecific + 444\n\t37  Foundation                          0x000000019117726c <redacted> + 304\n\t38  Foundation                          0x00000001911cbaa0 <redacted> + 88\n\t39  WebDriverAgentLib                   0x0000000101cd0704 -[FBWebServer startServing] + 260\n\t40  WebDriverAgentRunner                0x00000001007ebed0 -[UITestingUITests testRunner] + 120\n\t41  CoreFoundation                      0x0000000190767150 <redacted> + 144\n\t42  CoreFoundation                      0x0000000190659eac <redacted> + 284\n\t43  XCTest                              0x00000001001a4a30 __24-[XCTestCase invokeTest]_block_invoke.237 + 48\n\t44  XCTest                              0x00000001001a467c __24-[XCTestCase invokeTest]_block_invoke_2 + 564\n\t45  XCTest                              0x00000001001dfdac -[XCTestContext performInScope:] + 208\n\t46  XCTest                              0x00000001001a4430 -[XCTestCase invokeTest] + 268\n\t47  XCTest                              0x00000001001a4d80 -[XCTestCase performTest:] + 536\n\t48  XCTest                              0x00000001001a1f44 __27-[XCTestSuite performTest:]_block_invoke + 240\n\t49  XCTest                              0x00000001001a1b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t50  XCTest                              0x00000001001a1d54 -[XCTestSuite performTest:] + 200\n\t51  XCTest                              0x00000001001a1f44 __27-[XCTestSuite performTest:]_block_invoke + 240\n\t52  XCTest                              0x00000001001a1b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t53  XCTest                              0x00000001001a1d54 -[XCTestSuite performTest:] + 200\n\t54  XCTest                              0x00000001001a1f44 __27-[XCTestSuite performTest:]_block_invoke + 240\n\t55  XCTest                              0x00000001001a1b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t56  XCTest                              0x00000001001a1d54 -[XCTestSuite performTest:] + 200\n\t57  XCTest                              0x00000001001eda14 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44\n\t58  XCTest                              0x00000001001b08dc -[XCTestObservationCenter _observeTestExecutionForBlock:] + 520\n\t59  XCTest                              0x00000001001ed894 -[XCTTestRunSession runTestsAndReturnError:] + 292\n\t60  XCTest                              0x000000010018cf70 -[XCTestDriver runTestsAndReturnError:] + 252\n\t61  XCTest                              0x00000001001e36f8 _XCTestMain + 548\n\t62  CoreFoundation                      0x000000019070ea44 <redacted> + 20\n\t63  CoreFoundation                      0x000000019070e240 <redacted> + 288\n\t64  CoreFoundation                      0x000000019070c094 <redacted> + 788\n\t65  CoreFoundation                      0x000000019063a2b8 CFRunLoopRunSpecific + 444\n\t66  GraphicsServices                    0x00000001920ee198 GSEventRunModal + 180\n\t67  UIKit                               0x00000001966817fc <redacted> + 684\n\t68  UIKit                               0x000000019667c534 UIApplicationMain + 208\n\t69  XCTRunner                           0x00000001000a4474 XCTRunner + 33908\n\t70  libdyld.dylib                       0x000000018f61d5b8 <redacted> + 4\n)","sessionId":"254A44D6-B719-49E0-8C2C-C5FA926A9CA0","status":13}
    '****** xctest source end *******
```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
update xcode to 8.3

**Comment by Sandu1213** [comment]
@xudafeng has updated xcode(ver:8.3.2), the issues is still occured. help,tks!

**Environment:**
app-inspector: 1.2.23
OS ver:10.12.4
devices ver: 10.2.1 (Ipad Air 2)
xcode ver:8.3.2

**Error Info:**
{"value":"*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]\n\n(\n\t0   CoreFoundation                      0x0000000182c851d0 <redacted> + 148\n\t1   libobjc.A.dylib                     0x00000001816bc55c objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000182b63870 <redacted> + 312\n\t3   CoreFoundation                      0x0000000182b6f5fc <redacted> + 52\n\t4   XCTest                              0x00000001001cb6bc -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 152\n\t5   XCTest                              0x00000001001cbad4 -[XCElementSnapshot(Hitpoint) hitPoint] + 392\n\t6   WebDriverAgentLib                   0x0000000102653240 -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 576\n\t7   WebDriverAgentLib                   0x000000010265e654 -[XCElementSnapshot(WebDriverAttributes) isWDVisible] + 40\n\t8   WebDriverAgentLib                   0x0000000102650298 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 1692\n\t9   WebDriverAgentLib                   0x00000001026504ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t10  WebDriverAgentLib                   0x00000001026504ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t11  WebDriverAgentLib                   0x00000001026504ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t12  WebDriverAgentLib                   0x00000001026504ec +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2288\n\t13  WebDriverAgentLib                   0x000000010264fb48 -[XCUIApplication(FBHelpers) fb_tree] + 100\n\t14  WebDriverAgentLib                   0x000000010265ff64 +[FBDebugCommands handleGetSourceCommand:] + 360\n\t15  WebDriverAgentLib                   0x000000010265582c -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t16  WebDriverAgentLib                   0x000000010264d5b4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t17  RoutingHTTPServer                   0x00000001026f23cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t18  RoutingHTTPServer                   0x00000001026f2b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44\n\t19  libdispatch.dylib                   0x0000000181b0e1bc <redacted> + 16\n\t20  libdispatch.dylib                   0x0000000181b1f084 <redacted> + 320\n\t21  libdispatch.dylib                   0x0000000181b0e1bc <redacted> + 16\n\t22  libdispatch.dylib                   0x0000000181b12d68 _dispatch_main_queue_callback_4CF + 1000\n\t23  CoreFoundation                      0x0000000182c32810 <redacted> + 12\n\t24  CoreFoundation                      0x0000000182c303fc <redacted> + 1660\n\t25  CoreFoundation                      0x0000000182b5e2b8 CFRunLoopRunSpecific + 444\n\t26  Foundation                          0x000000018369b26c <redacted> + 304\n\t27  Foundation                          0x00000001836efaa0 <redacted> + 88\n\t28  WebDriverAgentLib                   0x000000010264c704 -[FBWebServer startServing] + 260\n\t29  WebDriverAgentRunner                0x000000010263bef4 -[UITestingUITests testRunner] + 80\n\t30  CoreFoundation                      0x0000000182c8b150 <redacted> + 144\n\t31  CoreFoundation                      0x0000000182b7deac <redacted> + 284\n\t32  XCTest                              0x0000000100184a30 __24-[XCTestCase invokeTest]_block_invoke.237 + 48\n\t33  XCTest                              0x000000010018467c __24-[XCTestCase invokeTest]_block_invoke_2 + 564\n\t34  XCTest                              0x00000001001bfdac -[XCTestContext performInScope:] + 208\n\t35  XCTest                              0x0000000100184430 -[XCTestCase invokeTest] + 268\n\t36  XCTest                              0x0000000100184d80 -[XCTestCase performTest:] + 536\n\t37  XCTest                              0x0000000100181f44 __27-[XCTestSuite performTest:]_block_invoke + 240\n\t38  XCTest                              0x0000000100181b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t39  XCTest                              0x0000000100181d54 -[XCTestSuite performTest:] + 200\n\t40  XCTest                              0x0000000100181f44 __27-[XCTestSuite performTest:]_block_invoke + 240\n\t41  XCTest                              0x0000000100181b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t42  XCTest                              0x0000000100181d54 -[XCTestSuite performTest:] + 200\n\t43  XCTest                              0x0000000100181f44 __27-[XCTestSuite performTest:]_block_invoke + 240\n\t44  XCTest                              0x0000000100181b64 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44\n\t45  XCTest                              0x0000000100181d54 -[XCTestSuite performTest:] + 200\n\t46  XCTest                              0x00000001001cda14 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44\n\t47  XCTest                              0x00000001001908dc -[XCTestObservationCenter _observeTestExecutionForBlock:] + 520\n\t48  XCTest                              0x00000001001cd894 -[XCTTestRunSession runTestsAndReturnError:] + 292\n\t49  XCTest                              0x000000010016cf70 -[XCTestDriver runTestsAndReturnError:] + 252\n\t50  XCTest                              0x00000001001c36f8 _XCTestMain + 548\n\t51  CoreFoundation                      0x0000000182c32a44 <redacted> + 20\n\t52  CoreFoundation                      0x0000000182c32240 <redacted> + 288\n\t53  CoreFoundation                      0x0000000182c30094 <redacted> + 788\n\t54  CoreFoundation                      0x0000000182b5e2b8 CFRunLoopRunSpecific + 444\n\t55  GraphicsServices                    0x0000000184612198 GSEventRunModal + 180\n\t56  UIKit                               0x0000000188b9e7fc <redacted> + 684\n\t57  UIKit                               0x0000000188b99534 UIApplicationMain + 208\n\t58  XCTRunner                           0x000000010002c474 XCTRunner + 33908\n\t59  libdyld.dylib                       0x0000000181b415b8 <redacted> + 4\n)","sessionId":"1EA025CD-17AF-4F62-B8F8-C1F79F704E5A","status":13}
    '****** xctest source end *******

**Comment by xudafeng** [comment]
@Sandu1213 升级新版
