### ISSUE TITLE
iOS app-inspector error

### ISSUE THREAD

**Issue by skumar1122** [macacajs/app-inspector#77]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:
V1.0

- os version / 系统:
Mac -10.12.4
node version: v7.8.0
macaca-doctor version: 1.0.28
WebDriverAgent version: 1.1.6

- device  information / 设备版本:
iPhone6Plus - 10.3.1 

- terminal log / 终端输出信息:

> WHM5003604:~ skumar$ app-inspector -u 9285c264a00455134d31e698ed542463bdaff43c
> >> xctest-client start with port: 8900
> >> WebDriverAgent version: 1.1.6
> >> app-inspector:66:44 [master] pid:22954 undefined
> (node:22954) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:22954 undefined
> (node:22954) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> try `app-inspector -u xxxx --verbose` for more log detail.

> $ app-inspector -u 9285c264a00455134d31e698ed542463bdaff43c --verbose
> >> server.js:16:12 [master] pid:23094 server start with config:
>  { port: 5678,
>   verbose: true,
>   udid: '9285c264a00455134d31e698ed542463bdaff43c',
>   ip: '192.168.58.1',
>   host: 'WHM5003604.local',
>   loaded_time: '2017-04-12 11:46:26' }
> >> app-inspector.js:42:10 [master] pid:23094 server start at: http://192.168.58.1:5678
> >> xctest-client.js:56:14 [master] pid:23094 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> >> xctest-client start with port: 8900
> >> xctest-client.js:238:14 [master] pid:23094 xcode version: 8.3
> >> WebDriverAgent version: 1.1.6
> >> xctest-client.js:175:14 [master] pid:23094 2017-04-12 11:46:28.497 xcodebuild[23100:1789374]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/BFDFC449-2DA4-4DD2-84C9-9CA7C65A072D/Session-WebDriverAgentRunner-2017-04-12_114628-GHqq8f.log
> 
> >> xctest-client.js:176:14 [master] pid:23094 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> >> xctest-client.js:175:14 [master] pid:23094 2017-04-12 11:46:28.497 xcodebuild[23100:1789357] [MT] IDETestOperationsObserverDebug: (A9CB757A-E0C6-4510-BE76-89C832988FBE) Beginning test session WebDriverAgentRunner-A9CB757A-E0C6-4510-BE76-89C832988FBE at 2017-04-12 11:46:28.497 with Xcode 8E162 on target <DVTiOSDevice: 0x7fdf1969a6f0> {
> 		deviceSerialNumber:         FK1Q2C0AG5QQ
> 		identifier:                 9285c264a00455134d31e698ed542463bdaff43c
> 		deviceClass:                iPhone
> 		deviceName:                 WhTest’s iPhone
> 		deviceIdentifier:           9285c264a00455134d31e698ed542463bdaff43c
> 		productVersion:             10.3.1
> 		buildVersion:               14E304
> 		deviceSoftwareVersion:      10.3.1 (14E304)
> 		deviceArchitecture:         arm64
> 		deviceTotalCapacity:        12158566400
> 		deviceAvailableCapacity:    10014212096
> 		deviceIsTransient:          NO
> 		ignored:                    NO
> 		deviceIsBusy:               NO
> 		deviceIsActivated:          YES
> 		deviceActivationState:      Activated
> 		isPasscodeLocked:           NO
> 		deviceType:                 <DVTDeviceType:0x7fdf195d6370 Xcode.DeviceType.iPhone>
> 		supportedDeviceFamilies:    (
>     1
> )
> 		applications:              (null)
> 		provisioningProfiles:      (null)
> 		activityProgress:          -2
> 		activityTitle:             
> 		hasInternalSupport:        NO
> 		isSupportedOS:             YES
> 		developerDiskMountError:   (null)
> (null)
> 	bootArgs:                  <unavailable>
> 		} (10.3.1 (14E304))
> 
> >> xctest-client.js:176:14 [master] pid:23094 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> >> xctest-client.js:175:14 [master] pid:23094 2017-04-12 11:46:29.073 xcodebuild[23100:1789357] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/BFDFC449-2DA4-4DD2-84C9-9CA7C65A072D/Session-WebDriverAgentRunner-2017-04-12_114628-GHqq8f.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/BFDFC449-2DA4-4DD2-84C9-9CA7C65A072D/Session-WebDriverAgentRunner-2017-04-12_114628-GHqq8f.log}
> 
> >> xctest-client.js:176:14 [master] pid:23094 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> >> xctest-client.js:175:14 [master] pid:23094 
> Testing failed:
> 	No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "D8A9Y93768" with a private key was found.
> 	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/BFDFC449-2DA4-4DD2-84C9-9CA7C65A072D/Session-WebDriverAgentRunner-2017-04-12_114628-GHqq8f.log
> ** TEST FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> 
> >> xctest-client.js:176:14 [master] pid:23094 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> >> xctest-client.js:270:14 [master] pid:23094 killing deviceLogProc pid: 23097
> >> xctest-client.js:275:14 [master] pid:23094 killing runnerProc pid: 23100
> >> xctest-client.js:281:14 [master] pid:23094 killing iproxyProc pid: 23099
> >> xctest-client.js:186:14 [master] pid:23094 xctest client exit with code: 65, signal: null
> >> xctest-client.js:214:14 [master] pid:23094 iproxy exit with code: null, signal: SIGKILL
> >> xctest-client.js:150:16 [master] pid:23094 deviceconsole exit with code: null, signal: SIGKILL
> >> xctest-client.js:262:14 [master] pid:23094 Fail to start xctest: undefined
> >> app-inspector:66:44 [master] pid:23094 undefined
> (node:23094) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:23094 undefined
> (node:23094) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>

**Comment by xudafeng** [comment]
update xcode to 8.3

**Comment by skumar1122** [comment]
Hi @xudafeng , 

Yes , I am using Latest versions 
Xcode : 8.3.1
iOS - 10.3.1
please check the logs attached.

$ app-inspector -u a6deb19e55a05baafed39f5b04b10749ce52edf7 --verbose
>> server.js:16:12 [master] pid:15424 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'a6deb19e55a05baafed39f5b04b10749ce52edf7',
  ip: '192.168.58.1',
  host: 'WHM5003604.local',
  loaded_time: '2017-04-18 16:26:25' }
>> app-inspector.js:42:10 [master] pid:15424 server start at: http://192.168.58.1:5678
>> xctest-client.js:56:14 [master] pid:15424 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:238:14 [master] pid:15424 xcode version: 8.3.1
>> WebDriverAgent version: 1.1.6
>> xctest-client.js:175:14 [master] pid:15424 2017-04-18 16:26:28.956 xcodebuild[15430:10352535]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/56816B10-44C1-4C5C-B526-46DDED3B2779/Session-WebDriverAgentRunner-2017-04-18_162628-AaSIEo.log

>> xctest-client.js:176:14 [master] pid:15424 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:15424 2017-04-18 16:26:28.957 xcodebuild[15430:10352525] [MT] IDETestOperationsObserverDebug: (665AFF51-1050-47C0-AAD9-8EA86039397D) Beginning test session WebDriverAgentRunner-665AFF51-1050-47C0-AAD9-8EA86039397D at 2017-04-18 16:26:28.957 with Xcode 8E1000a on target <DVTiOSDevice: 0x7f8cfc49ab20> {
		deviceSerialNumber:         DX3PGE26FFGC
		identifier:                 a6deb19e55a05baafed39f5b04b10749ce52edf7
		deviceClass:                iPhone
		deviceName:                 Richard's iPhone
		deviceIdentifier:           a6deb19e55a05baafed39f5b04b10749ce52edf7
		productVersion:             10.3.1
		buildVersion:               14E304
		deviceSoftwareVersion:      10.3.1 (14E304)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12380741632
		deviceAvailableCapacity:    8970186752
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f8cfbe01ed0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.1 (14E304))

>> xctest-client.js:176:14 [master] pid:15424 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:15424 2017-04-18 16:26:29.737 xcodebuild[15430:10352525] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/56816B10-44C1-4C5C-B526-46DDED3B2779/Session-WebDriverAgentRunner-2017-04-18_162628-AaSIEo.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/56816B10-44C1-4C5C-B526-46DDED3B2779/Session-WebDriverAgentRunner-2017-04-18_162628-AaSIEo.log}

>> xctest-client.js:176:14 [master] pid:15424 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:15424 
Testing failed:

>> xctest-client.js:176:14 [master] pid:15424 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:15424 	No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "D8A9Y93768" with a private key was found.
	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/56816B10-44C1-4C5C-B526-46DDED3B2779/Session-WebDriverAgentRunner-2017-04-18_162628-AaSIEo.log
** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:176:14 [master] pid:15424 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:270:14 [master] pid:15424 killing deviceLogProc pid: 15427
>> xctest-client.js:275:14 [master] pid:15424 killing runnerProc pid: 15430
>> xctest-client.js:281:14 [master] pid:15424 killing iproxyProc pid: 15429
>> xctest-client.js:186:14 [master] pid:15424 xctest client exit with code: 65, signal: null
>> xctest-client.js:214:14 [master] pid:15424 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:150:16 [master] pid:15424 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:262:14 [master] pid:15424 Fail to start xctest: undefined
>> app-inspector:66:44 [master] pid:15424 undefined
(node:15424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:15424 undefined
(node:15424) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

``

**Comment by skumar1122** [comment]
Hey @xudafeng ,

can someone help me to inspect iOS real device ? 
getting error below ,

> M5003604:.bin skumar$ app-inspector -u 4c07d6399dfa83fa59a58105f7030b4819e456d3
> >> xctest-client start with port: 8900
> >> WebDriverAgent version: 1.1.6
> >> app-inspector:66:44 [master] pid:87844 undefined
> (node:87844) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:87844 undefined
> (node:87844) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/377

**Comment by xudafeng** [comment]
update to latest version
