### ISSUE TITLE
Start app-inspector, failed with: pid:50707 xctest client exit with code: 65, signal: null

### ISSUE THREAD

**Issue by nguyenthinam** [macacajs/app-inspector#78]
- app inspector version / 版本号: 
1.2.23
macaca ver: 1.2.2
node version: v6.10.2

- os version / 系统: 
Sierra 10.12

- device  information / 设备版本: 
iPhone7Plus - iOS 10.0

- terminal log / 终端输出信息:
`CompileC /Users/namnguyen/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Build/Intermediates/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/FBElementCommands.o WebDriverAgentLib/Commands/FBElementCommands.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

>> xctest-client.js:176:14 [master] pid:50707 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:270:14 [master] pid:50707 killing deviceLogProc pid: 50713
>> xctest-client.js:275:14 [master] pid:50707 killing runnerProc pid: 50712
>> xctest-client.js:186:14 [master] pid:50707 xctest client exit with code: 65, signal: null
>> xctest-client.js:112:18 [master] pid:50707 simulator log process exit with code: null, signal: SIGKILL`

This issue occurs because a compiler error at WebDriverAgent 
`/usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/PrivateHeaders/XCTest/XCUICoordinate.h:30:1: Duplicate declaration of method 'pressForDuration:thenDragToCoordinate:'`

Just comment out that method in XCUICoordinate.h, rebuild Project and voila  app inspector works.

Please update your codes, thanks!

**Comment by xudafeng** [comment]
@nguyenthinam update xcode to 8.3
