### ISSUE TITLE
app-inspector 在gui显示页，下拉后，查找元素失败。

### ISSUE THREAD

**Issue by upengfei** [macacajs/app-inspector#79]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:

- os version / 系统:

- device  information / 设备版本:

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/377

**Comment by xudafeng** [comment]
@upengfei  升级新版

**Comment by upengfei** [comment]
感谢您的付出~~~收到！

在 2017-05-07 01:14:01，"xdf" <notifications@github.com> 写道：


@upengfei 升级新版
