### ISSUE TITLE
不能连接真机查看？

### ISSUE THREAD

**Issue by tigerqiu712** [macacajs/app-inspector#8]
连接真机的时候报错如下
  --> GET / 200
  <-- GET /jquery/dist/jquery.min.map
  --> GET /jquery/dist/jquery.min.map 404

**Comment by meowtec** [comment]
这个是一个前端资源的问题，对功能没有影响。
页面是否正常？如果现实 loading 需要多等十几秒

**Comment by xudafeng** [comment]
@meowtec 可以让用户知道等待是因为设备没准备好吗？不然设备慢的用户以为工具有问题

**Comment by meowtec** [comment]
#5 是不是同一个问题。

@xudafeng 现在就是显示等待中啊。用户可能因为等待久了，因为工具挂掉了。

可以考虑优化等待时间，在 initDevice 完成之前，设备其实就可以拿到 source 了，可以从这方面入手

**Comment by xudafeng** [comment]
@tigerqiu712  给出的log和信息太少了，不能判断问题

**Comment by tigerqiu712** [comment]
工具挂掉了，但是原因，我不知道，需要的具体信息可以加我微信：cambridge_brandy

**Comment by meowtec** [comment]
请参考 https://github.com/macacajs/app-inspector/issues/new 给出详细信息

**Comment by tigerqiu712** [comment]
原因是电脑上我同时装了两个版本的Xcode，新版本一直显示设备初始化了
 isDev: false }
>> port: 5678 was occupied, changed port: 5679
>> server.js:16:12 [master] pid:9744 server start with config:
 { port: 5679,
  verbose: true,
  udid: '76868D8A-E357-4715-9092-110CD743DFB3',
  ip: '192.168.1.8',
  host: 'localhost',
  loaded_time: '2016-08-27 00:38:17' }
>> inspector start at: http://192.168.1.8:5679
>> xctest-client.js:43:14 [master] pid:9744 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:182:12 [master] pid:9744 xcode version: 8.0
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> xctest-client.js:155:14 [master] pid:9744 xcodebuild: error: Unable to find a destination matching the provided destination specifier:
       		{ id:76868D8A-E357-4715-9092-110CD743DFB3 }

       	Unsupported device specifier option.
       	The device “My Mac” does not support the following options: id
       	Please supply only supported device specifier options.

       	Available destinations for the "WebDriverAgentRunner" scheme:
       		{ platform:iOS Simulator, id:D567684C-2032-4748-9BC9-CE2CC510D5A1, OS:10.0, name:iPad Air }
       		{ platform:iOS Simulator, id:5959331A-4D65-4242-B8FC-E6F5DDCBEA51, OS:10.0, name:iPad Air 2 }
       		{ platform:iOS Simulator, id:B77CE76D-4F15-4505-ADBC-6FD331E82375, OS:10.0, name:iPad Pro (9.7 inch) }
       		{ platform:iOS Simulator, id:584BC5B5-4790-4D67-8C18-0BD69154474F, OS:10.0, name:iPad Pro (12.9 inch) }
       		{ platform:iOS Simulator, id:31AF6531-9AAA-4C31-ABA8-8307D7FCC1F9, OS:10.0, name:iPad Retina }
       		{ platform:iOS Simulator, id:F459A9CD-8E0F-498D-9910-4EEE65853DBF, OS:10.0, name:iPhone 5 }
       		{ platform:iOS Simulator, id:B0D2606B-B4E6-4824-B3D2-0B66AE3D2730, OS:10.0, name:iPhone 5s }
       		{ platform:iOS Simulator, id:6AB48015-FA97-49F9-B122-B74DCB3F531E, OS:10.0, name:iPhone 6 }
       		{ platform:iOS Simulator, id:93DB11DC-8B70-4509-A3FF-7CBDB37B3381, OS:10.0, name:iPhone 6 Plus }
       		{ platform:iOS Simulator, id:3E4F5F12-03A2-41E0-BC59-270E727CB813, OS:10.0, name:iPhone 6s }
       		{ platform:iOS Simulator, id:C5930AE3-C35F-4EA1-B18B-73B75072CCA8, OS:10.0, name:iPhone 6s Plus }
       		{ platform:iOS Simulator, id:39222E32-EFD8-41F6-8EE1-0133E2B8309D, OS:10.0, name:iPhone SE }

       	Ineligible destinations for the "WebDriverAgentRunner" scheme:
       		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
       		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

>> xctest-client.js:163:14 [master] pid:9744 xctest client exit with code: 70, signal: null
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200

**Comment by xudafeng** [comment]
留最新版就好，其余删除，低版本的模拟器也可以删掉
