### ISSUE TITLE
The source may be wrong, please report message is seen when trying to inspect

### ISSUE THREAD

**Issue by Lokeshgan** [macacajs/app-inspector#80]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:1.6.4

- os version / 系统:10.12 Mac

- device  information / 设备版本:
Simulator iphone 6S

- terminal log / 终端输出信息:

  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":"*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]\n\n(\n\t0   CoreFoundation                      0x000000010cb9ad4b __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x000000010c5fc21e objc_exception_throw + 48\n\t2   CoreFoundation                      0x000000010caaa783 -[__NSPlaceholderArray initWithObjects:count:] + 275\n\t3   CoreFoundation                      0x000000010cab1994 +[NSArray arrayWithObjects:count:] + 52\n\t4   XCTest                              0x000000010c00ddaa -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 147\n\t5   XCTest                              0x000000010c00e19a -[XCElementSnapshot(Hitpoint) hitPoint] + 393\n\t6   WebDriverAgentLib                   0x000000011b439d6a -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 810\n\t7   WebDriverAgentLib                   0x000000011b4453bb -[XCElementSnapshot(WebDriverAttributes) isWDVisible] + 43\n\t8   WebDriverAgentLib                   0x000000011b436a64 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 1940\n\t9   WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t10  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t11  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t12  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t13  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t14  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t15  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t16  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t17  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t18  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660\n\t19  WebDriverAgentLib                   0x000000011b43620d -[XCUIApplication(FBHelpers) fb_tree] + 93\n\t20  WebDriverAgentLib                   0x000000011b446e45 +[FBDebugCommands handleGetSourceCommand:] + 357\n\t21  WebDriverAgentLib                   0x000000011b43c593 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179\n\t22  WebDriverAgentLib                   0x000000011b433ab4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548\n\t23  RoutingHTTPServer                   0x000000011b4d4c18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t24  RoutingHTTPServer                   0x000000011b4d54fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47\n\t25  libdispatch.dylib                   0x000000010f8c412e _dispatch_client_callout + 8\n\t26  libdispatch.dylib                   0x000000010f8ac773 _dispatch_barrier_sync_f_slow_invoke + 315\n\t27  libdispatch.dylib                   0x000000010f8c412e _dispatch_client_callout + 8\n\t28  libdispatch.dylib                   0x000000010f8ab4fb _dispatch_main_queue_callback_4CF + 1054\n\t29  CoreFoundation                      0x000000010cb5ee49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9\n\t30  CoreFoundation                      0x000000010cb2437d __CFRunLoopRun + 2205\n\t31  CoreFoundation                      0x000000010cb23884 CFRunLoopRunSpecific + 420\n\t32  Foundation                          0x000000010c0dd760 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274\n\t33  Foundation                          0x000000010c0dd63b -[NSRunLoop(NSRunLoop) run] + 76\n\t34  WebDriverAgentLib                   0x000000011b432a93 -[FBWebServer startServing] + 211\n\t35  WebDriverAgentRunner                0x000000011a790d24 -[UITestingUITests testRunner] + 100\n\t36  CoreFoundation                      0x000000010cb2144c __invoking___ + 140\n\t37  CoreFoundation                      0x000000010cb212d1 -[NSInvocation invoke] + 289\n\t38  XCTest                              0x000000010bfd0f77 __24-[XCTestCase invokeTest]_block_invoke_2 + 481\n\t39  XCTest                              0x000000010c0097df -[XCTestContext performInScope:] + 190\n\t40  XCTest                              0x000000010bfd0d83 -[XCTestCase invokeTest] + 255\n\t41  XCTest                              0x000000010bfd159c -[XCTestCase performTest:] + 457\n\t42  XCTest                              0x000000010bfce664 -[XCTestSuite performTest:] + 491\n\t43  XCTest                              0x000000010bfce664 -[XCTestSuite performTest:] + 491\n\t44  XCTest                              0x000000010bfce664 -[XCTestSuite performTest:] + 491\n\t45  XCTest                              0x000000010bfba618 __25-[XCTestDriver _runSuite]_block_invoke + 51\n\t46  XCTest                              0x000000010bfdbd2b -[XCTestObservationCenter _observeTestExecutionForBlock:] + 602\n\t47  XCTest                              0x000000010bfba4b5 -[XCTestDriver _runSuite] + 436\n\t48  XCTest                              0x000000010bfbb302 -[XCTestDriver _checkForTestManager] + 287\n\t49  XCTest                              0x000000010c00ad67 _XCTestMain + 628\n\t50  CoreFoundation                      0x000000010cb3f6ac __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12\n\t51  CoreFoundation                      0x000000010cb246f4 __CFRunLoopDoBlocks + 356\n\t52  CoreFoundation                      0x000000010cb23e65 __CFRunLoopRun + 901\n\t53  CoreFoundation                      0x000000010cb23884 CFRunLoopRunSpecific + 420\n\t54  GraphicsServices                    0x000000010effea6f GSEventRunModal + 161\n\t55  UIKit                               0x000000010cfbec68 UIApplicationMain + 159\n\t56  XCTRunner                           0x000000010bf3b81c XCTRunner + 6172\n\t57  libdyld.dylib                       0x000000010f90d68d start + 1\n\t58  ???                                 0x0000000000000005 0x0 + 5\n)","sessionId":"9B830A9A-F3D2-4FC4-9400-F63D99368480","status":13}
    '****** xctest source end *******

  TypeError: Cannot create property 'class' on string '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
  
  (
  	0   CoreFoundation                      0x000000010cb9ad4b __exceptionPreprocess + 171
  	1   libobjc.A.dylib                     0x000000010c5fc21e objc_exception_throw + 48
  	2   CoreFoundation                      0x000000010caaa783 -[__NSPlaceholderArray initWithObjects:count:] + 275
  	3   CoreFoundation                      0x000000010cab1994 +[NSArray arrayWithObjects:count:] + 52
  	4   XCTest                              0x000000010c00ddaa -[XCElementSnapshot(Hitpoint) _transformPoint:windowContextID:windowDisplayID:] + 147
  	5   XCTest                              0x000000010c00e19a -[XCElementSnapshot(Hitpoint) hitPoint] + 393
  	6   WebDriverAgentLib                   0x000000011b439d6a -[XCElementSnapshot(FBIsVisible) fb_isVisible] + 810
  	7   WebDriverAgentLib                   0x000000011b4453bb -[XCElementSnapshot(WebDriverAttributes) isWDVisible] + 43
  	8   WebDriverAgentLib                   0x000000011b436a64 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 1940
  	9   WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	10  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	11  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	12  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	13  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	14  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	15  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	16  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	17  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	18  WebDriverAgentLib                   0x000000011b436d34 +[XCUIApplication(FBHelpers) dictionaryForElement:] + 2660
  	19  WebDriverAgentLib                   0x000000011b43620d -[XCUIApplication(FBHelpers) fb_tree] + 93
  	20  WebDriverAgentLib                   0x000000011b446e45 +[FBDebugCommands handleGetSourceCommand:] + 357
  	21  WebDriverAgentLib                   0x000000011b43c593 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179
  	22  WebDriverAgentLib                   0x000000011b433ab4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548
  	23  RoutingHTTPServer                   0x000000011b4d4c18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136
  	24  RoutingHTTPServer                   0x000000011b4d54fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47
  	25  libdispatch.dylib                   0x000000010f8c412e _dispatch_client_callout + 8
  	26  libdispatch.dylib                   0x000000010f8ac773 _dispatch_barrier_sync_f_slow_invoke + 315
  	27  libdispatch.dylib                   0x000000010f8c412e _dispatch_client_callout + 8
  	28  libdispatch.dylib                   0x000000010f8ab4fb _dispatch_main_queue_callback_4CF + 1054
  	29  CoreFoundation                      0x000000010cb5ee49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
  	30  CoreFoundation                      0x000000010cb2437d __CFRunLoopRun + 2205
  	31  CoreFoundation                      0x000000010cb23884 CFRunLoopRunSpecific + 420
  	32  Foundation                          0x000000010c0dd760 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274
  	33  Foundation                          0x000000010c0dd63b -[NSRunLoop(NSRunLoop) run] + 76
  	34  WebDriverAgentLib                   0x000000011b432a93 -[FBWebServer startServing] + 211
  	35  WebDriverAgentRunner                0x000000011a790d24 -[UITestingUITests testRunner] + 100
  	36  CoreFoundation                      0x000000010cb2144c __invoking___ + 140
  	37  CoreFoundation                      0x000000010cb212d1 -[NSInvocation invoke] + 289
  	38  XCTest                              0x000000010bfd0f77 __24-[XCTestCase invokeTest]_block_invoke_2 + 481
  	39  XCTest                              0x000000010c0097df -[XCTestContext performInScope:] + 190
  	40  XCTest                              0x000000010bfd0d83 -[XCTestCase invokeTest] + 255
  	41  XCTest                              0x000000010bfd159c -[XCTestCase performTest:] + 457
  	42  XCTest                              0x000000010bfce664 -[XCTestSuite performTest:] + 491
  	43  XCTest                              0x000000010bfce664 -[XCTestSuite performTest:] + 491
  	44  XCTest                              0x000000010bfce664 -[XCTestSuite performTest:] + 491
  	45  XCTest                              0x000000010bfba618 __25-[XCTestDriver _runSuite]_block_invoke + 51
  	46  XCTest                              0x000000010bfdbd2b -[XCTestObservationCenter _observeTestExecutionForBlock:] + 602
  	47  XCTest                              0x000000010bfba4b5 -[XCTestDriver _runSuite] + 436
  	48  XCTest                              0x000000010bfbb302 -[XCTestDriver _checkForTestManager] + 287
  	49  XCTest                              0x000000010c00ad67 _XCTestMain + 628
  	50  CoreFoundation                      0x000000010cb3f6ac __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
  	51  CoreFoundation                      0x000000010cb246f4 __CFRunLoopDoBlocks + 356
  	52  CoreFoundation                      0x000000010cb23e65 __CFRunLoopRun + 901
  	53  CoreFoundation                      0x000000010cb23884 CFRunLoopRunSpecific + 420
  	54  GraphicsServices                    0x000000010effea6f GSEventRunModal + 161
  	55  UIKit                               0x000000010cfbec68 UIApplicationMain + 159
  	56  XCTRunner                           0x000000010bf3b81c XCTRunner + 6172
  	57  libdyld.dylib                       0x000000010f90d68d start + 1
  	58  ???                                 0x0000000000000005 0x0 + 5
  )'
      at adaptor (/Users/gangaiahl/node_modules/app-inspector/lib/ios.js:23:14)
      at Object.exports.dumpXMLAndScreenShot (/Users/gangaiahl/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/Users/gangaiahl/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by Lokeshgan** [comment]
![screen shot 2017-04-19 at 3 04 06 pm](https://cloud.githubusercontent.com/assets/27757483/25164012/88aaad82-2511-11e7-931a-5cb4c81d0aef.png)

**Comment by Lokeshgan** [comment]
![screen shot 2017-04-19 at 3 05 57 pm](https://cloud.githubusercontent.com/assets/27757483/25164032/ba2b8a84-2511-11e7-922e-2f0e4c17d757.png)

**Comment by Lokeshgan** [comment]
Just for that particular page on the app, this error is seen. for other pages in the app its all good able to inspect elements

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor
