### ISSUE TITLE
app-inspector -u bb5e64f1c4663afce48181d8033ef20a1a0086bd --verbose

### ISSUE THREAD

**Issue by lengyao88** [macacajs/app-inspector#81]
seirradeMac:~ hack$ app-inspector -u bb5e64f1c4663afce48181d8033ef20a1a0086bd --verbose
>> port: 5678 was occupied, changed port: 5682
>> server.js:16:12 [master] pid:24513 server start with config:
 { port: 5682,
  verbose: true,
  udid: 'bb5e64f1c4663afce48181d8033ef20a1a0086bd',
  ip: '192.168.121.134',
  host: 'seirradeMac.local',
  loaded_time: '2017-04-20 14:46:35' }
>> app-inspector.js:42:10 [master] pid:24513 server start at: http://192.168.121.134:5682
>> xctest-client.js:56:14 [master] pid:24513 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:238:14 [master] pid:24513 xcode version: 8.3.1
>> WebDriverAgent version: 1.1.6
>> xctest-client.js:175:14 [master] pid:24513 2017-04-20 14:46:38.551 xcodebuild[24519:296298]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/hack/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/CBE726CB-DB11-4A53-A010-9E9D110EFCAD/Session-WebDriverAgentRunner-2017-04-20_144638-q7tTgm.log

>> xctest-client.js:176:14 [master] pid:24513 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:24513 2017-04-20 14:46:38.551 xcodebuild[24519:296251] [MT] IDETestOperationsObserverDebug: (E09E197D-6E6F-441D-8866-D956434EDFDE) Beginning test session WebDriverAgentRunner-E09E197D-6E6F-441D-8866-D956434EDFDE at 2017-04-20 14:46:38.551 with Xcode 8E1000a on target <DVTiOSDevice: 0x7fdf6a6cead0> {
		deviceSerialNumber:         C3TJPDTPT4K4
		identifier:                 bb5e64f1c4663afce48181d8033ef20a1a0086bd
		deviceClass:                iPod
		deviceName:                 测试touch5-8.4
		deviceIdentifier:           bb5e64f1c4663afce48181d8033ef20a1a0086bd
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         armv7f
		deviceTotalCapacity:        29255798784
		deviceAvailableCapacity:    24622874624
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fdf67e18410 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (9.3.5 (13G36))

>> xctest-client.js:176:14 [master] pid:24513 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:24513 2017-04-20 14:46:40.687 xcodebuild[24519:296251] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/hack/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/CBE726CB-DB11-4A53-A010-9E9D110EFCAD/Session-WebDriverAgentRunner-2017-04-20_144638-q7tTgm.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/hack/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/CBE726CB-DB11-4A53-A010-9E9D110EFCAD/Session-WebDriverAgentRunner-2017-04-20_144638-q7tTgm.log}

>> xctest-client.js:176:14 [master] pid:24513 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:24513 
Testing failed:
	No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "D8A9Y93768" with a private key was found.
	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/hack/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/CBE726CB-DB11-4A53-A010-9E9D110EFCAD/Session-WebDriverAgentRunner-2017-04-20_144638-q7tTgm.log

>> xctest-client.js:176:14 [master] pid:24513 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:24513 ** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:176:14 [master] pid:24513 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:270:14 [master] pid:24513 killing deviceLogProc pid: 24516
>> xctest-client.js:275:14 [master] pid:24513 killing runnerProc pid: 24519
>> xctest-client.js:281:14 [master] pid:24513 killing iproxyProc pid: 24518
>> xctest-client.js:186:14 [master] pid:24513 xctest client exit with code: 65, signal: null
>> xctest-client.js:214:14 [master] pid:24513 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:150:16 [master] pid:24513 deviceconsole exit with code: null, signal: SIGKILL
>> proxy.js:56:14 [master] pid:24513 Proxy: /session:POST to http://127.0.0.1:8900/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:62:22 [master] pid:24513 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> xctest-client.js:262:14 [master] pid:24513 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8900
>> app-inspector:66:44 [master] pid:24513 Error: connect ECONNREFUSED 127.0.0.1:8900
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
(node:24513) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:24513 Error: connect ECONNREFUSED 127.0.0.1:8900
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by xudafeng** [comment]
update to latest version
