### ISSUE TITLE
Mac上使用inspector 在模拟上报错

### ISSUE THREAD

**Issue by jiap0724** [macacajs/app-inspector#83]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:1.2.23

- os version / 系统:macOS 10.12.4 (16E195)

- device  information / 设备版本:Xcode 自带的ios模拟器

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.
>> server.js:16:12 [master] pid:2806 server start with config:
 { port: 5678,
  verbose: true,
  udid: '91B26BEB-6251-49F9-A5D3-472E941021B0',
  ip: '10.0.1.176',
  host: 'jiapengdeMacBook-Pro.local',
  loaded_time: '2017-05-04 14:11:32' }
>> app-inspector.js:42:10 [master] pid:2806 server start at: http://10.0.1.176:5678
>> xctest-client.js:56:14 [master] pid:2806 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:238:14 [master] pid:2806 xcode version: 8.2.1
>> WebDriverAgent version: 1.1.6
>> xctest-client.js:175:14 [master] pid:2806 2017-05-04 14:11:33.862 xcodebuild[2809:63009] [MT] IDETestOperationsObserverDebug: (F2D77BBB-C934-4A13-B89A-C212F96ECEAD) Beginning test session WebDriverAgentRunner-F2D77BBB-C934-4A13-B89A-C212F96ECEAD at 2017-05-04 14:11:33.861 with Xcode 8C1002 on target <DVTiPhoneSimulator: 0x7fc348925410> {
		SimDevice: SimDevice : iPhone 5s (91B26BEB-6251-49F9-A5D3-472E941021B0) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 10.2 (14C89) - com.apple.CoreSimulator.SimRuntime.iOS-10-2 }
} (10.2 (14C89))

>> xctest-client.js:176:14 [master] pid:2806 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:2806 2017-05-04 14:11:33.863 xcodebuild[2809:63016]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/jiapeng/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/1D0C46B9-27B3-4A02-B785-13785F1A4CCD/Session-WebDriverAgentRunner-2017-05-04_141133-0k9zZF.log

>> xctest-client.js:176:14 [master] pid:2806 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:56:14 [master] pid:2806 Proxy: /session:POST to http://10.0.1.176:8100/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:84:20 [master] pid:2806 Got response with status 200: {"value":"'bundleId' desired capability not provided","sessionId":null,"status":13}
>> iOS device started: 91B26BEB-6251-49F9-A5D3-472E941021B0
>> inspector start at: http://10.0.1.176:5678
  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\" \" label=\" \" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"320\" height=\"568\"/>\n    </XCUIElementTypeOther>\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"320\" height=\"568\"/>\n  </XCUIElementTypeWindow>\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n            <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n              <XCUIElementTypeScrollView type=\"XCUIElementTypeScrollView\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"20\" width=\"320\" height=\"436\">\n                <XCUIElementTypeScrollView type=\"XCUIElementTypeScrollView\" enabled=\"true\" shown=\"false\" x=\"-640\" y=\"20\" width=\"0\" height=\"0\"/>\n                <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"-640\" y=\"0\" width=\"320\" height=\"568\">\n                  <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"-640\" y=\"0\" width=\"320\" height=\"568\">\n                    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"-640\" y=\"0\" width=\"320\" height=\"568\"/>\n                  </XCUIElementTypeOther>\n                </XCUIElementTypeOther>\n                <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"-320\" y=\"20\" width=\"320\" height=\"436\">\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" value=\"Thursday, May 04\" name=\"Calendar\" label=\"Calendar\" enabled=\"true\" shown=\"false\" x=\"-306\" y=\"25\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Photos\" label=\"Photos\" enabled=\"true\" shown=\"false\" x=\"-230\" y=\"25\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Maps\" label=\"Maps\" enabled=\"true\" shown=\"false\" x=\"-154\" y=\"25\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Wallet\" label=\"Wallet\" enabled=\"true\" shown=\"false\" x=\"-78\" y=\"25\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Reminders\" label=\"Reminders\" enabled=\"true\" shown=\"false\" x=\"-308\" y=\"113\" width=\"69\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"News\" label=\"News\" enabled=\"true\" shown=\"false\" x=\"-230\" y=\"113\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Health\" label=\"Health\" enabled=\"true\" shown=\"false\" x=\"-154\" y=\"113\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Settings\" label=\"Settings\" enabled=\"true\" shown=\"false\" x=\"-78\" y=\"113\" width=\"64\" height=\"86\"/>\n                </XCUIElementTypeOther>\n                <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"20\" width=\"320\" height=\"436\">\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Watch\" label=\"Watch\" enabled=\"true\" shown=\"true\" x=\"14\" y=\"25\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" value=\"1 app\" name=\"Extras\" label=\"Extras folder\" enabled=\"true\" shown=\"true\" x=\"90\" y=\"25\" width=\"64\" height=\"86\">\n                    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" name=\"Contacts\" label=\"Contacts\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"0\" height=\"0\"/>\n                  </XCUIElementTypeIcon>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"iCloud Drive\" label=\"iCloud Drive\" enabled=\"true\" shown=\"true\" x=\"159\" y=\"25\" width=\"78\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"PICOOC\" label=\"PICOOC\" enabled=\"true\" shown=\"true\" x=\"242\" y=\"25\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"WebDriverAgentRunner\" label=\"WebDriverAgentRunner\" enabled=\"true\" shown=\"true\" x=\"7\" y=\"113\" width=\"78\" height=\"86\"/>\n                </XCUIElementTypeOther>\n              </XCUIElementTypeScrollView>\n              <XCUIElementTypePageIndicator type=\"XCUIElementTypePageIndicator\" value=\"Page 3 of 3\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"445\" width=\"320\" height=\"43\"/>\n              <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"472\" width=\"320\" height=\"96\">\n                <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"471\" width=\"320\" height=\"3\">\n                  <XCUIElementTypeImage type=\"XCUIElementTypeImage\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"471\" width=\"320\" height=\"3\"/>\n                </XCUIElementTypeOther>\n                <XCUIElementTypeOther type=\"XCUIElementTypeOther\" name=\"Dock\" label=\"Dock\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"472\" width=\"320\" height=\"96\">\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Safari\" label=\"Safari\" enabled=\"true\" shown=\"true\" x=\"90\" y=\"484\" width=\"64\" height=\"86\"/>\n                  <XCUIElementTypeIcon type=\"XCUIElementTypeIcon\" name=\"Messages\" label=\"Messages\" enabled=\"true\" shown=\"true\" x=\"165\" y=\"484\" width=\"66\" height=\"86\"/>\n                </XCUIElementTypeOther>\n                <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"472\" width=\"320\" height=\"126\">\n                  <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"472\" width=\"320\" height=\"568\"/>\n                </XCUIElementTypeOther>\n              </XCUIElementTypeOther>\n            </XCUIElementTypeOther>\n          </XCUIElementTypeOther>\n        </XCUIElementTypeOther>\n      </XCUIElementTypeOther>\n    </XCUIElementTypeOther>\n  </XCUIElementTypeWindow>\n  <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\"/>\n        </XCUIElementTypeOther>\n      </XCUIElementTypeOther>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\"/>\n        </XCUIElementTypeOther>\n      </XCUIElementTypeOther>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\"/>\n      </XCUIElementTypeOther>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\"/>\n      </XCUIElementTypeOther>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\"/>\n        </XCUIElementTypeOther>\n      </XCUIElementTypeOther>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\"/>\n        </XCUIElementTypeOther>\n      </XCUIElementTypeOther>\n    </XCUIElementTypeOther>\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"640\" height=\"1136\"/>\n  </XCUIElementTypeOther>\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"320\" height=\"568\"/>\n  </XCUIElementTypeWindow>\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"568\">\n    <XCUIElementTypeStatusBar type=\"XCUIElementTypeStatusBar\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"20\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"false\" x=\"0\" y=\"0\" width=\"320\" height=\"20\"/>\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"0\" y=\"0\" width=\"320\" height=\"20\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" shown=\"true\" x=\"6\" y=\"0\" width=\"39\" height=\"20\"/>\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" value=\"SSID\" name=\"3 of 3 Wi-Fi bars\" label=\"3 of 3 Wi-Fi bars\" enabled=\"true\" shown=\"true\" x=\"50\" y=\"0\" width=\"13\" height=\"20\"/>\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" name=\"2:12 PM\" label=\"2:12 PM\" enabled=\"true\" shown=\"true\" x=\"139\" y=\"0\" width=\"47\" height=\"20\"/>\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" name=\"-100% battery power\" label=\"-100% battery power\" enabled=\"true\" shown=\"true\" x=\"282\" y=\"0\" width=\"33\" height=\"20\"/>\n      </XCUIElementTypeOther>\n    </XCUIElementTypeStatusBar>\n  </XCUIElementTypeWindow>\n</XCUIElementTypeApplication>\n","sessionId":"B51E35B0-1BED-41F5-BAC2-3AD7E37DC321","status":0}
    '****** xctest source end *******

  TypeError: Cannot create property 'class' on string '<?xml version="1.0" encoding="UTF-8"?>
  <XCUIElementTypeApplication type="XCUIElementTypeApplication" name=" " label=" " enabled="true" shown="true" x="0" y="0" width="320" height="568">
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" shown="false" x="0" y="0" width="320" height="568">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="320" height="568">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="320" height="568"/>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="320" height="568"/>
    </XCUIElementTypeWindow>
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" shown="true" x="0" y="0" width="320" height="568">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="0" width="320" height="568">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="0" width="320" height="568">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="0" width="320" height="568">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="0" width="320" height="568">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="0" width="320" height="568">
                <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" shown="true" x="0" y="20" width="320" height="436">
                  <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" shown="false" x="-640" y="20" width="0" height="0"/>
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="-640" y="0" width="320" height="568">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="-640" y="0" width="320" height="568">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="-640" y="0" width="320" height="568"/>
                    </XCUIElementTypeOther>
                  </XCUIElementTypeOther>
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="-320" y="20" width="320" height="436">
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" value="Thursday, May 04" name="Calendar" label="Calendar" enabled="true" shown="false" x="-306" y="25" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Photos" label="Photos" enabled="true" shown="false" x="-230" y="25" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Maps" label="Maps" enabled="true" shown="false" x="-154" y="25" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Wallet" label="Wallet" enabled="true" shown="false" x="-78" y="25" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Reminders" label="Reminders" enabled="true" shown="false" x="-308" y="113" width="69" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="News" label="News" enabled="true" shown="false" x="-230" y="113" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Health" label="Health" enabled="true" shown="false" x="-154" y="113" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Settings" label="Settings" enabled="true" shown="false" x="-78" y="113" width="64" height="86"/>
                  </XCUIElementTypeOther>
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="20" width="320" height="436">
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Watch" label="Watch" enabled="true" shown="true" x="14" y="25" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" value="1 app" name="Extras" label="Extras folder" enabled="true" shown="true" x="90" y="25" width="64" height="86">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" name="Contacts" label="Contacts" enabled="true" shown="false" x="0" y="0" width="0" height="0"/>
                    </XCUIElementTypeIcon>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="iCloud Drive" label="iCloud Drive" enabled="true" shown="true" x="159" y="25" width="78" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="PICOOC" label="PICOOC" enabled="true" shown="true" x="242" y="25" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="WebDriverAgentRunner" label="WebDriverAgentRunner" enabled="true" shown="true" x="7" y="113" width="78" height="86"/>
                  </XCUIElementTypeOther>
                </XCUIElementTypeScrollView>
                <XCUIElementTypePageIndicator type="XCUIElementTypePageIndicator" value="Page 3 of 3" enabled="true" shown="true" x="0" y="445" width="320" height="43"/>
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="472" width="320" height="96">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="471" width="320" height="3">
                    <XCUIElementTypeImage type="XCUIElementTypeImage" enabled="true" shown="true" x="0" y="471" width="320" height="3"/>
                  </XCUIElementTypeOther>
                  <XCUIElementTypeOther type="XCUIElementTypeOther" name="Dock" label="Dock" enabled="true" shown="true" x="0" y="472" width="320" height="96">
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Safari" label="Safari" enabled="true" shown="true" x="90" y="484" width="64" height="86"/>
                    <XCUIElementTypeIcon type="XCUIElementTypeIcon" name="Messages" label="Messages" enabled="true" shown="true" x="165" y="484" width="66" height="86"/>
                  </XCUIElementTypeOther>
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="472" width="320" height="126">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="472" width="320" height="568"/>
                  </XCUIElementTypeOther>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeWindow>
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136"/>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136"/>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="640" height="1136"/>
    </XCUIElementTypeOther>
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" shown="false" x="0" y="0" width="320" height="568">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="320" height="568"/>
    </XCUIElementTypeWindow>
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" shown="true" x="0" y="0" width="320" height="568">
      <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" shown="true" x="0" y="0" width="320" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="false" x="0" y="0" width="320" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="0" y="0" width="320" height="20">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" shown="true" x="6" y="0" width="39" height="20"/>
          <XCUIElementTypeOther type="XCUIElementTypeOther" value="SSID" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" shown="true" x="50" y="0" width="13" height="20"/>
          <XCUIElementTypeOther type="XCUIElementTypeOther" name="2:12 PM" label="2:12 PM" enabled="true" shown="true" x="139" y="0" width="47" height="20"/>
          <XCUIElementTypeOther type="XCUIElementTypeOther" name="-100% battery power" label="-100% battery power" enabled="true" shown="true" x="282" y="0" width="33" height="20"/>
        </XCUIElementTypeOther>
      </XCUIElementTypeStatusBar>
    </XCUIElementTypeWindow>
  </XCUIElementTypeApplication>
  '
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:23:14)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor
