### ISSUE TITLE
Error with provisioning profile matching

### ISSUE THREAD

**Issue by damitas** [macacajs/app-inspector#84]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:
1.2.23

- os version / 系统:
10.12.3

- device  information / 设备版本:
iPhone 7
v 10.2.1

- terminal log / 终端输出信息:

server.js:16:12 [master] pid:30835 server start with config:
 { port: 5678,
  verbose: true,
  udid: '44ee2c7188710f29042ed42f51a6a3642914c3d6',
  ip: '10.8.0.42',
  host: 'damitas-mini',
  loaded_time: '2017-05-04 09:44:01' }
>> app-inspector.js:42:10 [master] pid:30835 server start at: http://10.8.0.42:5678
>> xctest-client.js:56:14 [master] pid:30835 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:238:14 [master] pid:30835 xcode version: 8.3.2
>> WebDriverAgent version: 1.1.6
>> xctest-client.js:175:14 [master] pid:30835 2017-05-04 09:44:03.261 xcodebuild[30841:2114182]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/AB762E9C-30F3-497C-853D-B36ECB46D658/Session-WebDriverAgentRunner-2017-05-04_094403-vPanjU.log

>> xctest-client.js:176:14 [master] pid:30835 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:30835 2017-05-04 09:44:03.261 xcodebuild[30841:2114144] [MT] IDETestOperationsObserverDebug: (894E2B42-6374-4D69-B7C6-95F7A74A3227) Beginning test session WebDriverAgentRunner-894E2B42-6374-4D69-B7C6-95F7A74A3227 at 2017-05-04 09:44:03.261 with Xcode 8E2002 on target <DVTiOSDevice: 0x7fc8ba7f3210> {
		deviceSerialNumber:         F2MSQ58HHG04
		identifier:                 44ee2c7188710f29042ed42f51a6a3642914c3d6
		deviceClass:                iPhone
		deviceName:                 An iPhone
		deviceIdentifier:           44ee2c7188710f29042ed42f51a6a3642914c3d6
		productVersion:             10.2.1
		buildVersion:               14D27
		deviceSoftwareVersion:      10.2.1 (14D27)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        27573817344
		deviceAvailableCapacity:    21105545216
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fc8ba3e1f90 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.2.1 (14D27))

>> xctest-client.js:176:14 [master] pid:30835 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:30835 2017-05-04 09:44:03.935 xcodebuild[30841:2114144] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/AB762E9C-30F3-497C-853D-B36ECB46D658/Session-WebDriverAgentRunner-2017-05-04_094403-vPanjU.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/AB762E9C-30F3-497C-853D-B36ECB46D658/Session-WebDriverAgentRunner-2017-05-04_094403-vPanjU.log}

>> xctest-client.js:176:14 [master] pid:30835 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:30835 
Testing failed:

>> xctest-client.js:176:14 [master] pid:30835 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:175:14 [master] pid:30835 	No profiles for 'dee2.facebook.WebDriverAgentRunner.damitas-mini' were found:  Xcode couldn't find a provisioning profile matching 'dee2.facebook.WebDriverAgentRunner.damitas-mini'.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/root/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/AB762E9C-30F3-497C-853D-B36ECB46D658/Session-WebDriverAgentRunner-2017-05-04_094403-vPanjU.log
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:176:14 [master] pid:30835 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:270:14 [master] pid:30835 killing deviceLogProc pid: 30838
>> xctest-client.js:275:14 [master] pid:30835 killing runnerProc pid: 30841
>> xctest-client.js:281:14 [master] pid:30835 killing iproxyProc pid: 30840
>> xctest-client.js:186:14 [master] pid:30835 xctest client exit with code: 65, signal: null
>> xctest-client.js:150:16 [master] pid:30835 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:262:14 [master] pid:30835 Fail to start xctest: undefined
>> app-inspector:66:44 [master] pid:30835 undefined
(node:30835) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:30835 undefined
(node:30835) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> xctest-client.js:214:14 [master] pid:30835 iproxy exit with code: null, signal: SIGKILL

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by SamuelZhaoY** [comment]
@damitas , to run on real device, you need to config your developer certificate in XCode project and install the permission profile on device.  Go to the follow directory  `/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd` and open XCode project `XCTestWD.xcodeproj` , try to config your own developer certificate

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector#ios-real-device
