### ISSUE TITLE
现在拿不到id相关信息了，只能用xpath

### ISSUE THREAD

**Issue by daisyzou** [macacajs/app-inspector#87]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:
1.2.25

- os version / 系统:
xcode 8.3.2
10.12.3

- device  information / 设备版本:
10.3.1

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by daisyzou** [comment]
另外，还有一个问题，app-inspector更新得很频繁，每次更新之后，旧版本就用不了了，有没有什么方法设置一下，旧版本可以继续使用

**Comment by hqfking** [comment]
Agree with daisyzou.  It used to get the name, but now it does not.  Somehow the old version works better.

**Comment by hujiachun** [comment]
对啊 。。。拿不到文本信息了

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/622142f5cf2848d8759562b37f1e92325eb3448d
