### ISSUE TITLE
更新到1.2.27后android启动报错 

### ISSUE THREAD

**Issue by MrDreamCacher** [macacajs/app-inspector#88]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:1.2.27

- os version / 系统:android

- device  information / 设备版本: 5.1

- terminal log / 终端输出信息:

```
{ [Error: Command failed: /Users/insomnia/Library/Android/sdk/platform-tools/adb -s emulator-5554 push /Users/insomnia/.nvm/versions/node/v5.7.0/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/undefined
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/insomnia/Library/Android/sdk/platform-tools/adb -s emulator-5554 push /Users/insomnia/.nvm/versions/node/v5.7.0/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/undefined' }

```

> try `app-inspector -u xxxx --verbose` for more log detail.

**Comment by thanksdanny** [comment]
出现了类似的报错
>> server.js:16:12 [master] pid:46337 server start with config:
 { port: 5679,
  verbose: true,
  udid: 'VS55SKGI99999999',
  ip: '172.25.202.88',
  host: 'thankdanny.local',
  loaded_time: '2017-05-09 12:53:55' }
>> app-inspector.js:43:12 [master] pid:46337 server start at: http://172.25.202.88:5679
{ Error: Command failed: /Users/thanksdanny/Library/Android/sdk/platform-tools/adb -s VS55SKGI99999999 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/undefined

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/thanksdanny/Library/Android/sdk/platform-tools/adb -s VS55SKGI99999999 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/undefined' }

**Comment by xmlbw** [comment]
更新完成后也报同样的错误，想着是没升级完全，删除后又全部升级，然后模拟器换真机，都不行。
  macaca-doctor version: 1.1.1


  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v7.6.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_131`
  ANDROID_HOME is set to `D:\android-sdk`
  Platforms is set to `D:\android-sdk\platforms\android-25`
  Android tools is set to `D:\android-sdk\tools\android.bat`
  ADB tool is set to `D:\android-sdk\platform-tools\adb.exe`
  GRADLE_HOME is not set

  Installed driver list:

  android: 2.0.0
  chrome: 1.0.5
  app-inspector：1.2.27

**Comment by ericshiny** [comment]
i faced this same issue.
At last, i upgrade the Xcode to the latest version.
The app-inspector works again!!!

**Comment by wlrnet** [comment]
这个问题有更新吗？更新到最新的1.2.28问题依旧，也是报这个错误

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/107
