### ISSUE TITLE
Can't see text attribute in 1.2.27 app inspector

### ISSUE THREAD

**Issue by gaboF** [macacajs/app-inspector#89]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号: 1.2.27

- os version / 系统: 10.12.4 Mac OS Sierra  + Xcode 8.3

- device  information / 设备版本: iPhone 5s - iOS 10.3 Simulator

When I analyze the UI of the app, I missing the Rawtext attribute in inspector panel. It disappeared after I upgraded to 1.2.27. 

I added a screenshot - you can see e.g. rawtext attribute is missing there.
![macaca_app_inspector](https://cloud.githubusercontent.com/assets/3266275/25863038/81af260a-34ea-11e7-86f6-826ef23b2a56.png)

Please fix.

**Comment by JShearenSpark** [comment]
Issue is still persisting on version app-inspector@1.2.28

**Comment by xudafeng** [comment]
update
