### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ewg777** [macacajs/app-inspector#90]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号:
the latest

- os version / 系统:
windows 10

- device  information / 设备版本:
Meizu U20

- terminal log / 终端输出信息:

```

```

> try `app-inspector -u xxxx --verbose` for more log detail.

C:\Users\user>app-inspector -u U20HVCPG2282W --verbose
>> server.js:16:12 [master] pid:7812 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'U20HVCPG2282W',
  ip: '192.168.77.177',
  host: 'user',
  loaded_time: '2017-05-10 15:07:39' }
>> app-inspector.js:43:12 [master] pid:7812 server start at: http://192.168.77.177:5678
{ Error: Command failed: C:\Androidsdk\/platform-tools/adb -s U20HVCPG2282W push C:\Users\user\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Androidsdk\\/platform-tools/adb -s U20HVCPG2282W push C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\app-inspector\\node_modules\\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by xmlbw** [comment]
自从更新完到现在都不正常，再等等看吧。

**Comment by Ewg777** [comment]
How to resolve this?

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor

**Comment by youngchow** [comment]
@xudafeng , same issue here, could you please tell me how to solve it? Btw, after i run command "macaca doctor", show likes this:
macaca-doctor version: 2.0.3


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.7.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.26.0

  Android checklist:

  JAVA version is `1.8.0_141`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/roczhang/android-sdks`
  Platforms is set to `/Users/roczhang/android-sdks/platforms/android-23`
  ADB tool is set to `/Users/roczhang/android-sdks/platform-tools/adb`
  gradle is installed, version: 4.2

  Installed driver list:
