### ISSUE TITLE
1.2.28 Mac ios真机不显示name文本信息

### ISSUE THREAD

**Issue by hujiachun** [macacajs/app-inspector#92]
<img width="869" alt="2017-05-11 14 02 04" src="https://cloud.githubusercontent.com/assets/17762932/25934836/a210ce80-3652-11e7-973d-2118812e15bc.png">

**Comment by magaofei** [comment]
我也遇到了

**Comment by SamuelZhaoY** [comment]
请使用当前最新版本的macaca 驱动， 进行测试， 当前版本做了相关改动 @magaofei @hujiachun
