### ISSUE TITLE
升级到最新版本后连接模拟机报错，无法打开inspector

### ISSUE THREAD

**Issue by pkfameli** [macacajs/app-inspector#96]
- app inspector version / 版本号:app-inspector@1.2.29
macaca平台也升级到了最新版本

![image](https://cloud.githubusercontent.com/assets/26532559/26088945/969525b4-3a2c-11e7-8b6c-2c9920443c01.png)

- os version / 系统:10.12.2

- device  information / 设备版本:ios 10.3、iPhone6模拟器

启动app-inspector 报错如下
![image](https://cloud.githubusercontent.com/assets/26532559/26088967/bf6b5d0a-3a2c-11e7-8538-9ad5f19c9c21.png)

在升级前一切都是好的，可以顺利启动的，现在升级到最新版本后，就无法启动了。

**Comment by xudafeng** [comment]
update
