### ISSUE TITLE
app-inspector@1.2.29 更新后 Internal Server Error，之前的版本没问题

### ISSUE THREAD

**Issue by zhoutq** [macacajs/app-inspector#98]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号: app-inspector@1.2.29

- os version / 系统: 10.12.4

- device  information / 设备版本: 10.3.1

- terminal log / 终端输出信息:

```
>> xctestwd start with port: 8001
>> XCTestWD version: 1.0.14
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
>> iOS device started: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>> inspector start at: http://10.10.10.105:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

```

> try `app-inspector -u xxxx --verbose` for more log detail.
>> server.js:16:12 [master] pid:10676 server start with config:
 { port: 5678,
  verbose: true,
  udid: '92153e85add19bc487c268bab954126502c58da9',
  ip: '10.10.10.105',
  host: 'ZTQ',
  loaded_time: '2017-05-16 15:31:07' }
>> app-inspector.js:43:12 [master] pid:10676 server start at: http://10.10.10.105:5678
>> xctest-client.js:53:14 [master] pid:10676 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:226:14 [master] pid:10676 xcode version: 8.3.2
>> XCTestWD version: 1.0.14
>> xctest-client.js:174:14 [master] pid:10676 2017-05-16 15:31:08.946 xcodebuild[10684:129148] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 2017-05-16 15:31:08.947 xcodebuild[10684:129148] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSImageNamed.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-05-16 15:31:08.947 xcodebuild[10684:129148] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ESJsonFormat.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-05-16 15:31:08.948 xcodebuild[10684:129148] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ColorSenseRainbow.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-05-16 15:31:08.948 xcodebuild[10684:129148] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 2017-05-16 15:31:10.359 xcodebuild[10684:129151]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/zhoutq/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/6AA3D5BD-4FD4-4121-B437-90765BF67640/Session-XCTestWDUITests-2017-05-16_153110-0mANsY.log

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 2017-05-16 15:31:10.360 xcodebuild[10684:129148] [MT] IDETestOperationsObserverDebug: (8EDF8CEC-DF67-4AFC-87C4-4D050986EFD7) Beginning test session XCTestWDUITests-8EDF8CEC-DF67-4AFC-87C4-4D050986EFD7 at 2017-05-16 15:31:10.360 with Xcode 8E2002 on target <DVTiOSDevice: 0x7fda398ee040> {
		deviceSerialNumber:         F2LL8Q2NFQ11
		identifier:                 92153e85add19bc487c268bab954126502c58da9
		deviceClass:                iPhone
		deviceName:                 Circles-iPhone5c
		deviceIdentifier:           92153e85add19bc487c268bab954126502c58da9
		productVersion:             10.3.1
		buildVersion:               14E304
		deviceSoftwareVersion:      10.3.1 (14E304)
		deviceArchitecture:         armv7s
		deviceTotalCapacity:        13103882240
		deviceAvailableCapacity:    1616072704
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fda397bc510 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.1 (14E304))

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/c9a0a90c2d515086970b22bf735ef8a8/92153e85add19bc487c268bab954126502c58da9/XCTestWDUITests-Runner.app
state->new_bundle: /Users/zhoutq/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphoneos/XCTestWDUITests-Runner.app
state->dst_bundle: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.2D1ZHN/XCTestWDUITests-Runner.app_sparse.ipa/Payload//XCTestWDUITests-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.2D1ZHN/XCTestWDUITests-Runner.app_sparse.ipa

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.2D1ZHN/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.2D1ZHN/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/5cd1985a7cffd3645f7699f861e01c12/92153e85add19bc487c268bab954126502c58da9/XCTestWD.app
state->new_bundle: /Users/zhoutq/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Products/Debug-iphoneos/XCTestWD.app
state->dst_bundle: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWD.app.OIZHL3/XCTestWD.app_sparse.ipa/Payload//XCTestWD.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWD.app.OIZHL3/XCTestWD.app_sparse.ipa

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWD.app.OIZHL3/XCTestWD.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:10676 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/7b/lhx0gb414pb5kdkbsk23dywc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWD.app.OIZHL3/XCTestWD.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:175:14 [master] pid:10676 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:55:14 [master] pid:10676 Proxy: wd/hub/session:POST to http://127.0.0.1:8001wd/hub/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> proxy.js:61:22 [master] pid:10676 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:80
>> xctest-client.js:249:14 [master] pid:10676 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:80
>> xctest-client.js:257:14 [master] pid:10676 killing deviceLogProc pid: 10681
>> xctest-client.js:262:14 [master] pid:10676 killing runnerProc pid: 10684
>> xctest-client.js:268:14 [master] pid:10676 killing iproxyProc pid: 10683

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor
