### ISSUE TITLE
App-Inspector 1.2.29 socjet hang up on some parts of the app only

### ISSUE THREAD

**Issue by DanielPradoPino** [macacajs/app-inspector#99]
**真机问题先参考 https://testerhome.com/topics/5953**

- app inspector version / 版本号: 1.2.29

- os version / 系统: Mac OS Sierra

- device  information / 设备版本: iPhone 7 10.3 simulator

- terminal log / 终端输出信息:

Hi guys,

First thanks for this amazing app, I was using it without any issue until last update to 1.2.29, after this update I started getting errors on certain parts of my app, in example, I am able to inspect any part of my application but Registration or Login, can it be related to some SSL issue?

I  attached 
the complete log for you to check, I am not able to do figure what is the reason for this.

[Session-XCTestWDUITests-2017-05-16_120054-yYi2dd.txt](https://github.com/macacajs/app-inspector/files/1004062/Session-XCTestWDUITests-2017-05-16_120054-yYi2dd.txt)

Thanks.

**Comment by DanielPradoPino** [comment]
I was able to bypass this ssl error by enabling 1.2.27 to run and disabling xcuitestwd, now I am able to inspect anything in my app.

**Comment by xudafeng** [comment]
npm i macaca-cli -g && macaca doctor
